### ISSUE TITLE
Missing API requirement

### ISSUE THREAD

**Issue by JeffJerousek** [MicrosoftDocs/Azure-RMSDocs#1022]
Might be leftover from the preview but I needed to add the UnifiedPolicy.Tenant.Read Application Permission before I could use Set-AIPAuthentication.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7383893-1714-4be5-a499-7f9463fab5e2
* Version Independent ID: f566dfdf-bbae-f671-f012-b5c71e40bf14
* Content: [Use PowerShell with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell#to-create-and-configure-the-azure-ad-applications-for-set-aipauthentication---preview-client)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@JeffJerousek  Hi Jeff, what version of the unified labeling client are you using?

**Comment by Jeff-Jerousek** [comment]
UL_Preview 2.4.38.0

**Comment by cabailey** [comment]
@JeffJerousek  Yes, this additional permission was missing from the new instructions for the preview client - now added (steps 14-17 from https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell#to-create-and-configure-the-azure-ad-applications-for-set-aipauthentication---preview-client).  Thanks for flagging this!

**Comment by cabailey** [comment]
@JeffJerousek Now the instructions are updated, closing this issue - you can always reopen if you think the update is still missing information.
#please-close
