### ISSUE TITLE
Getting label guid

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1028]
Is there any way to get the label GUID from the SCC admin center? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603aa64b-3813-ca4a-9df6-19aed2193f60
* Version Independent ID: b6ec3e81-f89f-53c6-78a8-4ed0b43dd91c
* Content: [Configure the Azure Information Protection policy - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy#label-information-stored-in-emails-and-documents)
* Content Source: [Azure-RMSDocs/configure-policy.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Unfortunately not.  When you need the label GUID for PowerShell, we documented the following command:  Get-Label | Format-Table -Property DisplayName, Name, Guid

More info: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#specifying-the-identity-for-the-label-policy-or-label

**Comment by cabailey** [comment]
#please-close
