### ISSUE TITLE
Error in article

### ISSUE THREAD

**Issue by jonatanhovgaard** [MicrosoftDocs/Azure-RMSDocs#1035]
Setting NTFS deny permissions on "licensing.asmx" does not result in a redirect of the clients to Azure Information Protection. I think the article should include setting the same deny permission on "server.asmx" in the same directory on the AD RMS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0d29ee-00b5-5a48-b259-d62e75c22d05
* Version Independent ID: 8c6632dc-5926-a431-7f7b-f3f2469170f6
* Content: [Migrate AD RMS-Azure Information Protection - Phase 3](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#feedback)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase3.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase3.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jonatanhovgaard Investigating …. I've not heard that this file needs a deny configuration as well. have you tried as documented and it didn't work?  If so, was your scenario for publishing or consumption, or have you tried both?

**Comment by jonatanhovgaard** [comment]
According to the documentation, clients will discover RMS information in the following order: Registry, SCP and Cloud. As I understand the documentation, you will configure an explicit NTFS "deny" on "license.asmx" to force clients to move on to use the RMS in Azure. When setting the deny permission on "license.asmx" clients are still able to retrieve templates from the on prem RMS and use those templates to sign documents. After I configured the same NTFS deny on "Server.asmx" the clients finally started to use AIP instead of AD RMS. It seems to me that the documentation should instruct the customer to set a deny permission on both files?

**Comment by cabailey** [comment]
@jonatanhovgaard : I've checked this with several people now and had multiple confirmations that setting a deny on this second file should not be necessary for DNS redirection. For example "when it works correctly, DNS redirection occurs before server.asmx is exercised and before templates are pulled down." with the recommendation to get IPCLOG files to investigate why the SRV record isn't working as expected.  If you can reproduce this, please open a support ticket in the Azure portal for a support engineer to check the SRV record and log files.

https://docs.microsoft.com/en-us/azure/information-protection/information-support#to-contact-microsoft-support

**Comment by cabailey** [comment]
#please-close
