### ISSUE TITLE
include information on MAC office locations / logs

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#1037]
include information on MAC office locations / logs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af8c9c8-cf06-49a4-5f22-bba526bc2734
* Version Independent ID: 868c2079-00f4-eae3-822f-49ae6c8ef63c
* Content: [Refresh Azure RMS templates - AIP](https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates#feedback)
* Content Source: [Azure-RMSDocs/refresh-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/refresh-templates.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bakerm00 Hi Michael, this page is specifically for refreshing protection templates on clients.  For questions about Office for Mac, such as where they store their log files, please use their documentation.

**Comment by cabailey** [comment]
#please-close
