### ISSUE TITLE
This article directly conflicts

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/Azure-RMSDocs#1039]
Version history https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history says :

"As with the scanner from the classic client, the scanner protects Office files and PDF files. Currently, you can't configure other file types to be protected by this version of the scanner."

Yet this article lists : 

Images: .jpg, .jpe, .jpeg, .jif, .jfif, .jfi. png, .tif, .tiff
Autodesk Design Review 2013: .dwfx
.Tiff, .Zip files ect...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044457bf-06a4-cc9e-3425-780a748c50ed
* Version Independent ID: 4e587393-64eb-4cd7-f2a6-e0e22e22a8bd
* Content: [File types supported - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Mark7even  Hi Mark, yes the client can protect more than Office files and PDF but the scanner doesn't by default.  While the scanner from the unified labeling client is in preview, there isn't yet a way to override this default behavior to support protection for these other file types.  The registry method (https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#editing-the-registry-for-the-scanner) that the scanner uses for the classic client doesn't work for the unified labeling client.

Overriding the default behavior so the scanner from the unified labeling client can protect these other file types will be supported by the time the scanner goes GA.

**Comment by cabailey** [comment]
@Mark7even  We've just documented a new advanced setting to configure this so that the scanner from the unified labeling client can protect file types other than Office files and PDFs: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#change-which-file-types-to-protect 

Now there's a documented solution for the scanner to protect the same file types as the client, I'll mark this issue as resolved.

#please-close
