### ISSUE TITLE
Note on classic client to UL client upgrades

### ISSUE THREAD

**Issue by SteveBurkettNZ** [MicrosoftDocs/Azure-RMSDocs#1047]
Suggest you add a line about upgrading from the classic to the UL client. E.g. Do you need to uninstall the classic client first?  Or will the UL client auto-upgrade the classic client for you?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by SteveBurkettNZ** [comment]
Ah, see there is a note on the Overview page regarding this. However its easy to miss if you jump in to the Install the Client for Users page without reading the Overview first...      Link:  https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide#upgrading-and-maintaining-the-azure-information-protection-unified-labeling-client

**Comment by cabailey** [comment]
@SteveBurkettNZ Yes, we put this information in the Upgrade section of the admin guide, and there's also a note (actually, "Tip") in the version history page (https://docs.microsoft.com/azure/information-protection/rms-client/client-version-release-history), with of course links to install each client from the download page. 

I could put another reference/link in the "Install the client for users" page, but I was sensitive to over-promoting an upgrade to the unified labeling client. My thinking was that customers using this page had already decided that they wanted to install the classic client and yet another reference to upgrading to the unified labeling client might seem like we're not respecting their choice and trying to change their mind?  Repeated references can be misconstrued.

**Comment by cabailey** [comment]
@SteveBurkettNZ Hi Steve, I haven't heard back from you & whether you think we still need another reference to upgrading to the unified labeling client, here. I think for now, I'm going to monitor this and definitely revisit this when there's an end of support date for the classic client (no ETA on that yet).

**Comment by cabailey** [comment]
#please-close
