### ISSUE TITLE
HYOK usage inconsistency

### ISSUE THREAD

**Issue by ksagala** [MicrosoftDocs/Azure-RMSDocs#1053]
There is information that user should choose unified labeling client, when he use HYOK, and in comparison table below there is information that HYOK is not supported in unified labeling client. So it is inconsistency.

**Comment by cabailey** [comment]
@ksagala That's correct - the unified labeling client doesn't support HYOK and if you have users who require this functionality, they should use the classic client instead.  Where exactly do you see the inconsistency in the documentation, so we can fix that?

**Comment by ksagala** [comment]
In article (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#choose-which-labeling-client-to-use-for-windows-computers) there is comparison of clients and there is sentence:
Use the Azure Information Protection unified labeling client on Windows computers for labels and policy settings that can also be used by MacOS, iOS, and Android, you want to label files independently from Office 365 apps, and you don’t need features that are only supported by the classic client. **These features currently include protecting content with an on-premises key (HYOK)** and a general availability version of the scanner for on-premises data stores.

**Comment by cabailey** [comment]
@ksagala  I don't see an inconsistency here. This sentence says HYOK is one of the features that are only supported by the classic client.

**Comment by ksagala** [comment]
Indeed, after deeper analyze of those sentence, I see you are right. But If you reading fast, you see that there are features in three different version and in HYOK is mention in unified labelling description, not classic one. So if reader don't go further it can believe that if he wants to use HYOK, he should choose this client.

**Comment by cabailey** [comment]
@ksagala  Yes, for this complex situation, you have to read carefully and the table is there for people who want a quick comparison check of the features. Pleased you found the table helpful!
#please-close
