### ISSUE TITLE
Second Step 4 should be Step 5 in the last section

### ISSUE THREAD

**Issue by mustafafarooq** [MicrosoftDocs/Azure-RMSDocs#1056]
Under the "Specify and use the Token parameter for Set-AIPAuthentication " section there are two step 4's.

Step 4: Create a task that runs the PowerShell script
Step 4: Confirm that the token is saved and delete the PowerShell script

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9edb2c-4c7e-f9f5-a7fc-74c475dd083e
* Version Independent ID: 27d918c1-55e4-024b-35e6-2a9621b95cd7
* Content: [Use PowerShell with the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-powershell#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mustafafarooq You're quite right! I'll fix it today. Thanks for flagging this.

**Comment by cabailey** [comment]
Live now.
#please-close
