### ISSUE TITLE
Why do I see rpmsg files within my gmail mailbox

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/Azure-RMSDocs#1059]
Microsoft says AIP is compatible with Gmail but how does it work? Everytime I send a protected message to an email account it appears as a rpmsg attachment. If we have to configure our gmail accounts into Outlook it is not as supported as MS state... is there another way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d01ed44-c873-ea84-0fda-44ea8ab13409
* Version Independent ID: 4b005dc9-5456-1229-4346-62f1c6147dfc
* Content: [View protected files with the Azure Information Protection viewer](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-view-use-files)
* Content Source: [Azure-RMSDocs/rms-client/client-view-use-files.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-view-use-files.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Martony78 To use Azure Information Protection with Gmail accounts, you need Office 365 Message Encryption on the sending organization. See https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection#additional-integration-for-email

**Comment by cabailey** [comment]
@Martony78  I don't see any further questions from you after providing this information, so I'll ask for this issue to be closed. You can still reply, or open a new issue.
#please-close
