### ISSUE TITLE
Label typo

### ISSUE THREAD

**Issue by Nick-Gillott** [MicrosoftDocs/Azure-RMSDocs#1066]
The label includes MSIP_Label_0e421e6d-ea17-4fdb-8f01-93a3e71333b8_Enabled=True; in Example 1. The end character / semi-colon needs to be removed as that is a separator between the labels. Note - using the separator allows encryption to work with Outlook desktop but it breaks both OWA and iOS. Removing the semi-colon will mean that it works for all devices
Ping me for further details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4f87ed-6649-6998-889b-58f14556db29
* Version Independent ID: 46468916-b0f0-56b9-23d7-add664cc49b1
* Content: [Exchange Online mail flow rules for Azure Information Protection labels](https://docs.microsoft.com/en-us/azure/information-protection/configure-exo-rules#feedback)
* Content Source: [Azure-RMSDocs/configure-exo-rules.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-exo-rules.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Now fixed in this document, thanks for flagging this
#please-close
