### ISSUE TITLE
AzInfoProtection_UL Client is no longer preview

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/Azure-RMSDocs#1068]
Please remove preview designation from this article. https://docs.microsoft.com/en-us/azure/information-protection/quickstart-findsensitiveinfo#prerequisites

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6e055-5f55-5b2f-1877-e277f2954c66
* Version Independent ID: 7b9f2e2a-0d2e-f541-001d-ff76715314df
* Content: [Quickstart - Find sensitive info with the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/quickstart-findsensitiveinfo)
* Content Source: [Azure-RMSDocs/quickstart-findsensitiveinfo.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/quickstart-findsensitiveinfo.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@SLeuthold hold  Thanks for flagging we missed updating the file name for the unified labeling client.  Now fixed.
#please-close
