### ISSUE TITLE
Getting this error - Cannot find an overload for "AcquireTokenAsync" and the argument count: "4".

### ISSUE THREAD

**Issue by adlpenagithub** [MicrosoftDocs/Azure-RMSDocs#1069]
Hi there,

Can you please let me know how to fix this error?

Thanks,
AJ

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2d0b851-b857-b2b4-2e8e-78638bb30698
* Version Independent ID: 30e1b7ec-b3c4-592a-d9ef-2318fd0124b9
* Content: [Concepts - Using PowerShell to acquire an access token.](https://docs.microsoft.com/en-us/information-protection/develop/concept-authentication-acquire-token-ps#feedback)
* Content Source: [mip/develop/concept-authentication-acquire-token-ps.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-authentication-acquire-token-ps.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by cabailey** [comment]
#assign:msmbaldwin

**Comment by cricketthomas** [comment]
I don't think it works using powershell core. switching back to powershell works just fine though

**Comment by mlottner** [comment]
@msmbaldwin Can you take a look at this?
