### ISSUE TITLE
Great article but also please describe the scenerios or conditions for Revoke key 

### ISSUE THREAD

**Issue by achandrasekhar1976** [MicrosoftDocs/Azure-RMSDocs#1074]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a7e847-721a-8064-5d47-abcef59ec12f
* Version Independent ID: 9031c4fb-1e77-25cc-25ca-ad1ab07e7dd7
* Content: [Customer-managed - AIP tenant key life cycle operations](https://docs.microsoft.com/en-us/azure/information-protection/operations-customer-managed-tenant-key)
* Content Source: [Azure-RMSDocs/operations-customer-managed-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/operations-customer-managed-tenant-key.md)
* Service: **information-protection**
* Sub-service: **kms**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@achandrasekhar1976  You would normally revoke your tenant key only if it was compromised and/or it was in the hands of somebody you don't want to be able to decrypt content that has been protected by your organization.  When the key is revoked, they can't then use it to decrypt your protected content - but neither can anybody else. I've got some wording ready to publish that explains this in more detail but waiting for PM review and signoff before it can go live.

**Comment by cabailey** [comment]
@achandrasekhar1976  The revoke section is now updated for clarifications so I'm closing this issue but you can always reopen it if you have outstanding questions.
#please-close

**Comment by achandrasekhar1976** [comment]
Thanks a lot
