### ISSUE TITLE
MSICP Support for 1.0.2456

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1080]
What is the support status for MSCIP 1.0.2456? I assume that it is no longer supported but its not listed above. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d40811-9908-39df-a632-a31be13d9ad9
* Version Independent ID: b5c3157d-20d1-57d3-5332-41e385ebd7b9
* Content: [Azure Information Protection client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/client-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@DeanGross  In what context are you using this version of MSIPC?  You can have different versions of MSIPC installed on the same computer, which is why we list the version included with the Azure Information Protection client.  If you're using it with this client, no, it's not supported because not listed with one of the supported versions of the client.

**Comment by DeanGross** [comment]
I have a customer that has previously deployed the RMS client with MSCIP 1.0.2456 and I'm trying to confirm that it must be updated. during their migration from AD RMS to AIP

**Comment by cabailey** [comment]
I don't think there's a minimal version for migration, or we would have documented it here: https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-to-azure-rms#prerequisites-for-migrating-ad-rms-to-azure-information-protection

Checking to confirm.

**Comment by cabailey** [comment]
Confirmed - for migration from AD RMS, the only technical requirement for the RMS client is that it supports Crypto Mode 2, and all versions of MSIPC support that.  However, if you want to use DNS redirection (https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#step-7-reconfigure-windows-computers-to-use-azure-information-protection) there is a minimum version of MSIPC that's built into Office.  I don't know what that minimum version is, but we document the minimum Office version (Office 2016 click-to-run), which takes care of that.

**Comment by cabailey** [comment]
@DeanGross  Can this issue be closed now, Dean?

**Comment by DeanGross** [comment]
yes, thanks again for the quick response and excellent support.

**Comment by cabailey** [comment]
#please-close
