### ISSUE TITLE
One Time Passcode

### ISSUE THREAD

**Issue by ElanShudnow** [MicrosoftDocs/Azure-RMSDocs#1087]
I'm sorry, but this paragraph is thoroughly confusing, "However, the application opening the protected content must be able to support the authentication being used. For this reason, federated social providers such as Google, and onetime passcode authentication should be used for email only, and only when you use Exchange Online and the new capabilities from Office 365 Message Encryption."

From my experience, in Exchange Online, you can use a transport rule that will either apply a specific AIP Label or apply Office 365 Message Encryption.  If the e-mail goes to a federated social partner, AIP label will be applied.  If the e-mail goes to a non-federated social partner, the user is required to do a one time passcode.  I haven't tested this in a while but that's what my experience has been.  But this paragraph should be rewritten to be more clear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b8020d-3f87-1a2d-74e4-f132640010c4
* Version Independent ID: cb6f52e8-2d35-d899-8011-6f16058490de
* Content: [Configure an Azure Information Protection label for protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-protection#more-information-about-add-any-authenticated-users)
* Content Source: [Azure-RMSDocs/configure-policy-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-protection.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mlottner** [comment]
@ElanShudnow Thanks for taking the time to leave your comment on docs. 
I agree that the language you flagged can be improved and clarified. I'll work to make sure that happens in the next few days. 
Appreciate your contribution to our community.

**Comment by mlottner** [comment]
@ElanShudnow This topic will be updated in the next publish. Thanks again for your contribution to MSDocs! 
#please-close
