### ISSUE TITLE
Whether to support mac catalyst?

### ISSUE THREAD

**Issue by CancerQ** [MicrosoftDocs/Azure-RMSDocs#1090]
Whether to support mac catalyst?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efbdf85f-692a-9d6e-2e9d-4360a18313b8
* Version Independent ID: 4674e96a-8a5e-138c-95f9-7e3ef4756ff1
* Content: [Get started](https://docs.microsoft.com/en-us/azure/information-protection/develop/get-started#feedback)
* Content Source: [Azure-RMSDocs/develop/get-started.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/develop/get-started.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
@msmbaldwin Can you take a look?

**Comment by msmbaldwin** [comment]
#please-close
