### ISSUE TITLE
Are there any samples available in C# to remove protection from files? 

### ISSUE THREAD

**Issue by mishakogan** [MicrosoftDocs/Azure-RMSDocs#1094]
Are there any samples available in C# to remove protection (in CPP `RemoveProtectionAction`)  from files? 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ccface4-b3ed-dc67-3254-554b14e606e0
* Version Independent ID: 737cfb40-a41d-cc1d-71d2-c3f66714a512
* Content: [class mip::RemoveProtectionAction](https://docs.microsoft.com/en-us/information-protection/develop/reference/class_mip_removeprotectionaction#feedback)
* Content Source: [mip/develop/reference/class_mip_removeprotectionaction.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/reference/class_mip_removeprotectionaction.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
@msmbaldwin Can you take a look?

**Comment by msmbaldwin** [comment]
Hui, @mishakogan. Although we do intend to provide samples for RemoveProtectionAction in the future, we do not have any currently published. Thank you. #please-close
