### ISSUE TITLE
IRM in SharePoint Online works with AIP reader and Nitro Pro and Foxit Reader but not Acrobat Reader with MIP Plugin

### ISSUE THREAD

**Issue by marcdayton** [MicrosoftDocs/Azure-RMSDocs#1097]
Hi,
We are trying to setup IRM on a document library.  I have been through the IRM configuration and can access the protected PDFs with the Microsoft AIP Viewer and Nitro Pro PDF Reader, but I cannot get Acrobat Reader DS with the plugin to access the files.  I just get the message that the PDF is protected and to use a valid reader.  Foxit Pro doesn't work either.  Our company is standardized on Acrobat Reader DS, so I need to get this working.
I have confirmed the correct version of Reader, have the latest appropriate version of the plugin.  I have been combing the Internet and just cannot get this to work.  Firewall doesn't seem to be an issue because the behavior is the same on my home computer with the same setup and also on my work computer from home.
I have been through all of the tech docs below:
https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Now-Available-Our-integration-with-Adobe-Acrobat-extends/ba-p/270553
https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Starting-Today-Use-Adobe-Acrobat-Reader-for-PDFs-protected-by/ba-p/262738
https://techcommunity.microsoft.com/t5/Azure-Information-Protection/New-support-for-PDF-encryption-with-Microsoft-Information/ba-p/262757
https://techcommunity.microsoft.com/t5/Azure-Information-Protection/General-Availability-of-Adobe-Acrobat-Reader-Integration-with/ba-p/298396
https://techcommunity.microsoft.com/t5/azure-information-protection/using-azure-information-protection-to-protect-pdf-s-and-adobe/ba-p/282010

Any help or guidance would be appreciated.

**Comment by marcdayton** [comment]
I forgot to say we are accessing the files in a SharePoint Online Tenant E3,  Running Windows 10 workstations.  Thank you.

**Comment by marcdayton** [comment]
Update:  Installed the newest Foxit Pro Reader and it was working today with a trial RMS plugin.  Downloaded the Dec 10 Acrobat Reader and Acrobat MIP Plugins installed them and still get the error that it cannot open the file.  Is the Acrobat MIP plugin not compatible with IRM in SharePoint?

**Comment by marcdayton** [comment]
Assuming Acrobat and the MS AIP plugin do not support IRM in SharePoint.

**Comment by cunninghamp** [comment]
@marcdayton - did you ever find a solution to this? I am facing the same issue with SharePoint IRM-protected PDFs now opening in Acrobat Reader with the MIP/AIP plugin. Any PDF separated protected by the AIP client will open fine in Acrobat Reader.

**Comment by markdepalma** [comment]
@cunninghamp, I have also been looking for an update on this...

**Comment by jianhuashi2038** [comment]
@markdepalma @marcdayton 

Did you find any change on this?
Looks now the Acrobat Reader can open SharePoint IRM procted PDF file well now.

**Comment by markdepalma** [comment]
I

> ### **[markdepalma](/markdepalma) ** commented [1 hour ago](#issuecomment-1020148709)

You're right! I just tried and it is working!
