### ISSUE TITLE
Encrypt-Only in Sensitivity labels

### ISSUE THREAD

**Issue by joeri-juramento** [MicrosoftDocs/Azure-RMSDocs#1104]
This page states: _"Exchange Online is rolling out a new option, Encrypt-Only. This option is not available for label configuration. However, when you know who the recipients will be, you can use this example to configure a label with the same set of usage rights."_

Why is the label **Encrypt Only** not available as label configuration? Am I missing something?

I have created a list of sensitivity labels inspired by the (new) default, however between the non-encrypted labels (like General) and a High Confidential label, I have a need for encrypting e-mails, but not preventing forwarding. "Do not forward" also communicates a negative message to my recipient. This text is in their screen, sometimes even red; it might feel to them I do not trust them and I just want to keep our e-mail messages E2E private. (I would prefer another phrase, but that is another story.)

So I would like to have easy accessible encryption that is tied to my identity as sender and to the recipient(s). Like the Outlook button 'Encrypt', it encrypts to contents and attachments but does not prevent copying, printing or forwarding. Why can't I have that behaviour in my own sensitivity label? 

The problems are:
- The Encrypt button is a different menu than Sensitivity labels in Outlook for Windows, Outlook for Web; it would be a better experience if I can put them together (in the same sensitivity menu via a specific Label) when the user visits that to make a choice. 
- *Outlook for iOS does not have en Encrypt button*, only sensitivity menu. I tried to create a sensitivity label mimicking the Encrypt button, but the label does not show up. 

**Obviously I cannot pre-define the recipients in a label-template because that can change every e-mail.** In only do this for projects.

Example 4 on this page describes the goal, but the interaction to get there doesn't fit.

**Please let me know if I have missed something or how to achieve this behaviour?**

Note: I have worked with transport rules but this does have the downside it also encrypts messages to zendesk and even microsoft helpdesk and it is too inclusive to be practical. The benefit of having sensitivity labels is that you can define what you want.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b8020d-3f87-1a2d-74e4-f132640010c4
* Version Independent ID: cb6f52e8-2d35-d899-8011-6f16058490de
* Content: [Configure an Azure Information Protection label for protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-protection#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-protection.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by cabailey** [comment]
@joeri-juramento  There are some technical challenges to support this configuration on a label - for example, not all Outlook clients support the Encrypt-Only action (unlike Do Not Forward).  However, it's a popular request and the most effective way to make your voice heard is by using UserVoice.  You can get to this site by selecting the "This product" button at the bottom of the page instead of "This page" in the Feedback section.   You'll find others have already requested this so you can up-vote it and track progress: https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/39705655-support-encrypt-only-as-a-label-protection-policy

**Comment by mlottner** [comment]
@joeri-juramento I'm closing this documentation issue for now as I hope you joined other users in the forum linked previously, but feel free to continue to comment here if/as needed. 
#please-close
