### ISSUE TITLE
Protected pdf via SPO IRM policy does not open 

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#1106]
I have download a pdf file from SPO IRM protected document library. I have member access to the site and the library and when i try to open this protected pdf file with AIP Viewer, it just says you do not have access to the document. Then I tried to download the same document with owner permission and document opens in the viewer. Then I tried to download a word file with member access, and I am able to open it in word. So what is causing the issue? Does this work with the documents which are downloaded with members access? FYI..this viewer was installed as part of AIP Unified labeling client

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11db9693-c3bf-ccda-c55f-f9ccfb954059
* Version Independent ID: d71de514-76e5-f17e-bd83-683d42591132
* Content: [View protected files with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-view-use-files)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-view-use-files.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-view-use-files.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@prashant1380 Thanks for taking the time to leave us documentation feedback. 
For AIP product support, open a [support ticket](https://docs.microsoft.com/en-us/azure/information-protection/information-support#to-contact-microsoft-support). 
I'm closing this docs issue for now, but feel free to continue to continue to comment here if/as needed. 
#please-close
