### ISSUE TITLE
Missing Uninstall Instructions

### ISSUE THREAD

**Issue by ChristopherTulip** [MicrosoftDocs/Azure-RMSDocs#1109]
Missing uninstall commands for the executable install. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c12b247-129e-a67c-e463-04d506b25c0c
* Version Independent ID: 4d80d86b-2461-d088-22e9-970d84e0e283
* Content: [Install the Azure Information Protection client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-install#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@ChristopherTulip Thanks for taking the time to give us your docs feedback. 
We'll work to get the commands from our engineering team and add them to the next publish. 
Closing this issue for now, but feel free to continue to comment here if/as needed. 
Thanks for your contribution to docs!
#please-close
