### ISSUE TITLE
Client limitations missing

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/Azure-RMSDocs#1110]
Setting different visual markings for Word, Excel, PowerPoint, and Outlook. This only works for the AIP classic client. It is not available in the unified client. please  could you add this information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@iaasazure Thanks for taking the time to comment on docs. 
You are correct. Added the notions where relevant. 
Appreciate your contribution to our community!

**Comment by mlottner** [comment]
#please-close
