### ISSUE TITLE
Stop-AIPScan cmdlet doesn't exist

### ISSUE THREAD

**Issue by mariuszo-at-microsoft-com** [MicrosoftDocs/Azure-RMSDocs#1117]
The "Stop a scan" chapter mentions "Stop-AIPSCan" cmdlet, while it doesn't seem to exist (at least for AIP unified client)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#feedback)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mariuszo-at-microsoft-com Thanks for taking the time to comment on MSDocs. 
You are correct. This addition was somehow missed in the last update. It is being added and will be published to the PowerShell reference shortly. 
Appreciate your contribution to our docs community. Closing this issue for now, but free to continue to comment here if/as needed. #please-close
