### ISSUE TITLE
Confirmation needed

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#1121]
Can you please confirm that the reports/features mentioned in this doc are available even in case of AIP UL client usage and when labels are created only in Security and Compliance Center?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@prashant1380  Yes, this is documented in the prerequisites "Both the unified labeling client and the classic client are supported."  What isn't currently supported, is built-in labeling from Office aps.  It doesn't matter where the labels are created/published.  What matters is support from the endpoint (the labeling client in this case) to send their reporting information.

**Comment by mlottner** [comment]
#please-close
