### ISSUE TITLE
Add Outlook add-in Name

### ISSUE THREAD

**Issue by ThomasKur** [MicrosoftDocs/Azure-RMSDocs#1125]
For Word, Excel and PowerPoint you directly add the correct add-in name which should be added to the allowed add-in list. Please also add the one for Outlook: MSIP.OutlookAddin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install#feedback)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@ThomasKur Thanks for your docs feedback. 
I'm not sure I totally understand what you are asking. 
If you have the GPO that manages load behavior for the add-ins, you should allow Azure Information Protection add-ins. But aren't they GUID, not name based? 
If I didn't understand your question, let me know so I can try to assist further.

**Comment by ThomasKur** [comment]
No as you could see in the docs it's already written, that it is the ProgID for Word, Excel and PowerPoint. Just for Outlook is only a link to e generic article without information what to exclude. 
-------
For Office 2013 and later versions, configure group policy to ensure that the Microsoft Azure Information Protection add-in for Office applications is always enabled. Without this configuration, the Microsoft Azure Information Protection add-in can get disabled and users will not be able to label their documents and emails in their Office application.

**- For Outlook: Use the group policy setting documented in System Administrator control over add-ins from the Office documentation.**
- For Word, Excel, and PowerPoint: Use the group policy setting list of managed add-ins documented in the Support article No Add-ins loaded due to group policy settings for Office 2013 and Office 2016 programs.
Specify the following programmatic identifiers (**ProgID**) for Azure Information Protection, and set the option to 1: The add-in is always enabled.
**- For Word: MSIP.WordAddin
- For Excel: MSIP.ExcelAddin
- For PowerPoint: MSIP.PowerPointAddin**

**Comment by mlottner** [comment]
@ThomasKur Thanks so much for taking the time to submit your improvement suggestion to docs. 
I've added the name as your suggested. Closing this issue for now, but feel free to continue to comment/question here if/as needed. Appreciate your contribution to our docs community!
#please-close
