### ISSUE TITLE
Example variable test string incorrect

### ISSUE THREAD

**Issue by alana257** [MicrosoftDocs/Azure-RMSDocs#1127]
The example of using a variables in a visual marking is incorrect. Whilst the example "Document: ${item.name} Classification: ${item.label}" is correct for the AIP Classic client, it needs to be updated as the UL client is case sensitive. So should be something like "Document: ${Item.Name} Classification: ${Item.Label}".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@alana257 Thanks for taking the time to give us feedback. 
You are correct. I updated the example to reflect the capitalization. 
Appreciate your contribution to our docs community!

**Comment by mlottner** [comment]
#please-close
