### ISSUE TITLE
Would this same process work with Office 365 Sensitivity Labels?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/Azure-RMSDocs#1128]
Would this same process work with Office 365 Sensitivity Labels?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4f87ed-6649-6998-889b-58f14556db29
* Version Independent ID: 46468916-b0f0-56b9-23d7-add664cc49b1
* Content: [Exchange Online mail flow rules for Azure Information Protection labels](https://docs.microsoft.com/en-us/azure/information-protection/configure-exo-rules#feedback)
* Content Source: [Azure-RMSDocs/configure-exo-rules.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-exo-rules.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mtwelve Thanks for taking the time to ask this docs question. 
For Office 365 sensitivity label queries, checking the Office 365 doc site is the best way to make sure you have the most accurate and up to date product information. Sensitivity labels in Office 365 are described [here](https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels?view=o365-worldwide). 
I'm closing this issue for now, but feel free to continue to post or ask Azure Information Protection related documentation issues in the thread as needed. 
#please-close
