### ISSUE TITLE
Client reconfiguration by using registry edits

### ISSUE THREAD

**Issue by explodinghat** [MicrosoftDocs/Azure-RMSDocs#1130]
The wording is confusing - 'This method is suitable for all Windows clients and should be used if they do not run Office 365 apps, or Office 2019. or Office 2016, but instead, an earlier version of Office.' 
Is the full stop after 'office 2019' supposed to be a comma? Or is there further configuration required for Office 2016. Also does this apply to non click-to-run installs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0d29ee-00b5-5a48-b259-d62e75c22d05
* Version Independent ID: 8c6632dc-5926-a431-7f7b-f3f2469170f6
* Content: [Migrate AD RMS-Azure Information Protection - Phase 3](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#client-reconfiguration-by-using-registry-edits)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase3.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase3.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mlottner** [comment]
@explodinghat Thanks for taking the time to leave us your questions.  
The . was a mistake and will be fixed to a comma in an imminent publish. With regards to the question of application to non-click-to-run installs, I've sent your question to our engineering team for clarification and will respond here with an answer. I'll also update the page in docs with this information. 
Appreciate your contribution to our docs community.

**Comment by mlottner** [comment]
@explodinghat Clarified that it also applies to installs that are not click-to-run, and will update the page accordingly in our next publish. 
Thanks again for your contribution to Azure Information Protection docs. 
#please-close
