### ISSUE TITLE
Is CentOS 7 really supported?

### ISSUE THREAD

**Issue by Chaz6** [MicrosoftDocs/Azure-RMSDocs#1132]
The page says CentOS 7 is supported, but the link to "How to build libs and sample apps" (https://github.com/AzureAD/rms-sdk-for-cpp/wiki/How-to-Build) has no instructions for CentOS. It probably also needs to be updated because Qt 5.7 is old. The current release is 5.14.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3aa66908-6ef0-5256-500d-3210f920ece8
* Version Independent ID: 5170e5d7-a4ef-cc6b-9a28-ebeab8d99a32
* Content: [Linux setup](https://docs.microsoft.com/en-us/azure/information-protection/develop/linux-setup#how-to-build-and-use)
* Content Source: [Azure-RMSDocs/develop/linux-setup.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/develop/linux-setup.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
@msmbaldwin Can you take a look?

**Comment by msmbaldwin** [comment]
Hi, @CHaz6. CentOS 7 is supported in the RMS SADK, however, we are no longer updating that content. We strongly encourage you to investigate the MIP SDK as an alternative.  https://docs.microsoft.com/en-us/information-protection/develop/.  Thank you! #please-close
