### ISSUE TITLE
AIP MIGRATION THEN USING WHICH CLIENT

### ISSUE THREAD

**Issue by karimzaki** [MicrosoftDocs/Azure-RMSDocs#1142]
Actually this article misses lot of informations in real world
First when i migrate to unified labeling i cannot take decision shall i publish or shall i copy policies, also shall i use AIp classic or unified just theories no practice

**Comment by mlottner** [comment]
@karimzaki Thanks for your feedback. 
Can you let me know exactly which article you are referring to and what kind of information you would like for us to add there or enhance? 
Appreciate your contribution to our documentation.

**Comment by karimzaki** [comment]
this is what i m talking about 
https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels

**Comment by mlottner** [comment]
@karimzaki This forum is for documentation questions, but based on your comments, I think you are looking for product guidance from a support or customer experience specialist. Have you joined the [Information Protection product discussion group on Yammer](https://www.yammer.com/askipteam)? 
I'm going to close this issue for now as specific product guidance based on your environment is outside of the scope of docs, but feel free to continue to comment here if/as needed. 
#please-close
