### ISSUE TITLE
This page is really outdated 

### ISSUE THREAD

**Issue by itguysocal** [MicrosoftDocs/Azure-RMSDocs#1144]
this page should be heavily updated for the new Unified Label experience. 
It shows things like Revoke that are no longer available in the new UL experience

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection? - AIP](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mlottner** [comment]
@itguysocal Thanks so much for taking the time to leave us feedback!
Absolutely agree. In fact, this article is already on our schedule for a refresh as soon as possible. 
Appreciate your contribution to docs. 
#please-close
