### ISSUE TITLE
SPO permissions

### ISSUE THREAD

**Issue by AJRus** [MicrosoftDocs/Azure-RMSDocs#1146]
Is there a similar document for SharePoint Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6e055-5f55-5b2f-1877-e277f2954c66
* Version Independent ID: 7b9f2e2a-0d2e-f541-001d-ff76715314df
* Content: [Quickstart - Find sensitive info with the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/quickstart-findsensitiveinfo?source=docs#permission-users-to-scan-sharepoint-repositories)
* Content Source: [Azure-RMSDocs/quickstart-findsensitiveinfo.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/quickstart-findsensitiveinfo.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@AJRus  Thanks for taking the time to comment on docs. 
Azure Information Protection is currently On-Prem only. 
As of today, for SPO, you'll need to use Microsoft Cloud App Security, or wait for the public preview of built-in labeling for SPO data at rest. 
I'm closing this issue for now, but feel free to continue to comment or ask questions as needed.

**Comment by mlottner** [comment]
#please-close

**Comment by AJRus** [comment]
@mlottner - but the licensing model for Azure IP2 shows support for SPO..?
