### ISSUE TITLE
Is AIP the same thing as AIP for Office 365?

### ISSUE THREAD

**Issue by jebalert** [MicrosoftDocs/Azure-RMSDocs#1150]
"Azure Information Protection for Office 365 is included in the Office 365 Enterprise E3 and E5 plans. It can also be purchased as a standalone with these plans: Office 365 Enterprise E1, Office 365 Enterprise K1, Exchange Online Plan 1, Exchange Online Plan 2, and Exchange Online Kiosk." https://products.office.com/en-us/business/azure-information-protection-for-office-365?activetab=pivot:faqtab

Is it the same thing or is AIP for Office 365 just OME or is it both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection? - AIP](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by mlottner** [comment]
@jebalert Thanks so much for taking the time to post your product question on docs. 
The AIP for Office 365 described on the page you linked is indeed, the same Azure Information Protection. 
The components of Azure Information Protection (client, scanner etc.) are used in conjunction with M365 to offer a comprehensive classification and labelling solution. 
"Office 365 Message Encryption is an online service that's built on Microsoft Azure Rights Management (Azure RMS) which is part of Azure Information Protection. This includes encryption, identity, and authorization policies to help secure your email. You can encrypt messages by using rights management templates, the Do Not Forward option, and the encrypt-only option."
Hope this answered your question. I'm closing this issue for now, but feel free to continue to comment here in the future if/ as needed. 
#please-close
