### ISSUE TITLE
Missing "your tenant name" on point 20

### ISSUE THREAD

**Issue by Kreism** [MicrosoftDocs/Azure-RMSDocs#1151]
Please correct point 20:
`20. Back on the API permissions pane, in the Grant consent section, select Grant admin consent for and select Yes for the confirmation prompt.`
to --> 
`20. Back on the API permissions pane, in the Grant consent section, select Grant admin consent for "<your tenant name>" and select Yes for the confirmation prompt.`
Thanks Martin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9edb2c-4c7e-f9f5-a7fc-74c475dd083e
* Version Independent ID: 27d918c1-55e4-024b-35e6-2a9621b95cd7
* Content: [Use PowerShell with the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-powershell#how-to-label-files-non-interactively-for-azure-information-protection)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Kreism Thanks for taking the time to comment on MSDocs. 
We've checked your suggestion and added it to the page. 
Appreciate your contribution to our community. 
#please-close
