### ISSUE TITLE
AIP Unified Labeling Client now supports AIP Scanner

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/Azure-RMSDocs#1152]
This page tells us "These features currently include protecting content with an on-premises key (HYOK) and a general availability version of the scanner for on-premises data stores.".
HYOK is still not supported in the AIP UL client but in my understanding AIP scanner is:
https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Martony78 consuming HYOK content is supported via the AIP UL client. Answered you about this in a previous thread. Do you feel more changes are required here?

**Comment by mlottner** [comment]
@Martony78 Closing this in the meantime, but feel free to continue to comment here if/as needed. 
#please-close
