### ISSUE TITLE
AIP UL client not mentionned

### ISSUE THREAD

**Issue by Martony78** [MicrosoftDocs/Azure-RMSDocs#1153]
This page does not mention the AIP Unified Labeling as a not supported scenario but the client page explains the AIP claccis is the only supported client.
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client
My understanding is we can't protect documents using HYOK with the AIP UL client but can we at least open them?
You should add this this to the supported/unsupported scenarios section

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d475e54-14a8-9a51-a509-782ebe7a65fa
* Version Independent ID: 164664ff-d57c-46a3-97dc-760d2365f978
* Content: [HYOK protection for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/configure-adrms-restrictions#feedback)
* Content Source: [Azure-RMSDocs/configure-adrms-restrictions.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-adrms-restrictions.md)
* Service: **information-protection**
* Sub-service: **hyok**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@Martony78 Thanks for taking the time to leave your feedback on docs. 
Yes, you can configure the AIP UL client on Windows to consume HYOK protected content. Configuration details are found [here](https://review.docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device?branch=pr-en-us-3799#step-2-authorize-apps-for-your-devices). I'll work to update the supported/unsupported scenario section in the next publish, so it is more clear. 

Closing this in the meantime, but feel free to continue to comment here as needed. 
#please-close
