### ISSUE TITLE
Firewall port dependencies 

### ISSUE THREAD

**Issue by aakrol** [MicrosoftDocs/Azure-RMSDocs#1154]
These IP addresses are listed as required connectivity, 13.107.6.181 and 13.107.9.181, what are the specific port requirements for connectivity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements#feedback)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @aakrol!

Thanks for taking the time to send your question!

I'm going to check back with the team about this one. 
We'll update the page as needed with an upcoming publish.

I'm closing this in the meantime, but feel free to continue to comment here if you have more feedback.

#please-close
