### ISSUE TITLE
How does this work with Exchange Online Protection and Office 365 Advanced Threat Protection?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/Azure-RMSDocs#1155]
Hello,

If we are using AIP to label and encrypt (protect) emails being sent/received in Exchange Online; does this break the ability for email content to be scanned by the Safe Links and Safe Attachments features of Office 365 Advanced Threat Protection?

Safe Links - https://docs.microsoft.com/en-gb/microsoft-365/security/office-365-security/atp-safe-links?view=o365-worldwide
Safe Attachments - https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/atp-safe-attachments?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0ca219-540d-2816-3f51-d02f3f3667e0
* Version Independent ID: 44a2f2ce-c32f-9870-863e-5635f7e2b22d
* Content: [FAQs for Azure RMS - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-rms)
* Content Source: [Azure-RMSDocs/faqs-rms.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-rms.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@mtwelve Thanks for taking the time to ask great questions on our docs!
At present number of Microsoft Information Protection services are working to streamline interdependent workflows between products. This is a scenario where AIP is involved, but doesn't the manage the workflow you described.    
Exchange Online should work for protected mails and attachments (if those were protected at the same time as mail), but cannot work with pre-protected files (which may or may not be your scenario). 
For details and help with this specific scenario, reach out to your support or product rep from either Exchange Online or Office 365 to get the exact guidance on how to design the best workflows for your specific needs. 
You can also post in their tech community groups for guidance and product clarification. 
I'm closing this issue for now, but feel free to continue to comment here if/as needed. 
#please-close
