### ISSUE TITLE
how to ensure that authentication method to be one time passcode for prtected document outisde orgamisation

### ISSUE THREAD

**Issue by anchalchoubey** [MicrosoftDocs/Azure-RMSDocs#1156]
This is serious product flaw that AIP protected doc like pdf,excel,word , ppt, images etc can be viewed by external org user when their organisation restricted their right to download AIP clinet OR their federated identifty in official user email is not google or microsoft  . This defeat whole purpoes of AIP protection as even legit external users whom we want to accesss protected files cant see and blame on this solution poor arhitecture flaw.

What we want is one time passcode not only for protected email but for is attachments to be open in apps like excel, word and PPT not only on windows bit on IOS,Android and Mac. asap.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9532c6a-66f7-963b-5ea6-e52e0e92b788
* Version Independent ID: 982f65e1-89a2-4f3e-1057-38e92d27b58b
* Content: [Configuring secure document collaboration with Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/secure-collaboration-documents#feedback)
* Content Source: [Azure-RMSDocs/secure-collaboration-documents.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/secure-collaboration-documents.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@anchalchoubey Thanks for taking the time to leave this feedback on Azure Information Protection docs. Your product feedback and experiences are important and should be shared and communicated with the product team via the [AIP yammer group](https://www.yammer.com/askipteam). 
Retain this method for communicating documentation issues, or questions related to the documentation. 
Closing this issue for now, but feel free to comment here again if/as needed. 
#please-close
