### ISSUE TITLE
Does this mean that Office documents and emails are encrypted with a 128 bit key?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/Azure-RMSDocs#1157]
Hello,

Does the list of specific scenarios (Footnote 1) where a 256 bit encryption key is used to protect the content of files mean that in all other scenarios the key is 128 bit?

I am primarily concerned with understanding the implications of content encryption for Office documents and emails.

Footnote 1 - https://docs.microsoft.com/en-us/azure/information-protection/how-does-it-work#footnote-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7f3d8e-57eb-43db-e03c-3eadba114e86
* Version Independent ID: 2c3d65a1-9f43-4849-e674-f9ceda054c67
* Content: [How Azure RMS works - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/how-does-it-work)
* Content Source: [Azure-RMSDocs/how-does-it-work.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/how-does-it-work.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@mtwelve For the content key, yes.  It can't be higher than 128 bits to support Office 2010.  Note that the tenant key is a minimum of 1024 bits (defaults to 2048),

**Comment by mtwelve** [comment]
@cabailey if you are not utilising Office 2010 and/or are not interested in supporting it, can you force it to always use a 256 bit key?

**Comment by cabailey** [comment]
@mtwelve  No. because Azure Information Protection supports Office 2010 and although you might not use it internally, users send emails/documents externally and you can't control what versions of Office other people use.  There is a UserVoice entry for this that you might want to comment on and vote: https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/19602334-office-apps-on-all-platforms-move-to-aes256-cbc-f

**Comment by mtwelve** [comment]
@cabailey thank you for clarifying and for directing me to a relevant UserVoice 👍

**Comment by cabailey** [comment]
#please-close
