### ISSUE TITLE
Do you have any tips section

### ISSUE THREAD

**Issue by gwenbettwy** [MicrosoftDocs/Azure-RMSDocs#1158]
It looks like thee is supposed to be a clickable link.  But it is just bold.  I do not see where "Design and deploy simple policies" is immediatly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0ca219-540d-2816-3f51-d02f3f3667e0
* Version Independent ID: 44a2f2ce-c32f-9870-863e-5635f7e2b22d
* Content: [FAQs for Azure RMS - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-rms)
* Content Source: [Azure-RMSDocs/faqs-rms.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-rms.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@gwenbettwy Thanks for taking the time to give us feedback on Azure Information Protection docs! 
We'll add some additional information to this page in our next publish to make it easier to locate. 
I'm closing this issue for now, but feel free to continue to comment here if/as needed. 
Appreciate your contribution to our content! 
#please-close
