### ISSUE TITLE
Documentation says support for .NET Standard 2.0, but doesn't work on Linux

### ISSUE THREAD

**Issue by tremblaysimon** [MicrosoftDocs/Azure-RMSDocs#1159]
When MIP.Initialize is called, there is a System.DllNotFoundException thrown:

Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Microsoft.InformationProtection.Utils.UnsafeKernel32NativeMethods.LoadLibrary(String dllToLoad)
   at Microsoft.InformationProtection.Utils.Loader.LoadDlls(String dllFolder, String dllName, String[] dllDependencies)
   at Microsoft.InformationProtection.MIP.Initialize(MipComponent mipComponent, String path)
   at test_mip.Program.Main(String[] args) in /home/simon/workspace/test-mip/Program.cs:line 12

Maybe that documentation page should mention that it works only on a Windows-based platform? Or there is an undocumented way to get it works on Linux?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f08174c-3073-8833-30bb-ea54e9c6486d
* Version Independent ID: b496a7db-67ca-8d96-afe7-10fb6d7012fc
* Content: [Microsoft Information Protection SDK C# Wrapper Overview](https://docs.microsoft.com/en-us/information-protection/develop/concept-summary-csharp)
* Content Source: [mip/develop/concept-summary-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-summary-csharp.md)
* Service: **information-protection**
* GitHub Login: @tommoser
* Microsoft Alias: **tommos**

**Comment by tommoser** [comment]
Thanks for the feedback. We'll get an update in there for this. There's no support at the moment for Linux platforms using the .NET package.

**Comment by tommoser** [comment]
We now support .NET Standard on Ubuntu 18.04.

**Comment by batamig** [comment]
Hi @tremblaysimon - thanks for taking the time to send us your feedback! 

I see that @tommoser 's already replied, so I'm going to close this. Feel free to continue to comment here as needed.

#please-close
