### ISSUE TITLE
Difference between Classification and Protection

### ISSUE THREAD

**Issue by michael-pollack** [MicrosoftDocs/Azure-RMSDocs#1160]
Hello,

Where can I find some clarification on the difference between classification and protection described in this document?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8ab6d-63a2-dd69-7394-dd1d1577507c
* Version Independent ID: 57385923-cbf3-1cc7-a4b7-89d93e7a83ae
* Content: [File types supported - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-file-types)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@michael-pollack Thanks for taking the time to comment on MSDocs!
The Azure Information Protection classic client is currently slated for deprecation as of March 2021. Having said that, the following [overview description of the product](https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-file-types.md#file-types-supported-for-protection) offers a better description of the differences between classification and protection. 
I'm closing this issue for now, but feel free to continue to comment here if/as needed. 
#please-close
