### ISSUE TITLE
unable to import az.keyvault and aipservice at the same time

### ISSUE THREAD

**Issue by TechNosisDerek** [MicrosoftDocs/Azure-RMSDocs#1161]
Hi, I am trying to connect to aipservice using credentials saved in keyvault but am unable to load both modules at the same time. I get different error message depending on the order they are loaded.
I have tried on a brand new windows 10 instance with powershell 7.0.0

The code to reproduce is simply: 
```
get-module
import-module aipservice
get-module
import-module az.keyvault
get-module
```

![aip error](https://user-images.githubusercontent.com/63754161/79919316-c1cdc100-83f3-11ea-9bfd-f95c2e7fc401.png)

**Comment by TechNosisDerek** [comment]
I compared loaded assemblies for each module 
az.keyvault also loads az.accounts. az.accounts
Az.Accounts\1.7.5\Microsoft.WindowsAzure.Storage.dll is version 9.3.0.0
AIPService\1.0.0.1\Microsoft.WindowsAzure.Storage.dll is version 9.3.2.0
I have renamed the aipservice file to .old and copied the 9.3.0.0 into that directory.
I don't know if there is a way to have some sort of checking if the assembly is already loaded and allowing the load if it is some sort of compatible range is detected.

I also don't know if this should also be reported on the AZ module

**Comment by mlottner** [comment]
@TechNosisDerek Thanks for taking the time to comment on MSDocs! 
I've tagged the docs writer for Azure Key Vault, but a support call or post on the relevant product yammer group is the best way to directly source tech product support. 
@msmbaldwin Can you possibly take a look at this?

**Comment by msmbaldwin** [comment]
#please-close
