### ISSUE TITLE
Capabilities

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/Azure-RMSDocs#1162]
Please add a capabilities matrix for using information protection with PDF files (e.g. encryption, content markings, searchability in SPO, Office on the Web viewing, etc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@danmyhre Thanks for taking the time to contribute to improving MSDocs!
We've reviewed your suggestions for adding the matrix and will be updating the relevant article in a future publish cycle. 
Appreciate your contribution to our community.
I'm closing this for now, but feel free to continue to comment here as needed. 
#please-close
