### ISSUE TITLE
Please Add guidance on opening .pfile protected content.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/Azure-RMSDocs#1165]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/issues/26

@juhirao commented 14 hours ago — with docs.microsoft.com
If the application is not associated with the OS in advance for the file extension after pfile protection is decrypted, an "unknown error" is displayed.
I would like you to add a supplement to this event in the article.
Or, i want you to display a hint that suggests whether or not an application is associated as an error message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8ab6d-63a2-dd69-7394-dd1d1577507c
* Version Independent ID: 57385923-cbf3-1cc7-a4b7-89d93e7a83ae
* Content: [File types supported - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-file-types#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@juhirao Thanks for taking the time to comment on our docs. 
After discussing with the product managers, we'll be adding add this guidance into the docs in the coming days. It will probably take a few weeks after the addition to show in the translated versions. 

Appreciate your contribution! 
#please-close
