### ISSUE TITLE
About Custom Permissions selection UI in the protection workflow.

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Azure-RMSDocs#1169]
I would like to know the current situation about displaying the Selection UI for custom permissions as mentioned in the RMS SDK 4.2 release notes FAQ.
The following Docs article describes a plan to add a custom permission UI as "Known issue".

https://docs.microsoft.com/en-us/azure/information-protection/develop/release-notes
---
Q: I don’t see a Custom Permissions selection UI in the protection workflow. Why?
A: This is a known issue and will be addressed later.
---

I understand that custom permission buttons in the MIP SDK have been migrated to labeling future and that MIP SDK is recommended.
However, while my customer is also moving to Unified Labelling Function, they are not looking to migrate their apps that use custom permissions, and they have a strong desire to use the RMS SDK 4.2 for the time being.

Customers will be relieved if the features of known issues have already been improved.
However, if the current situation has not yet been completed and there is no prospect of correction, I think it is better  to correct this public information.
Is it correct to understand that important comment "No further enhancements are planned for the Microsoft Rights Management Service SDK." takes precedence over the article description?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f7a5355-4a8c-f509-5f05-5ab77b113b57
* Version Independent ID: 588ace6d-6fe0-488f-cd8d-433864df9b73
* Content: [Rrelease notes for the Rights Management Services SDK v4.x](https://docs.microsoft.com/en-us/azure/information-protection/develop/release-notes)
* Content Source: [Azure-RMSDocs/develop/release-notes.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/develop/release-notes.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
@juhirao Thanks for taking the time to comment on docs!
@msmbaldwin Can you take a look at this?

**Comment by msmbaldwin** [comment]
Hello @juhirao. The RMS SDK is no longer being developed, so this known issue is unlikely to be addressed. I have updated the article to reflect that. We recommend you instead investigate the [Microsoft Information Protection SDK](/information-protection/develop).  Thank you! #please-close
