### ISSUE TITLE
Admin role requirements

### ISSUE THREAD

**Issue by timkkk** [MicrosoftDocs/Azure-RMSDocs#1171]
Can this page say something about the required admin roles? I think at least for grant consent a GA is necessary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7383893-1714-4be5-a499-7f9463fab5e2
* Version Independent ID: f566dfdf-bbae-f671-f012-b5c71e40bf14
* Content: [Use PowerShell with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell#feedback)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@timkkk Thanks for the great suggestion. Yes, I will work on an improvement for the page that details the admin roles required and republish it ASAP. 
Appreciate your contribution to our docs community. 
#please-close
