### ISSUE TITLE
Incorrect code

### ISSUE THREAD

**Issue by poortom1004** [MicrosoftDocs/Azure-RMSDocs#1173]
This code is bad:
$irmConfig = Get-IRMConfiguration
$list = $irmConfig.LicensingLocation
$list += "&lt;YourTenantURL&gt;/_wmcs/licensing"
Set-IRMConfiguration -LicensingLocation $list
Set-IRMConfiguration -internallicensingenabled $false
Set-IRMConfiguration -internallicensingenabled $true

I think the intention was to get two URLs into an array, but the actual result from the first $list = is a whole array with many other properties.  I'm thinking you meant for that line of code to be the following:
$list = $irmConfig.LicensingLocation.AbsoluteUri
or
$list = $irmConfig.LicensingLocation.OriginalString

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db563c7f-28b3-abec-2310-b9c7d963b4e9
* Version Independent ID: 448c88a4-3e53-a50a-16ac-9b7e71faecab
* Content: [Migrate AD RMS-Azure Information Protection - Phase 1](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase1)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase1.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase1.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@poortom1004 Thanks for taking the time to contribute to improving MSDocs!
We've reviewed your submission and will be updating the relevant article in the next publish. 
Appreciate your contribution to our community.
Closing this issue in the meantime, but feel free to continue to comment here as needed. 
#please-close
