### ISSUE TITLE
Error: HResult: 0x80070002 - Could not find file

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/Azure-RMSDocs#1174]
Under the https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#run-a-discovery-cycle-and-view-reports-for-the-scanner section add if Error: HResult: 0x80070002 - Could not find file
then check the support of long paths: Windows 2016 and above with the group policy - Enable Win32 long paths

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#feedback)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@DavidTaig Thanks for taking the time to comment on docs. 
I've sent your suggestion to the dev team for confirmation and will update the page accordingly. 
Appreciate your contribution to our community. 
I'm going to close this issue in the meantime, but feel free to continue to comment here as needed. 
#please-close
