### ISSUE TITLE
HYOK support - Unified labeling client - Yes or No?

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/Azure-RMSDocs#1175]
Under - Which client should you use?
Azure Information Protection unified labeling client - protecting content with an on-premises key (HYOK)
Compare the labeling clients for Windows computers - Unified labeling client - No
What is correct?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-au/azure/information-protection/rms-client/use-client#feedback)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@DavidTaig Thanks for taking the time to ask for clarification about Azure Information Protection Documentation!
With the Unified Labeling client, you can use AD RMS protected files, however the Unified Labeling client cannot apply HYOK labels.  Based on the confusion this documentation generated, I'm going to modify the documentation to clarify and remove the ambiguity around the limitations and possible use case scenarios. 
Closing this issue for now, but feel free to continue to comment here if you need additional information. We do appreciate your contribution to our docs community! 
#please-close
