### ISSUE TITLE
Should explain how to create a new template in new Security/Compliance Center

### ISSUE THREAD

**Issue by takeakitake** [MicrosoftDocs/Azure-RMSDocs#1176]
At "To create a new template" section on this page explain information for old (will be deprecated) Azure Portal. But there are no information for new Security/Compliance Center.
https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-templates#to-create-a-new-template
Please create "To create a new template" contents for new Security/Compliance Center. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc239db-314a-afdf-2d21-9f2cba07efcd
* Version Independent ID: 31f8cd80-db51-3e11-6f1c-bfaf241deb7c
* Content: [Configure and manage templates for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-templates#to-create-a-new-template)
* Content Source: [Azure-RMSDocs/configure-policy-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-templates.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@takeakitake Thanks so much for taking the time to comment on our documentation. 
Actually, this process can be done via PowerShell using the [Add-AipServiceTemplate cmdlet](https://docs.microsoft.com/powershell/module/aipservice/add-aipservicetemplate?view=azureipps) and is not completed in the Security and Compliance Center. I've updated the article to explain this in the next publish. 
Appreciate your contribution!
#please-close
