### ISSUE TITLE
Protect is now called Sensitivity 

### ISSUE THREAD

**Issue by challengelogic** [MicrosoftDocs/Azure-RMSDocs#1180]
[Enter feedback here]

"Protect" is now called "Sensitivity" in the newest AIP UL client

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c05358db-2c5f-fd01-1077-4255f06352be
* Version Independent ID: fa8b14ad-4aa1-c34c-9103-e3f048ee8828
* Content: [Tutorial - Edit the Azure Information Protection policy - AIP](https://docs.microsoft.com/en-gb/azure/information-protection/infoprotect-quick-start-tutorial)
* Content Source: [Azure-RMSDocs/infoprotect-quick-start-tutorial.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/infoprotect-quick-start-tutorial.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@challengelogic Thanks for taking the time to give us your feedback on the docs. 
This tutorial is based on the classic client and has not yet been redesigned for the unified labeling client. We are in the process of making those changes now. 
I'm going to close this issue as it is work in progress, but feel free to continue to comment here as needed. 
Appreciate your contribution to our community. 
#please-close
