### ISSUE TITLE
broken link for "document tracking site"

### ISSUE THREAD

**Issue by hctrr** [MicrosoftDocs/Azure-RMSDocs#1182]
[Label information stored in emails and documents](
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-track-revoke#using-a-web-browser-to-track-and-revoke-documents-that-you-have-registered)

first bullet: Using your Windows PC, Mac computer, or mobile device, visit the **document tracking site**.

the document tracking site hyperlink takes you over to: https://track.azurerms.com/
which is now a broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74c2dca-2883-0833-9176-0f5ea2cd9c62
* Version Independent ID: f02aa653-1300-b8c2-7b75-ad17f082dbfe
* Content: [Track & revoke documents - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-track-revoke)
* Content Source: [Azure-RMSDocs/rms-client/client-track-revoke.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-track-revoke.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@hctrr Thanks for taking the time to comment on our docs!
When I use the live link, I'm taken to the [tracking site](https://track.azurerms.com/#/landing?sourceUrl=%2F) and see the live tracking page as shown below. 
Can I suggest you try again on a different browser and make sure the link/site it isn't blocked by your company firewall? 
I'm closing this issue for now, but feel free to comment again if you need more help to resolve. 
Appreciate your contribution to our community. 
<img width="724" alt="AIP document tracking site" src="https://user-images.githubusercontent.com/41567042/83388445-23bc1600-a3f7-11ea-9373-8b5859e38ec3.png">
#please-close
