### ISSUE TITLE
Does the 200 user limit for scoped policy apply to Unified Label client as well ?

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#1189]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce76b92f-404f-374b-a01b-a3fd2e8ffff7
* Version Independent ID: 75ed4519-dd4a-d21c-4f28-ca859d75a3c1
* Content: [Configure scoped policies for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-scope)
* Content Source: [Azure-RMSDocs/configure-policy-scope.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-scope.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@bholzmmc Thanks for taking the time to ask your question on MSDocs. 
Yes, scoped policy limit applies for unified labeling. I'll adjust the page so it is more clear in the next version we publish. We do appreciate your contribution to our docs community! 
Closing this issue for now, but feel free to continue to comment here if/as needed. 
#please-close

**Comment by bholzmmc** [comment]
Are there any limits the number of members in a group?  Or the number of members in total among all groups specified in a scoped policy ?

Brian

**Comment by mlottner** [comment]
@bholzmmc From the AIP side, there are no limits on the number of members in a group or on total members of all groups for a scoped policy. There may be group limits on the AAD side, but again, not from AIP. You can check out the AAD group limitations documentation [here](https://docs.microsoft.comazure/active-directory/users-groups-roles/directory-service-limits-restrictions#:~:text=A%20user%20can%20create%20a,members%20of%20a%20single%20group.).
