### ISSUE TITLE
Powershell Aip V2 Policy setting mandatory missing

### ISSUE THREAD

**Issue by sidey79** [MicrosoftDocs/Azure-RMSDocs#1191]
The advanced configuration policy option is missing a  description how this can be configured via powershell:

All documents and emails must have a label

Reference:
https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md

May the advanced configuration key ist just named mandatory, but this is nowhere specified in the docs.

**Comment by mlottner** [comment]
@sidey79 Thanks for taking the time to leave us your question on MSDocs. 
I'm confused as to which exactly advanced configuration policy option you are referring to from the page you linked. Are you working with the  Office 365 Security and Compliance Center PowerShell as indicated?

**Comment by sidey79** [comment]
The issue is, regarding this sentence:

When you use the label policy setting of All documents and emails must have a label, users are prompted to select a label when they first save an Office document and when they send an email.

I did not found the Powershell parameter how to configure this option:
All documents and emails must have a label

There is a powershell parameter named mandatory which ist not documented. May it is this switch or not.

Would bei nice if the docs can be extended to explain all options via powershell, so that creating a policy via new-labelPolicy can be comleted without the s&c portal.


https://docs.microsoft.com/en-us/powershell/module/exchange/new-labelpolicy

**Comment by mlottner** [comment]
@sidey79 Thanks for your patience while we researched this issue. Where a PowerShell option exists, we have made sure to mark and document it. For this policy, it needs to be created via the SCC portal. 
I'm closing this issue for now, but feel free to continue to comment here if/as needed. 
Appreciate your contribution to our docs community. 
#please-close

**Comment by sidey79** [comment]
@mlottner 

Sorry, but may we misunderstood each other.

There is a powershell comannd [set-labelPolicy](https://docs.microsoft.com/de-de/powershell/module/exchange/set-labelpolicy?view=exchange-ps) .
With this powershell, `AdvancedSettings `  can be specified, which are specified in the [docs](https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md#available-advanced-settings-for-label-policies).

There is an advanced option already available via powershell called `mandatory`.
This can be controlled via powershell. 
From my point of view, with this option "All documents and emails must have a label" can be controlled via powershell.

But i found no docs about this AdvancedSettings which is also displayed performing a get-labelPoilcy.
Can `mandatory `added to the docs to make this clearer?
