### ISSUE TITLE
Unclear formatting

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/Azure-RMSDocs#1194]
Is the section below supposed to be a bulleted list?

> Office apps minimum version 1805, build 9330.2078 from Office 365 Business or Microsoft 365 Business when the user is assigned a license for Azure Rights Management (also known as Azure Information Protection for Office 365) Office 365 ProPlus Office Professional Plus 2019 Office Professional Plus 2016 Office Professional Plus 2013 with Service Pack 1 Office Professional Plus 2010 with Service Pack 2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @dcbrown16 
Thanks for taking the time to send feedback on docs!
Yes, it looks like there's a small error here. I'll clean up this code in a coming publish.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
