### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by sqadev1** [MicrosoftDocs/Azure-RMSDocs#1196]
[Enter feedback here]

The "Webinar: Unified labeling recording, deck, and FAQs" link doesn't exist.  Please update the page with the correct information.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to unified sensitivity labels - AIP](https://docs.microsoft.com/en-gb/azure/information-protection/configure-policy-migrate-labels#clients-and-services-that-support-unified-labeling)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* Sub-service: **labelmigrate**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @sqadev1 - thanks for taking the time to send feedback on docs!

I've found these resources linked from this post: https://techcommunity.microsoft.com/t5/microsoft-security-and/moving-to-unified-labeling-webinar/ba-p/1181717 

We'll update the docs with the correct link in a coming publish.
I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
