### ISSUE TITLE
Looking for documentation and any sample on registration and revocation for doc tracking

### ISSUE THREAD

**Issue by SaurabhSharma-MSFT** [MicrosoftDocs/Azure-RMSDocs#1198]
Hi,
Is there any public documentation (developer guide) or sample using MIP SDK  available registration and revocation feature for doc tracking as mentioned in the [release notes](url).

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d514f9c7-6635-438b-6407-0acf31438934
* Version Independent ID: 16ed826c-ed50-1570-df38-792a5ae0e578
* Content: [Microsoft Information Protection (MIP) SDK version release history and support policy](https://docs.microsoft.com/en-us/information-protection/develop/version-release-history)
* Content Source: [mip/develop/version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/version-release-history.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
@SaurabhSharma-MSFT thanks for taking the time to comment on the docs!
@msmbaldwin can you take a look at this?

**Comment by SaurabhSharma-MSFT** [comment]
@msmbaldwin Any updates ?

**Comment by msmbaldwin** [comment]
Will address via email. #please-close
