### ISSUE TITLE
Office 365 ProPlus and Business Renaming

### ISSUE THREAD

**Issue by miguelvidex** [MicrosoftDocs/Azure-RMSDocs#1199]
There's several mentions to Office 365 ProPlus and Business that should be updated to Microsoft 365 Apps for Business and Enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks! Just to confirm, across the board we should rename as follows?
- Office 365 ProPlus > Microsoft 365 Apps for Business
- Office 365 Business > Microsoft 365 Apps for Enterprise

**Comment by miguelvidex** [comment]
It's the other way arround:
Office 365 ProPlus > Microsoft 365 Apps for Enterprise
Office 365 Business > Microsoft 365 Apps for Business

More info [here](https://www.microsoft.com/microsoft-365/partners/smb-sku-rename)

**Comment by batamig** [comment]
Thanks for taking the time to send us feedback on MSDocs.
We'll update this for an upcoming publish, and appreciate your contribution to our docs community!
Closing this issue for now, but feel free to continue to comment here if/as needed.

**Comment by mlottner** [comment]
#please-close
