### ISSUE TITLE
Add Microsoft Edge Chromium to list of supported PDF readers for IRM Protected PDF's.

### ISSUE THREAD

**Issue by Notorious-AFK** [MicrosoftDocs/Azure-RMSDocs#1200]
[Enter feedback here]
Microsoft Edge Chromium now supports IRM protected PDF's.
This is an excellent option for MacOS users (and other platforms!).

Please add this to the list of supported software for the relevant platforms.
I have had successful IRM tests with PDF's in "Edge Chromium" for Windows 10 Enterprise and MacOS Catalina.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to comment on docs!

We'll confirm this with the dev team and then add the change to an upcoming publish accordingly. 
I'm going to close this issue in the meantime, but feel free to continue to comment here as needed.
We appreciate your contribution to our community!

#please-close
