### ISSUE TITLE
Online Outlook does not honor app name in the If.App macro

### ISSUE THREAD

**Issue by mlemartien** [MicrosoftDocs/Azure-RMSDocs#1202]
Apparently when using those macros in the footer/header marking of a label, Outlook Online does not seem to see itself as Outlook and therefore puts the whole macro in the footer/header of the email.

So one ends up with a footer in the email that shows something like this:
${If.App.WXP}Confidential ${If.End}

Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
@mlemartien, Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs. 

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
