### ISSUE TITLE
Classify and protect existing files in bulk - Azure Cloud App Security ?

### ISSUE THREAD

**Issue by DavidTaig** [MicrosoftDocs/Azure-RMSDocs#1203]
[Enter feedback here]
https://docs.microsoft.com/en-us/azure/information-protection/deployment-roadmap#step-5-configure-labels-and-settings-applications-and-services-for-data-protection

4. Classify and protect existing files in bulk

For your on-premises data stores, now run the Azure Information Protection scanner in enforcement mode so that files are automatically labeled. For cloud-based data stores, use Azure Cloud App Security.

My understanding: You can't classify and protect **existing files in bulk** with Azure Cloud App Security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a8eb9a0-a91e-fcd7-883d-5371b8c8cfe1
* Version Independent ID: a16e9d16-0fc9-793c-820f-0cac8f7815bd
* Content: [Azure Information Protection deployment roadmap](https://docs.microsoft.com/en-us/azure/information-protection/deployment-roadmap)
* Content Source: [Azure-RMSDocs/deployment-roadmap.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deployment-roadmap.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @DavidTaig 
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I'm going to check back with the team to see how we can clarify this page.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by batamig** [comment]
Hi @DavidTaig , just getting back to you here while we update our docs.

I checked with the Cloud App Security team, and you're correct that scanning existing files in bulk isn't the most common use case for Cloud App Security, and therefore it doesn't work in exactly the same way.  
There are, however, some steps you can take to get your files scanned. They pointed me to this page for details: https://docs.microsoft.com/en-us/cloud-app-security/azip-integration. 

I hope this helps. Thanks again for sending us your question!
