### ISSUE TITLE
Query on telemetry

### ISSUE THREAD

**Issue by RevengerTT** [MicrosoftDocs/Azure-RMSDocs#1205]
* Instead of AllowTelemetry=0 to disable the install option Help improve Azure Information Protection by sending usage statistics to Microsoft, specify ENABLETELEMETRY=0.

Is this correct? should this be AllowTelemetry=1 or ENABLETELEMETRY=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @RevengerTT 
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I'm going to check back with the team about this one and update the page as needed to clarify. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
