### ISSUE TITLE
Protect/Unprotect-RMSFile not present in Azure Information Protection Unified Labeling

### ISSUE THREAD

**Issue by cotugnogi** [MicrosoftDocs/Azure-RMSDocs#1210]
[Enter feedback here]

Hi,

I've installed the latest version of AzInfoProtection_UL Version 2.7.96.0 and I've noticed that this version does not install the Powershell cmdlets **Protect-RMSFile and Unprotect-RMSFile**.

However, this cmdlets was available in the [AzInfoProtection(classic) ](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-powershell) that is no longer downloadable.

How can we use this important feature in an enterprise environment?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7383893-1714-4be5-a499-7f9463fab5e2
* Version Independent ID: f566dfdf-bbae-f671-f012-b5c71e40bf14
* Content: [Use PowerShell with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by WeiqiuLiu** [comment]
hi,

did u managed to download that? I've been in the same problem...

thanks

**Comment by cotugnogi** [comment]
Hi @WeiqiuLiu the new AIP_UL client use **Set-AIPFileLabel** cmdlet instead of the old _Protect/Unportect_-RMSFile.

Here you can find more information about:
https://docs.microsoft.com/it-it/powershell/module/azureinformationprotection/set-aipfilelabel?view=azureipps

**Comment by WeiqiuLiu** [comment]
> Hi @WeiqiuLiu the new AIP_UL client use **Set-AIPFileLabel** cmdlet instead of the old _Protect/Unportect_-RMSFile.
> 
> Here you can find more information about:
> https://docs.microsoft.com/it-it/powershell/module/azureinformationprotection/set-aipfilelabel?view=azureipps

Yes, it use the Set-AIPFileLabel comlet. But for my understanding, it only supports azure rms but not adrms template. (right?) I'm using ad rms and hoping to apply rms template to file by using powershell cmd.

**Comment by ethanchal** [comment]
Hi all, is there a suitable workaround given the removable of this cmdlet for decrypting messages stored in .pst files? Previously we would use **Unprotect-RMSFile** to do this..
