### ISSUE TITLE
The following video shows how DKE works to secure your content - this video could not found

### ISSUE THREAD

**Issue by PrasadKasireddy** [MicrosoftDocs/Azure-RMSDocs#1216]
The following video shows how DKE works to secure your content - this video could not found

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8412fc-3bea-8925-169c-24f2f85d5fb5
* Version Independent ID: 58c2c518-b291-70f0-c146-c116e8159c17
* Content: [Your Azure Information Protection tenant key](https://docs.microsoft.com/en-us/azure/information-protection/plan-implement-tenant-key)
* Content Source: [Azure-RMSDocs/plan-implement-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/plan-implement-tenant-key.md)
* Service: **information-protection**
* Sub-service: **kms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @PrasadKasireddy 
Thanks for taking the time to send us feedback on the docs! We're working on getting this link fixed and updating the page.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
