### ISSUE TITLE
The title of the page is " Microsoft Information Projection SDK" but should be "Protection"

### ISSUE THREAD

**Issue by lubartonmsft** [MicrosoftDocs/Azure-RMSDocs#1219]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bec10c4-b6c8-8579-3f4a-09db68dec1c4
* Version Independent ID: 4814fa7f-b91b-51a2-e858-1bc3a6a53153
* Content: [Overview - Microsoft Information Projection SDK.](https://docs.microsoft.com/en-us/information-protection/develop/overview)
* Content Source: [mip/develop/overview.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/overview.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @lubartonmsft , 
Thanks for taking the time to send us this feedback! We always appreciate hearing from users.

I can see that we've already fixed this, so I'll just tag @msmbaldwin as an FYI and close the issue. 
Feel free to comment here as needed.

#please-close
