### ISSUE TITLE
Some collected information is missing from the list.

### ISSUE THREAD

**Issue by joeri-juramento** [MicrosoftDocs/Azure-RMSDocs#1226]
Hello, 

Considering this paragraph: https://docs.microsoft.com/en-gb/azure/information-protection/reports-aip#information-collected-and-sent-to-microsoft which mentions 10 collected information points.

> Information collected and sent to Microsoft
> To generate these reports, endpoints send the following types of information to Microsoft:
> 
> - The label action. For example, set a label, change a label, add or remove protection, automatic and recommended labels.
>  
> - The label name before and after the label action.
> 
> - Your organization's tenant ID.
> 
> - The user ID (email address or UPN).
> 
> - The name of the user's device.
> 
> - For documents: The file path and file name of documents that are labeled.
> 
> - For emails: The email subject and email sender for emails that are labeled.
> 
> - The sensitive information types (predefined and custom) that were detected in content.
> 
> - The Azure Information Protection client version.
> 
> - The client operating system version.

I encountered the following **additional data/information points**: 

- IP Address
- Process (like 'outlook' or 'msip.app')
- Application Name (like 'Outlook' or 'File Explorer')

I found these two information points in _Azure Information Protection | Activity Logs (Preview)_ and clicking an entry. Below a screenshot of the _Activity Details_.

![image](https://user-images.githubusercontent.com/22143678/89020881-efde6d80-d31f-11ea-8c37-991a209fafbe.png)

I would add these to the list / documentation.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-gb/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@joeri-juramento Thanks for taking the time to give us your suggested docs improvements. 
We'll revise the reports page you flagged in our next update.  
Closing this issue for now, but feel free to continue to comment or question here if/as needed. 
Appreciate your contribution to our docs community!
@batamig #please-close
