### ISSUE TITLE
Azure Information Protection or Microsoft Information Protection?

### ISSUE THREAD

**Issue by jbaeza32** [MicrosoftDocs/Azure-RMSDocs#1228]
This article calls it AIP (which is a name I like better and is more aligned to the idea of Azure Security capabilities) but I've heard for a while that we are calling it "Microsoft Information Protection."

If we're moving to MIP then this article should be corrected or should at least mention that MIP is the "new" name.

Thank you!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @jbaeza32 - thanks for your question on the AIP / MIP naming! We always appreciate hearing from our users.

The Azure Information Protection solution is actually just a part of the MIP story. This area of the Microsoft docs mainly covers the AIP scanner and the classic and unified labeling clients.

For a higher-level view of Microsoft Information Protection, including many elements other than the AIP scanner and clients, see [https://aka.ms/MIPdocs](https://aka.ms/MIPdocs)  

The timing on your question is also excellent - we've just released a survey about MIP usage. We're gathering feedback to help us make the MIP user experience more intuitive. 
It should only take 5 minutes to fill out - please see [https://aka.ms/MIPC/MIPPolicySurvey](https://aka.ms/MIPC/MIPPolicySurvey).

You can also get more updates and questions in our Yammer group here: [https://www.yammer.com/askipteam](https://www.yammer.com/askipteam)

Customer feedback is critical, and we'd love to hear from you!

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
