### ISSUE TITLE
AzInfoProtection.exe is no longer available for download.

### ISSUE THREAD

**Issue by sfilinto** [MicrosoftDocs/Azure-RMSDocs#1230]
[Enter feedback here]
this page need to remove reference to AzInfoProtection.exe as it is no longer available for download.
refer to https://www.microsoft.com/en-us/download/details.aspx?id=53018
The Azure Information Protection classic client is being deprecated in March, 2021. To deploy the AIP classic client, open a support ticket to get download access.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba6f8d6-57f2-2982-fa29-ec1d2ffdf24c
* Version Independent ID: bedf8139-1a11-7996-bea0-1efb00d4a14d
* Content: [Download & install the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/install-client-app)
* Content Source: [Azure-RMSDocs/rms-client/install-client-app.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/install-client-app.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @sfilinto Thank for taking the time to send us your feedback!

You're correct - this should read **AzInfoProtection_UL.exe**, as it's only the unified labeling client that's currently available for download from this page. We'll fix this in an upcoming publish.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
