### ISSUE TITLE
role to configure in azure

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1231]
[Enter feedback here]
What admin level role is required to configure AIP in Azure, this is not stated on this page, please add

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d99ffdbf-da4e-7e91-772a-146dc9a66f4c
* Version Independent ID: 0fbe983b-7c9d-4915-1a6f-5ae12bc8799e
* Content: [Install and configure the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-configure-install)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner-configure-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner-configure-install.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @DeanGross 
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I've checked, and the list of admin roles required to configure Azure Information Protection is listed here:
[Signing in to the Azure portal](https://docs.microsoft.com/azure/information-protection/configure-policy#signing-in-to-the-azure-portal)

I've added an item to our backlog to clarify this in the requirements section as well.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close.
