### ISSUE TITLE
Access Denied running documented commands.

### ISSUE THREAD

**Issue by scyto** [MicrosoftDocs/Azure-RMSDocs#1234]
Hi,

I want to enable IRM templates on my O365 exchange instance.  I am following the instructions in this doc (wow could you have made this any more complicated!)

When i run ``` $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://ps.outlook.com/powershell/ -Credential $Cred -Authentication Basic –AllowRedirection```

I get access denied.

Yes i logged on with an account that has perms (it is a GA).  Is this possibly because I have MFA (i note i wasn't promted for my MFA, just my username and password).

Please clarify the docs if MFA is needed?

alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0f9004-6541-428f-120f-48e1cc006e4d
* Version Independent ID: bd791ddb-d4a2-8ac4-0a7a-201bdc175c94
* Content: [Configuration for Office 365 services to use Azure RMS - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-office365)
* Content Source: [Azure-RMSDocs/configure-office365.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-office365.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by cabailey** [comment]
@scyto f you have MFA, use these instructions to connect to the service, then you can jump to step 4: https://docs.microsoft.com/en-us/powershell/exchange/connect-to-scc-powershell?view=exchange-ps 

Yes, it was complicated - much better now Azure RMS is enabled by default for new tenants, and enabled for most existing tenants.

**Comment by mlottner** [comment]
@scyto Thanks again for taking the time to give us your docs feedback. 
I'm closing this issue for now, but feel free to continue to comment or ask questions here if/as needed. 
Appreciate your contribution to our community! 
#please-close
