### ISSUE TITLE
PDF file extension

### ISSUE THREAD

**Issue by anpiskai** [MicrosoftDocs/Azure-RMSDocs#1238]
Hi,
For extra clarity, can the .pdf file type be added to the list detailing the file extension changes (or lack thereof) that occur when they are protected? It appears to stay as a pdf, but is missing from the chart. The chart mentions that any generic file (like the ones not listed) would be .pfile's but if .pdf stays the same, it wouldn't fall into that category

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044457bf-06a4-cc9e-3425-780a748c50ed
* Version Independent ID: 4e587393-64eb-4cd7-f2a6-e0e22e22a8bd
* Content: [File types supported - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#supported-file-types-for-classification-and-protection)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by mlottner** [comment]
@anpiskai Thanks so much for taking the time to give us your docs improvement suggestion. 
We'll work to add clarity around pdf protection explanations on the page you tagged in our next update. 
Closing this issue for now, but feel free to continue to comment or question here as needed. 
Appreciate your contribution to the community. 
@batamig #please-close
