### ISSUE TITLE
Link to download scanner 

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1240]
[Enter feedback here]
It would be helpful if this page contained a link to the actual location for downloading the scanner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e1c46-7da6-6abd-cf7e-508932b7f217
* Version Independent ID: c5d25e69-4b80-a517-e0b0-79e79a5a9dc1
* Content: [Azure Information Protection client admin guide](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide#upgrading-the-azure-information-protection-scanner)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your feedback! We really appreciate getting customer input on docs.

The scanner installation files come as part of the Azure Information Protection client.

You've commented on the page for the _classic_ client and scanner, which is being deprecated in March, 2021. If you need to deploy a classic client upgrade, please open a support ticket to get download access.

If you would like to upgrade your unified labeling scanner and client, you can access the latest version from the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=53018).

We'll plan an update to this page to clarify this issue, for both the classic and unified labeling clients and scanners.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by DeanGross** [comment]
Thanks, the fact that the scanner comes with the client has always been confusing to me and my clients. I know that it mentioned somewhere, but this is not really emphasized throughout the documentation so anything that can be done to make this more clear would be apprecizated.

**Comment by batamig** [comment]
@DeanGross thank you very much for taking the time to send us that feedback!
