### ISSUE TITLE
Hyperlink broken

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#1241]
Hello,
Please update hyperlink for:

If you use Intune for your software deployment method, use these instructions together with _Add apps with Microsoft Intune._

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for the heads up on this! We appreciate you taking the time to send this to us.
We'll have this fixed in a coming update. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
