### ISSUE TITLE
Can Rights Management Prevent Screen Sharing

### ISSUE THREAD

**Issue by BrianMcNeese** [MicrosoftDocs/Azure-RMSDocs#1242]
Consider adding documentation about screen sharing with Microsoft Teams, Skype for Business, and other screen sharing applications. This is especially important given the remote world we are in now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e0ca219-540d-2816-3f51-d02f3f3667e0
* Version Independent ID: 44a2f2ce-c32f-9870-863e-5635f7e2b22d
* Content: [FAQs for Azure RMS - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-rms#can-rights-management-prevent-screen-captures)
* Content Source: [Azure-RMSDocs/faqs-rms.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-rms.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Thanks for commenting @BrianMcNeese ! 
You can find some details about screensharing for protected PDFs on this topic:

> **[Which PDF readers are supported for protected PDFs?](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers):**
> 
> Encrypting your PDFs with Azure Information Protection (AIP) ensures that unauthorized people cannot read the file's content, and that even authorized people cannot share screens or screenshots that display the content.

I'm going to check back with the team to see what we can add and clarify about other file types.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
