### ISSUE TITLE
${User.Name} documentation is causing confusion and implementation mistakes.

### ISSUE THREAD

**Issue by get2tom** [MicrosoftDocs/Azure-RMSDocs#1245]
This feedback is specifically about the document item "${User.Name} for the owner of the document or email, by the Windows signed in user name. For example: rsimone".  It has come to my attention that the values provided for ${User.Name} are intended to be the "Display Name" of the user.  However, the example given is just the first part of the user's email address (the part before the at sign @).  Which could occasionally be the user's Display Name, but even then this example is confusing and ambiguous.  Readers may very well (incorrectly) conclude that ${User.Name} is supposed to be the first part of the email address.  Please make the documentation clearer.  Consider stating outright that the ${User.Name} is intended to produce the "Display Name" for the user's email identity.  And consider giving an example which looks like a real display name (perhaps "Dr. Rosalind Simone"), and which is not confusable for the first part of the user's email address.  Many Thanks!   

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings#using-variables-in-the-text-string)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @get2tom , thanks very much for your feedback! Customer input is really valuable to our docs.

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
