### ISSUE TITLE
Is there any API call to add an MIP label to an existing file? Can it be modified only from the UI?

### ISSUE THREAD

**Issue by toshetah** [MicrosoftDocs/Azure-RMSDocs#1246]

**Comment by KhurramShehzadd** [comment]
I also need help with this one, i have the same scenario where i need to modify original file to apply label on it.

**Comment by tommoser** [comment]
MIP SDK is unable to label files in place as our parsing library isn't capable of read/write. We read the source file, write the changes to a new file, then recommend that you replace the unlabeled file with the labeled file. In some cases, you may need to preserve timestamps or other metadata in your own app code.

**Comment by batamig** [comment]
Hi @toshetah - thanks for taking the time to send us your question! 

I see that @tommoser 's already replied, so I'm going to close this. Feel free to continue to comment here as needed.

#please-close
