### ISSUE TITLE
Unable to process .msg files for applying sensitivity labels

### ISSUE THREAD

**Issue by KhurramShehzadd** [MicrosoftDocs/Azure-RMSDocs#1247]
MIP Sdk, APIs are working good for applying labels on word, excel and power-point. But when it comes to email files (.msg), It's not able to process them. Can you please advise on this ?

**Comment by batamig** [comment]
Hi @KhurramShehzadd - thanks for taking the time to send us your question! 
@msmbaldwin can you take a look at this?

**Comment by msmbaldwin** [comment]
Hi, @KhurramShehzadd. Labeling of .msg files is not yet supported. We hope to provide this functionality soon. Thank you. #please-close
