### ISSUE TITLE
AIP Viewer on unmanaged devices with App protection policies

### ISSUE THREAD

**Issue by win2000b** [MicrosoftDocs/Azure-RMSDocs#1250]
Hi, we have app protection policies in place for all microsoft ios apps, with copy and paste and opening allowed ONLY between managed apps.  However, since you never log into the AIP viewer app until you first open a document in it. You cant use it with other managed apps. The open with "AIP Viewer" app for PDF's is not available as its not managed. How do we overcome this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1562feec-bf8f-9e84-b642-bcd259c8a418
* Version Independent ID: 953ab73d-8ee8-b63e-a7d4-52aaa60026f8
* Content: [Azure Information Protection apps for iOS & Android](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/mobile-app-faq)
* Content Source: [Azure-RMSDocs/rms-client/mobile-app-faq.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/mobile-app-faq.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.
I'm going to check back with the team about this one and update this page to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
