### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by razvan-b** [MicrosoftDocs/Azure-RMSDocs#1253]
In the article we have : 

"4. Stop and start IIS to activate tracing.

5. When you have captured the traces that you need, revert the line in step 3, and stop and start IIS again. "

but there is no mention of where we can find the logs. I have looked in the folders where the connector is installed and i could not find anything. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42532a53-5da7-3ffd-7db5-f0cba455be5b
* Version Independent ID: 8d7d2007-ff66-a5d6-2390-ca96e110a9b9
* Content: [Monitor the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/monitor-rms-connector)
* Content Source: [Azure-RMSDocs/monitor-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/monitor-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.
I'm going to check back with the team about this one and then update this page to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
