### ISSUE TITLE
RunPolicyInBackground description unclear

### ISSUE THREAD

**Issue by andrePKI** [MicrosoftDocs/Azure-RMSDocs#1254]
The sentence is unclear
"this behavior enables automatic and recommended classification and protection for documents that are stored in SharePoint"
Does this behaviour apply to any Word/Excel/PowerPoint that is being edited, or only for documents stored in SharePoint?
If SharePoint, does that include Onedrive and Teams as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#how-to-configure-advanced-settings-for-the-client-by-using-office-365-security--compliance-center-powershell)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.
I'm going to check back with the team to clarify before I update this item. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
