### ISSUE TITLE
Variables in visual markings in Office Online

### ISSUE THREAD

**Issue by Appie1701** [MicrosoftDocs/Azure-RMSDocs#1258]
Variables (for example **${If.App.PowerPoint}This presentation is confidential. ${If.End}**) work in both clients. However, if a document is labeled (using a label with this configuration) in Office Online, the plain-text variable is shown. Only when the document is opened in the Office App will this be replaced by the correct marking. This only goes for the variables. Other markings work perfectly.

Can you please add this to the documentation?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings#using-variables-in-the-text-string)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Appie1701 - thanks for sending us your feedback! 

I'm going to check back with the team before adding this in to the docs, and will update the docs as needed in a coming publish.

We always appreciate customer input! 
I'm closing this in the meantime, but feel free to continue to comment here as needed.

#please-close
