### ISSUE TITLE
Does office online server support mip?

### ISSUE THREAD

**Issue by nvliumang** [MicrosoftDocs/Azure-RMSDocs#1262]
Hello !

I am reading this doc: https://docs.microsoft.com/en-us/office/troubleshoot/administration/office-online-limitations-and-features-with-information-rights-management

And I see : ' 'Protected documents where the IRM or Azure Information Policy protection is applied from Office applications are not supported by Office Online and Microsoft Offices Online.' and only share point document libaries with IRM is supported by office online.' 

If the above statement still holds true, could you please help below question?

- Will there be any future support in Microsoft office Online Servers for the protected files using Microsoft Information Protection(MIP SDK)?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bec10c4-b6c8-8579-3f4a-09db68dec1c4
* Version Independent ID: 4814fa7f-b91b-51a2-e858-1bc3a6a53153
* Content: [Overview - Microsoft Information Protection SDK.](https://docs.microsoft.com/en-us/information-protection/develop/overview)
* Content Source: [mip/develop/overview.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/overview.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @nvliumang thanks for your question on docs!

I'm tagging the authors of these two pages to comment here, @msmbaldwin and @danocoyote can you take a look?

**Comment by batamig** [comment]
@tommoser - can you also take a look at this one?

**Comment by renatoromao** [comment]
Hi,

I'm trying to apply this documentation [here](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp) to read SharePoint Online file but I'm getting an issue like "Failed to open file".
I think that is the same thread here.

Do you know anything about it?

**Comment by tommoser** [comment]
@nvliumang  there are no plans today to support MIP protected docs in OOS. 

@renatoromao That sounds like a different issue. If you use something like Graph to read the full file bytes from SharePoint Online, you should be able to read the label from MIP SDK.

**Comment by renatoromao** [comment]
Hi @tommoser ,

Thanks for helping us! :)
I fixed it on my side using a C# project that I converted to a PowerShell script.

**Comment by batamig** [comment]
Thanks all! I'm closing this issue for now, but feel free to continue commenting as needed.
#please-close
