### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by hittensa** [MicrosoftDocs/Azure-RMSDocs#1263]
The documentation states that the following settings are supported within the Azure Information Protection Built-In Labels client:

User-defined permissions for a label:- Do Not Forward for emails
User-defined permissions for a label:- Custom permissions for Word, Excel, PowerPoint

This is incorrect, the moment you enable Encryption on the Sensitivity Label it is not visible in the Built-In client.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#choose-which-labeling-client-to-use-for-windows-computers)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for your comment on docs, @hittensa! We always appreciate hearing from our users.
I'm going to check back with our team to verify the change, and then update the docs as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by batamig** [comment]
HI @hittensa , getting back to you on your issue.
For information about built-in labeling support, see here:  https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#support-for-sensitivity-label-capabilities-in-apps

If you're having an issue where the sensitivity label isn't visible in the built-in client after enabling encryption on the label, we recommend that you contact support.

Thanks!
