### ISSUE TITLE
Ignite links don't work

### ISSUE THREAD

**Issue by scruffty** [MicrosoftDocs/Azure-RMSDocs#1274]
All of the ignite links are broken 👎 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection#microsoft-ignite)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @scruffty , thanks for your comment on our docs! 
Updated information for our recent Ignite 2020 should be up on this page soon.

In the meantime, you can find links to Ignite 2020 sessions here: https://myignite.microsoft.com/home

I'm closing this for now, but feel free to continue to comment here as needed.
#please-close
