### ISSUE TITLE
"Open In" inaccuracies

### ISSUE THREAD

**Issue by RonPattersonBadger** [MicrosoftDocs/Azure-RMSDocs#1275]
The site states:
"View protected files on your device
1. Once you've installed the AIP mobile app, open a protected email or file.

2. When prompted to select an app, select the AIP Viewer:"

On IOS (I've tried two different devices running IOS 13.6.1 and IOS 12.4.8) you do not get an "Open In/Open With" option when attempting to open a protected PDF file using Outlook or the intrinsic Mail client.  Instead you get a page headed with Microsoft Azure Information Protection and drives you to "Open in the app" where you select apple and it drives you to https://go.microsoft.com/fwlink/?linkid=836828 where it instructs you to install the Azure Information Protection viewer for IOS (which is already installed).  This is completely unhelpful and cyclical.

Instead, to successfully open the document you have to press the Share button in the upper right of the window, select "Share File via..". and select "Copy to AIP Viewer"

![1](https://user-images.githubusercontent.com/53090783/96034222-6f0f1800-0e1e-11eb-8df9-7e075a5b64f9.png)
![2](https://user-images.githubusercontent.com/53090783/96034235-72a29f00-0e1e-11eb-9955-03e1a1733ff4.PNG)
![3](https://user-images.githubusercontent.com/53090783/96034239-7504f900-0e1e-11eb-8cbe-79f541047714.png)
![4](https://user-images.githubusercontent.com/53090783/96034246-77ffe980-0e1e-11eb-84d8-385e59a30cf4.png)
![5](https://user-images.githubusercontent.com/53090783/96034256-7a624380-0e1e-11eb-9387-1fca802b14dc.PNG)

It's like AIP Viewer doesn't register to be able to open .pdf files (and related extensions), which would seem to be a design flaw.  Regardless, the provided documentation doesn't appear to be accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1562feec-bf8f-9e84-b642-bcd259c8a418
* Version Independent ID: 953ab73d-8ee8-b63e-a7d4-52aaa60026f8
* Content: [Azure Information Protection apps for iOS & Android](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/mobile-app-faq)
* Content Source: [Azure-RMSDocs/rms-client/mobile-app-faq.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/mobile-app-faq.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @RonPattersonBadger , thanks for taking the time to send your feedback on our docs!
I've taken this back to the team, and have added the relevant instructions to this page.
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/mobile-app-faq#ios-view-protected-files-on-your-device 
I'm closing this -  feel free to continue to comment here as needed.
#please-close
