### ISSUE TITLE
Using sensitivity label name as a field in the dcument

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/Azure-RMSDocs#1276]
We figured out how to do this https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#can-i-create-a-document-template-that-automatically-includes-the-classification with the unified labelling client. However, it doesn't appear to update if the label is changed. Is that expected behavior or a limitation of MS Word?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb834-9023-f79b-115e-199c4e1af17b
* Version Independent ID: a0ea852a-eedd-b205-91c0-bfa8732fa9f3
* Content: [FAQs for classification & labeling - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#can-i-create-a-document-template-that-automatically-includes-the-classification)
* Content Source: [Azure-RMSDocs/faqs-infoprotect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-infoprotect.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by SLeuthold** [comment]
Correction, it appears with the unified labelling client the document property isn't consistently named.

**Comment by batamig** [comment]
Hi @SLeuthold thanks for taking the time to send your question to the docs team!

It's unclear to me if there's still a docs issue here, or if you've solved it? In either case, I'd be glad to hear more details in case there's something we can clarify for future users.

**Comment by batamig** [comment]
Hi @SLeuthold , this item has been open a while without clarification. 

I'm not sure if there's a docs issue here or something that's related to an MS Word issue?

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by SLeuthold** [comment]
This is still a docs issue.

**Comment by batamig** [comment]
Thanks @SLeuthold . I'll raise it with the team and see if we can clarify - I've added it to our backlog.
In the meantime, you can also open a support ticket or ask our team on Yammer: https://www.yammer.com/askipteam/
