### ISSUE TITLE
Web Proxy Information for AIP Client

### ISSUE THREAD

**Issue by GuyPartridge** [MicrosoftDocs/Azure-RMSDocs#1277]
Hi,
It states in the doc for the AIP Client fixed issues for 2.8.85.0
Added support for Proxy.pac files when using a proxy to acquire a token. To enable this fix, set the new registry key UseDefaultCredentialsInProxy = 1.
Where exactly is this key set or created and do you have any further information on this?
Thanks,
Guy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection unified labeling client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
HI @GuyPartridge 
Thanks for taking the time to send us your question! We always appreciate getting customer feedback on docs.

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by Rkhan-ms** [comment]
Hi, I found the follwing registry key from an internal source. 

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\MSIP\UseDefaultCredentialsInProxy, and set the value to 1

**Comment by batamig** [comment]
Thanks @Rkhan-ms ! Yep, we're in the process of making the doc update.
