### ISSUE TITLE
You say that Adobe Reader is a supported PDF reader software, but there is a big issue with that product

### ISSUE THREAD

**Issue by pavelrozenberg** [MicrosoftDocs/Azure-RMSDocs#1278]
When protecting a document using AIP that has a restriction on content extraction (i.e. screenshot/screen sharing) the Adobe Reader doesn't protect.
The only way the document can be viewed protected is using the AIP Viewer.
This causes a lot of confusion as many companies usually only use Adobe Reader and are faced with many legal issues when they find out themselves that Adobe Reader causes this issue, although it is stated here that it is supported (seems to be not supported after all).
Please adjust the documentation to include this known issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by pavelrozenberg** [comment]
Hi,
Thank you for getting back on this, but why did you close this issue?
The Adobe Reader is still there, their plug-in is not updated yet to support the feature I wrote about. I had a case opened with Microsoft support since more than a month where eventually they told me to write here about this issue.
Microsoft case number: 120082425003052

This is a real issue and this docs page is confusing everyone into believing that Adobe Reader is the best option there is.
You should have a section for partially-supported PDF readers explaining what exactly is not working there well.

**Comment by batamig** [comment]
Hi @pavelrozenberg, we generally close the issues here when we've open up a backlog item and it's in process with the team to understand exactly how the content should get updated. We're currently discussing the fix needed based on your feedback.
