### ISSUE TITLE
a little spellcheck needed :)

### ISSUE THREAD

**Issue by DonPick** [MicrosoftDocs/Azure-RMSDocs#1279]
found "customziation" and "justifcaiton" in this doc  :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#customize-justification-prompt-texts-for-modified-labels)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @DonPick! Thanks for taking the time to send us your feedback. 
We'll get this update fixed, and appreciate you letting us know.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
