### ISSUE TITLE
Tenant GUID?

### ISSUE THREAD

**Issue by adamtoth** [MicrosoftDocs/Azure-RMSDocs#1281]
There is no Tenant GUID in the sample code, but at the bottom of the article it mentions replacing the Tenant GUID. Also there is a missing comma for the line:

            var engineSettings = new FileEngineSettings("adam@iffpppoc.onmicrosoft.com.com",authDelegate "", "en-US");
Right after authDelegate
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0261682a-a7cb-7362-4386-4fc77975ebf6
* Version Independent ID: 4ddc7104-90e0-1468-22b9-9b96344aa205
* Content: [Quickstart - Initialization for Microsoft Information Protection (MIP) SDK C# clients](https://docs.microsoft.com/en-us/information-protection/develop/quick-app-initialization-csharp)
* Content Source: [mip/develop/quick-app-initialization-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-app-initialization-csharp.md)
* Service: **information-protection**
* GitHub Login: @tommoser
* Microsoft Alias: **tommos**

**Comment by batamig** [comment]
@tommoser can you take a look at this one?

**Comment by tommoser** [comment]
Just created a PR for this fix.

**Comment by batamig** [comment]
Hi @adamtoth - thanks for taking the time to send us your question!

I see that @tommoser 's already replied, so I'm going to close this. Feel free to continue to comment here as needed.

#please-close
