### ISSUE TITLE
Something missing on step 24?

### ISSUE THREAD

**Issue by JonesMikael** [MicrosoftDocs/Azure-RMSDocs#1285]
The followin step says::
24. Still on the AIPClient pane, from the Manage menu, select Authentication.

But after that, there is no action. Step 25 just tells us to go to Manage > API permissions.

Is there something missing on step 24 or just a typo?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9edb2c-4c7e-f9f5-a7fc-74c475dd083e
* Version Independent ID: 27d918c1-55e4-024b-35e6-2a9621b95cd7
* Content: [Use PowerShell with the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-powershell#how-to-label-files-non-interactively-for-azure-information-protection)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
