### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by jonathanmurch** [MicrosoftDocs/Azure-RMSDocs#1286]
Spelling mistake, on-premises director should probably be directory 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your feedback! We always appreciate proof that users are reading our docs carefully.
We'll get a fix up for this in a coming update.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
