### ISSUE TITLE
@ThomasKur Thanks so much for taking the time to submit your improvement suggestion to docs.

### ISSUE THREAD

**Issue by DonPick** [MicrosoftDocs/Azure-RMSDocs#1287]
@ThomasKur Thanks so much for taking the time to submit your improvement suggestion to docs. 
I've added the name as your suggested. Closing this issue for now, but feel free to continue to comment/question here if/as needed. Appreciate your contribution to our docs community!
#please-close

_Originally posted by @mlottner in https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/1125#issuecomment-684507278_

**Comment by DonPick** [comment]
This issue/correction hasn't been published, or maybe has been reverted?
The ProgID of: MSIP.OutlookAddin, has not been added to the docs page, so the original issue reported by @ThomasKur isn't resolved.

**Comment by batamig** [comment]
Hi @DonPick , thanks for taking the time to send us your question. We always appreciate customer interaction with our docs.

As you know, the current docs say to use the group policy setting for Outlook instead of the ProgID. However, I'll take this back to the team to understand how best to clarify or update this topic.

Please feel free to comment further here if needed!

**Comment by DonPick** [comment]
Hi @batamig , thanks, the docs refer to the GPO and to use the GPO requires that you know/identify the specific ProgID for the specific add-in. The docs did not list the ProgID for the Outlook add-in, but docs did list the ProgIDs for Word/Excel/PowerPoint. The omission of the ProgID for the Outlook add-in, was noted (#1125 ) as being revised to include that missing item, but that revision was not visible publicly? 
I can now see that revision, and can see that the missing ProgID is now present.
(also the link to https://docs.microsoft.com/en-us/office/vba/outlook/Concepts/Getting-Started/support-for-keeping-add-ins-enabled has been removed, but ok I guess? :)

**Comment by batamig** [comment]
Hi @DonPick , yes - that was the change we'd gotten from the dev team, and got approval on it just yesterday. thanks again for your feedback on docs!
