### ISSUE TITLE
Supported scenarios for opening protected documents

### ISSUE THREAD

**Issue by BLTTEST** [MicrosoftDocs/Azure-RMSDocs#1291]
Hi Teams,

The "Supported scenarios for opening protected documents" section in this article seems have a conflict with another article.

https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-office-apps?view=o365-worldwide#sharing-encrypted-documents-with-external-users

This article says some Android versions have been supported.

Besides, I also test and find that external users can use Office 2019 proplus to authenticate Microsoft accounts and then open AIP-protected documents. Can you kindly confirm if only Microsoft 365 Apps can authenticate Microsoft accounts when it comes to Windows? 

Please let me know if I misunderstood anything. I'll appreciate if you can share any information.

Best Regards,
Ben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9532c6a-66f7-963b-5ea6-e52e0e92b788
* Version Independent ID: 982f65e1-89a2-4f3e-1057-38e92d27b58b
* Content: [Configuring secure document collaboration with Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/secure-collaboration-documents#opening-and-editing-the-protected-document)
* Content Source: [Azure-RMSDocs/secure-collaboration-documents.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/secure-collaboration-documents.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @BLTTEST 
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

At first glance, without going into details about the support provided, you're looking at two different docs pages that apply to different Azure Information Protection clients.

- **Configuring secure document collaboration with Azure Information Protection** in the AIP docs refers to the AIP classic client, where labels and label policies are configured in the Azure portal. This client is planned for deprecation in March 2021. 

- **Sharing encrypted documents with external users** in the Microsoft 365 docs refers to the AIP unified labeling client, which uses sensitivity labels that are configured in a labeling admin center, such as the Microsoft 365 Security and Compliance Center. 
Sensitivity labels are only relevant to the unified labeling client.

The classic and unified labeling clients do differ in their support. Does this help clarify the differences between the two docs pages?

**Comment by BLTTEST** [comment]
Hi @batamig 

Thank you for your reply and I find it's true. No further questions and please close this issue.

Best Regards,

**Comment by batamig** [comment]
Great! I'm glad to know this is resolved.
I'm closing this issue, but feel free to comment further here as needed.

#please-close
