### ISSUE TITLE
File Types That Are Excluded From Classification and Protection Incorrect

### ISSUE THREAD

**Issue by chschul-sie** [MicrosoftDocs/Azure-RMSDocs#1293]
The following lists exclusions of file types not supported for classification and protection.

https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#file-types-that-are-excluded-from-classification-and-protection

But, based on our own tests ".pst" file extension is still working in default configuration. Either documentation is wrong, of it is a bug in the AIP client.

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! We really appreciate getting customer feedback on docs.

I'm going to check back with the team about this one and update this page as needed to clarify.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
