### ISSUE TITLE
Change Latest Labeling update info

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1295]
[Enter feedback here]

Please create a separate what's new page that we can read. Many of the other apps/services do this and it is very helpful. Having a subsection buried on the middle of a page is hard to find. 
Videos are great for demos, but reading the description of the new features is much faster. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @DeanGross  - thanks for taking the time to send us your feedback!
We actually have this in our short list of to-do items, and plan on moving this article to the Overview section where it'll be more visible. Please check back soon and send any other input you may have. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
