### ISSUE TITLE
Unable to open encrypted email in gmail or yahoo when sent from Outlook Desktop Client

### ISSUE THREAD

**Issue by git4life1864** [MicrosoftDocs/Azure-RMSDocs#1296]
Hi,

Have setup AIP and it works when I send an encrypted email from OWA to Gmail or Yahoo account, I get prompted to read email, when I click to read email, directs me to "Sing in with Google" and "Sign in with a One-time passcode" page. Works beautiful.

When I send a similar encrypted email (no attachment) from Outlook Desktop Client to Gmail or Yahoo account.  I do not get any of the options above.  I get the message is protected verbiage.

*****
This message is protected with Microsoft Information Protection. You can open it using Microsoft Outlook, which is available for iOS, Android, Windows, and Mac OS. Get Outlook for your device here: https://aka.ms/protectedmessage.

Microsoft Information Protection allows you to ensure your emails can't be copied or forwarded without your permission. Learn more at https://microsoft.com/rms.

*****

MS states this should work however it does not appear to work.  Has anyone gotten this to work, again from Outlook Desktop Client to Gmail or Yahoo?  I have no issues when sending from OWA to Gmail.

Any input would help.  I have reached out to MS support but they keep having me test and same results - does not work.  Can anyone verify they can send an encrypted email from their corporate Outlook Desktop Client to a Gmail or Yahoo account and have it work.

Thanks,
Izzy

**Comment by batamig** [comment]
Thanks for sending us your question! We always appreciate interaction with our users. 

Have you posted about this issue on our yammer group? See https://www.yammer.com/askipteam/ - you've got a broader user community there, as well as knowledgeable members from the team.

I'm closing this issue for now, but please feel free to continue to comment here as needed, and tag me if there's a specific doc update required. (If there is, I'll probably hear about it from the team too..)

#please-close
