### ISSUE TITLE
Circular link

### ISSUE THREAD

**Issue by fvhemert** [MicrosoftDocs/Azure-RMSDocs#1297]
Hi,

The link "Deploying the Azure Information Protection scanner to automatically classify and protect files." on this page circles back to the same page, the original page with additional information seems to have disappeared.

Need more details, feel free to reach out to me: franvanh@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d99ffdbf-da4e-7e91-772a-146dc9a66f4c
* Version Independent ID: 0fbe983b-7c9d-4915-1a6f-5ae12bc8799e
* Content: [Install and configure the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-configure-install)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner-configure-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner-configure-install.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @fvhemert, thanks for sending us your question on docs.
Could you please clarify a little bit more? The link you're referring to seems to go to the scanner overview page, as intended:
https://docs.microsoft.com/azure/information-protection/deploy-aip-scanner 
Which additional information are you looking for?

**Comment by batamig** [comment]
Hi @fvhemert, I haven't heard back from you, so I'm closing this issue for now. 

Feel free to continue to comment here as needed and tag me if you still have a question.
#please-close
