### ISSUE TITLE
Visual markings variable not honoured in web version of Office apps

### ISSUE THREAD

**Issue by martinyy108** [MicrosoftDocs/Azure-RMSDocs#1300]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @martinyy108 - thanks for sending us your comment on docs!

This page is relevant for usage with the AIP classic client only. Are you using the classic client or the unified labeling client?

The unified labeling client is our more recent, and more popular client, and it uses sensitivity labels that are configured in Microsoft 365. If you're using the unified labeling client, note that dynamic markings with variables is currently under review for Web.

For more information, see https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels-office-apps

If you're working with the classic client, please advise. In that case, I'll check back with team to understand if we need a clarification on this page.

**Comment by batamig** [comment]
Hi @martinyy108 , I haven't heard any reply from you, so I'm closing this item in the meantime. 
Feel free to comment further as needed.

#please-close
