### ISSUE TITLE
AIP Scanner discovery of sensitive information in SharePoint 2010 document name or metadata

### ISSUE THREAD

**Issue by aadappfactory** [MicrosoftDocs/Azure-RMSDocs#1301]
I know this can be done in MCAS but can the AIP scanner discovery sensitive information in a SharePoint 2010 document name of metadata? I cannot find any clear documentation.

**Comment by batamig** [comment]
Hi @aadappfactory ,
Are you asking specifically about SharePoint 2010, or about document names?
SharePoint 2010 itself is now only in extended support.

If you want more details about support for document name metadata, I'll check back with the team to see if we can clarify anything further. 
I also recommend posting a question to our Yammer group: https://www.yammer.com/askipteam

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by batamig** [comment]
Hi @aadappfactory  - a quick update from our PM team:
Currently, the scanner doesn't include metadata inspection as part of the content inspection. However - this is a great idea and they're adding it to the backlog.

Hope that helps!
