### ISSUE TITLE
Wrong description of OutlookBlockTrustedDomains

### ISSUE THREAD

**Issue by Torbjorn-S** [MicrosoftDocs/Azure-RMSDocs#1302]
Hi.

The section that covers information about OutlookBlockTrustedDomains states the direct opposite of how it works. 
In the example text, @gmail.com is added as a domain, but the text describes that this will BLOCK sending certain labeled documents to @gmail.com if the label is listed in the setting OutlookBlockUntrustedCollaborationLabel.

Now, this is not correct since what you do by adding the domain in OutlookBlockTrustedDomains is to whitelist it from the behavior that otherwise comes with OutlookBlockUntrustedCollaborationLabel 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#implement-pop-up-messages-in-outlook-that-warn-justify-or-block-emails-being-sent)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Torbjorn-S , thanks for taking the time for sending us this issue! We really appreciate customer input on our docs, and we've updated the page to clarify.

I'm closing this now, but feel free to continue to comment here as needed.
#please-close
