### ISSUE TITLE
Exchange 2010 is no longer supported.

### ISSUE THREAD

**Issue by daarroy** [MicrosoftDocs/Azure-RMSDocs#1303]
Can you please update the documentation for RMS connector. Exchange 2010 is out of mainstream support since October 13, 2020 and having Exchange 2010 in the list of supported versions to use RMS connector has caused confusion to customers.

"To use the RMS connector, these servers running Exchange must be running one of the following software versions:

Exchange Server 2010 with Exchange 2010 Service Pack 3 Rollup Update 6"

Thanks,
Daniel
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3136d8f7-5265-0a0c-e930-f56440bdb74f
* Version Independent ID: 307547d7-a7b8-99ae-6186-e105ab01c9ad
* Content: [Configure servers for the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-servers-rms-connector#configuring-an-exchange-server-to-use-the-connector)
* Content Source: [Azure-RMSDocs/configure-servers-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-servers-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @daarroy, 
This fix is planned for an upcoming update.  Thanks for raising the issue! We really appreciate customer input on docs.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
