### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by GalaxyLithium** [MicrosoftDocs/Azure-RMSDocs#1304]
Page not Found
https://www.microsoft.com/en-au/microsoft-365/blog/2012/11/09/whats-new-with-information-rights-management-in-sharepoint-and-sharepoint-online/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e647478-e7b5-549a-040d-11c34e2fc2a8
* Version Independent ID: 9660a681-a663-2f60-4148-beac607d2f34
* Content: [How Office apps & services support Azure RMS from AIP](https://docs.microsoft.com/en-us/azure/information-protection/office-apps-services-support)
* Content Source: [Azure-RMSDocs/office-apps-services-support.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/office-apps-services-support.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @GalaxyLithium - thanks for this! We'll get this page updated in a coming fix.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
