### ISSUE TITLE
Inquiry about RMS Client (MSIPC)

### ISSUE THREAD

**Issue by ahm3dhany** [MicrosoftDocs/Azure-RMSDocs#1306]
I noticed that the MSIPC (i.e. the RMS Client) is already included in all Windows 10 PCs I checked on some environment. Also I know -and correct me if I was wrong- that [Microsoft Office already uses RMS SDK natively ](https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/migration-from-ad-rms-to-azure-rms)(i.e. the SDK is shipped with the product during development).
I noticed that upon configuring AD RMS on-premise servers, the RMS protection functionality (i.e. File>Info>Protect>Restrict Access) can be used without any additional configuration on client machines (domain-joined).

My question here is, on a clean image of Windows10 without any additional installed software other than Microsoft Office (2013 or later), the user can use the RMS functionality without installing any RMS Client (e.g. RMS Client, Classic, Unified, .. etc.) given that the office already includes the RMS SDK natively?

Also, in case of migrating to Azure RMS (Cloud), the RMS SDK that is already included within Microsoft Office can interact with Azure RMS (i.e. the minimal interaction via retrieving the RMS templates) without the need to install any newer agent?

**Comment by batamig** [comment]
Hi @ahm3dhany - thanks for your question! 

I'd like to clarify this in the docs but need to take it back to the team first to verify. 

I suggest that you post your question on our Yammer group, which hosts active conversations with subject matter experts across AIP features, and should be able to get you a quicker answer. See here: https://www.yammer.com/askipteam/

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
