### ISSUE TITLE
Bad markdown link on documentation

### ISSUE THREAD

**Issue by nicolaslareu** [MicrosoftDocs/Azure-RMSDocs#1307]
[Enter feedback here]
There is a markdown link to another documentation page which is showing the current link. It is the link with the legend "Azure Information Protection unified labeling client administrator guide".

![image](https://user-images.githubusercontent.com/50845301/100932536-c77f9f00-34ca-11eb-996d-e2db1ddb7551.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c744cf2-5e29-11c4-8e30-9af0adfaa8da
* Version Independent ID: 708c51d5-946a-c162-fcdc-7a4e309ba855
* Content: [Azure Information Protection client - Install & configure](https://docs.microsoft.com/en-us/azure/information-protection/configure-client)
* Content Source: [Azure-RMSDocs/configure-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-client.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @nicolaslareu - thanks for taking the time to send this to us! We'll get this fixed in an upcoming update. 

I'm closing this in the meantime, but please feel free to continue to comment here as needed.
#please-close
