### ISSUE TITLE
Windows Server 2019 FCI supported by RMS Connector

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Azure-RMSDocs#1309]
[Enter feedback here]
For scenarios using RMS connectors, the Information Protection support team has determined that Windows Server 2019 FCI is also sapportable (Steve.Light@microsoft.com confirmed to).
I want you to modify "Windows Server 2019" to the OS list in the "Configuring a file server for File Classification Infrastructure to use the connector" section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3136d8f7-5265-0a0c-e930-f56440bdb74f
* Version Independent ID: 307547d7-a7b8-99ae-6186-e105ab01c9ad
* Content: [Configure servers for the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-servers-rms-connector#configuring-a-file-server-for-file-classification-infrastructure-to-use-the-connector)
* Content Source: [Azure-RMSDocs/configure-servers-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-servers-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi juhirao, thanks for taking the time to send us this update! 
We'll put it through the approval cycle and update the docs in an upcoming push.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
