### ISSUE TITLE
Syntax errors in the document

### ISSUE THREAD

**Issue by peterjoinobits** [MicrosoftDocs/Azure-RMSDocs#1311]
[Enter feedback here]
The examples presented in the document don't gel with each other.

As an example check the following paragraphs:

Set footer text for Word, Excel, and Outlook, and different footer text for PowerPoint:

${If.App.WXO}This content is confidential. ${If.End}${If.App.PowerPoint}This presentation is confidential. ${If.End}

In Word, Excel, and Outlook, the label applies the footer text "This content is confidential." In PowerPoint, the label applies the footer text "This presentation is confidential."

Set specific watermark text for Word and PowerPoint, and then watermark text for Word, Excel, and PowerPoint:

${If.App.WP}This content is ${If.End}Confidential

In Word and PowerPoint, the label applies the watermark text "This content is Confidential". In Excel, the label applies the watermark text "Confidential". In Outlook, the label doesn't apply any watermark text because watermarks as visual markings are not supported for Outlook.

I think the second example should read 

${If.App.WPX}This content is Confidential${If.End}${If.App.O}This Email is confidential,${}

Without the X in place this option will not be applied to Excel. In either case the policy will not apply to Outlook since it doesn't support watermarks.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3232645e-090d-0276-521e-d04ae58c5a4e
* Version Independent ID: 7d873c26-2de7-1416-bfdd-8c9288091387
* Content: [Configure visual markings for an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-markings)
* Content Source: [Azure-RMSDocs/configure-policy-markings.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-markings.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @peterjoinobits , thanks for taking the time to send us this feedback! We'll add this to our list of items to clarify / correct in a coming update.

Please note that this article applies to AIP labels only, which are configured in the Azure portal, and are supported by the AIP classic client only. 

If you have the unified labeling client, your sensitivity labels are configured in one of the Microsoft 365 labeling admin center, such as the Security & Compliance Center. For more information, you can read about sensitivity labels here: https://docs.microsoft.com/microsoft-365/compliance/sensitivity-labels

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
