### ISSUE TITLE
Applicability to Sensitivity Labels

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1312]
Do these same instructions apply to changing Sensitivity label in the M365 Compliance Center? if so, please add this confirmation, if not please add a link to the relevant instructions that provide the appropriate guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e01559a-abee-e1eb-9aa2-002095a0dbbd
* Version Independent ID: 7133d3bf-6ba8-1829-e153-d8761e007c34
* Content: [Change an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-change-label)
* Content Source: [Azure-RMSDocs/configure-policy-change-label.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-change-label.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @DeanGross - thanks for taking the time to send us your question! 

This article is relevant only for configuring labels in the Azure portal, supported only by the AIP classic client.
For sensitivity labels and the unified labeling client, see the section on sensitivity labels in the Microsoft 365 docs: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels 

We're currently working on updates throughout the docs to clarify these sorts of issues - what's relevant for the classic client only, and what's relevant for the unified labeling client and sensitivity labels. Stay tuned for the updates!

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
