### ISSUE TITLE
Removing Protection

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#1314]
The cmdlets needed to remove protection from a file are not very clear. This is done with the Set-AIPFile cmdlet and the -RemoveProtection parameter where with the classic client, it was a separate cmdlet. It would be helpful if one of the paragraphs discussing removing protection also pointed to this updated removal process. 

Most documentation points to the older cmdlet: Unprotect-RMSFIle

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7383893-1714-4be5-a499-7f9463fab5e2
* Version Independent ID: f566dfdf-bbae-f671-f012-b5c71e40bf14
* Content: [Use PowerShell with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by batamig** [comment]
Hi @terrogin thanks for taking the time to send us this feedback! I'm adding this to our list to clarify in an upcoming update.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
