### ISSUE TITLE
Exempt Outlook messages from mandatory labeling does not apply to OWA.

### ISSUE THREAD

**Issue by Aishwaryagupta59** [MicrosoftDocs/Azure-RMSDocs#1315]
[When we run Set-LabelPolicy -Identity Global -AdvancedSettings @{DisableMandatoryInOutlook="True"} they apply to only outlook client and not OWA. OWA will prompt for label even after the command is run. We would need to mention this. It is reproducible in test environments.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your feedback! 

We always appreciate getting customer input on our docs and will check on how to clarify this in a coming update.

In the meantime - Office on the web (OWA) uses the built-in labeling functionalities and has the same support as Office would without the Azure Information Protection client. 

You can find more details about the AIP features that are also available for built-in labeling here: 
[Compare the labeling solutions for Windows computers](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-solutions-for-windows-computers) 

I'm closing this for now, but feel free to continue to comment here as needed.
#please-close
