### ISSUE TITLE
MacOS Refresh instructions

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#1316]
The instructions for refreshing templates on MacOS don't appear to work on newer versions of MacOS. Can you please update these?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af8c9c8-cf06-49a4-5f22-bba526bc2734
* Version Independent ID: 868c2079-00f4-eae3-822f-49ae6c8ef63c
* Content: [Refresh Azure RMS templates - AIP](https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates)
* Content Source: [Azure-RMSDocs/refresh-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/refresh-templates.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! I'm going to check back with this team to get any updates and make any required changes with a coming push.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close

**Comment by batamig** [comment]
Hi @terrogin, I'm checking back in with you as I continue to get this information updated.

Can you tell me if you're using Phoenix (the new Outlook Mac), or the Legacy, ribbon-based version? I understand that there was a recent bug fix for Phoenix that should be rolling out shortly. 

Please tag me in your reply - thanks!

**Comment by terrogin** [comment]
Hi Batami – we were using the ribbon-based version

**Comment by batamig** [comment]
Hi @terrogin - if you're having this issue on the legacy system, we recommend that you open a support ticket to troubleshoot, including looking at the various relevant logs.

Thanks again for commenting on docs and best of luck.
