### ISSUE TITLE
Typo in Get-AipServiceTrackingLog example

### ISSUE THREAD

**Issue by Lexy2** [MicrosoftDocs/Azure-RMSDocs#1318]
There is the second "Get-" in the PowerShell example

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179f78bb-2202-5c69-16ec-28f544f7676c
* Version Independent ID: b6a6ebe6-3ce9-9cff-84c3-484479afe7d4
* Content: [Track and revoke access - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/track-and-revoke-admin)
* Content Source: [Azure-RMSDocs/rms-client/track-and-revoke-admin.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/track-and-revoke-admin.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by Lexy2** [comment]
`PS C:\>Get-Get-AipServiceTrackingLog -ContentId c03bf90c-6e40-4f3f-9ba0-2bcd77524b87`

**Comment by batamig** [comment]
Hi @Lexy2 , yep we caught this too and it's already been fixed.  Thanks for taking the time for sending us your feedback!

I'm closing this issue, but feel free to continue to comment here as needed.
#please-close
