### ISSUE TITLE
Tracking and revocation by document owner

### ISSUE THREAD

**Issue by barborico** [MicrosoftDocs/Azure-RMSDocs#1319]
The new AIP client doesn't currently support tracking and revocation by the doc owner. This is alluded to in the [checklist comparison for labeling solutions](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-solutions-for-windows-computers). However, tracking is not mentioned in the [detailed comparison](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#detailed-comparisons-for-the-azure-information-protection-clients) or the [list of legacy features that will not be included in the new client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#features-not-planned-to-be-in-the-azure-information-protection-unified-labeling-client).

Will this feature be added to the unified labeling client? I really hope so, because the central reporting is not a substitute. It does not allow granular RBAC for tracking, and in large organizations it would be a terrible practice to grant individual document owners the [necessary AAD roles](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip#permissions-required-for-azure-information-protection-analytics). My team has continued to use the legacy client for this reason, but we're worried about the upcoming deprecation date.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#features-not-planned-to-be-in-the-azure-information-protection-unified-labeling-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @barborico - thanks for your very timely comment!
We've actually just released a public preview version of the unified labeling client where tracking and revoking is supported.
We've updated the table here: [Compare the labeling solutions for Windows computers](https://docs.microsoft.com/azure/information-protection/rms-client/use-client#compare-the-labeling-solutions-for-windows-computers).

We'd very much look forward to your feedback on this feature! Join the conversation on this feature in our Yammer group: https://www.yammer.com/askipteam/threads/993723252523008

You can find more details, including the specific features supported for admins and users respectively, in the following articles:
- [Release notes](https://docs.microsoft.com/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#track-document-access-and-revoke-access)
- [Admin guide](https://docs.microsoft.com/azure/information-protection/rms-client/track-and-revoke-admin)
- [User guide](https://docs.microsoft.com/azure/information-protection/rms-client/revoke-access-user)
- [Known issues](https://docs.microsoft.com/azure/information-protection/known-issues#tracking-and-revoking-document-access-public-preview)

I'm closing this issue for now, but feel free to comment here as needed.
#please-close

**Comment by barborico** [comment]
It seems like users still can't track document readership in the unified labeling client, which is the main functionality my team relies on. Will this be added? Once the legacy client is deprecated, will authors (who lack org-wide admin permissions) have any way to track who accesses the documents they create and share?

**Comment by batamig** [comment]
Hi @barborico ,
The content group doesn't have the roadmap details for this. 
You may be able to get your answers in our yammer group - feel free to post your question here: https://www.yammer.com/askipteam
