### ISSUE TITLE
Microsoft information protection 

### ISSUE THREAD

**Issue by msellar-inst** [MicrosoftDocs/Azure-RMSDocs#1320]
There is no mention of MIP or where it fits in. 
Eg recent article here doesn’t mention AIP at all

https://techcommunity.microsoft.com/t5/microsoft-security-and/announcing-new-microsoft-information-protection-capabilities-to/ba-p/1999692

you should clarify and link out to what is MIP and how it works with AIP it, if it fact it supersedes it?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8021a68-b55b-93eb-5fd0-abbbf8f5da58
* Version Independent ID: e246079c-8579-0bdc-b7c8-290114e8fa1a
* Content: [Azure Information Protection also known as](https://docs.microsoft.com/en-us/azure/information-protection/aka)
* Content Source: [Azure-RMSDocs/aka.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/aka.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @msellar-inst , and thanks for your feedback!
You can find more information about how MIP and AIP fit together here: https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection

In addition, especially if you have comments on the blogs, I recommend that you start a thread on our yammer group, where several subject matter experts from across the team are available to help explain. See here: https://www.yammer.com/askipteam/

I'll also take another look at this "AIP also known as page" to see if we can clarify further, or at the very least add some links for more information.

We always appreciate hearing from users. I'm closing this issue for now, but feel free to add more comments as needed.
#please-close
