### ISSUE TITLE
Version 2.8.85.0 supports Document Track and Revoke?

### ISSUE THREAD

**Issue by naqash11** [MicrosoftDocs/Azure-RMSDocs#1321]
Hi,

We have AIP Unified Labeling Client version 2.8.85.0 deployed to our users. As per the Microsoft document, it says after upgrading to 2.9.109.0 we will be getting Document Track and Revoke feature but when i ran **Get-AipServiceDocumentTrackingFeature** command in PS, it says "Enabled". How is that possible or am i missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179f78bb-2202-5c69-16ec-28f544f7676c
* Version Independent ID: b6a6ebe6-3ce9-9cff-84c3-484479afe7d4
* Content: [Track and revoke access - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/track-and-revoke-admin)
* Content Source: [Azure-RMSDocs/rms-client/track-and-revoke-admin.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/track-and-revoke-admin.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @naqash11 , thanks for your question!

Before the 2.9.109.0 public preview version, track and revoke was supported for use only with the classic client, even if there may have been technical parameters enabled.

Version 2.9.109.0 now brings these features to the unified labeling client to help create parity between the clients. 

For more information, you might want to read the recent threads on our yammer group at https://www.yammer.com/askipteam/, or start a new one if you need more clarification.

I'm closing this issue for now, but feel free to continue commenting here as needed.
#please-close

**Comment by naqash11** [comment]
Thank you. 

It means that "Enabled" part which i saw in the PS was for classic client not the unified one, correct?

**Comment by batamig** [comment]
That's correct. This parameter is a service-side parameter that supported only the classic client until the 2.9.109.0 public preview.
If you have any specific concerns about your tenant or environment, I encourage you to open a support ticket or find assistance on yammer.

We're always glad to hear from customers. Let us know if you have any further feedback on our docs!
