### ISSUE TITLE
About Office 2010 support for AIP clients

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Azure-RMSDocs#1323]
[Enter feedback here]
The Office 2010 support lifecycle has already ended, so please remove office 2010 from this article.

Ref. "End of support for Office 2010"
https://support.microsoft.com/en-us/office/-3a3e45de-51ac-4944-b2ba-c2e415432789
~~~~~
Support for Office 2010 ended on October 13, 2020 and there will be no extension and no extended security updates. All of your Office 2010 apps will continue to function. However, you could expose yourself to serious and potentially harmful security risks.
~~~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f439846-b6e1-b083-9af4-258475541642
* Version Independent ID: 08624dbb-fe99-bc7d-c2f1-bad8bf35ffd2
* Content: [Install the Azure Information Protection unified labeling client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-install#supported-applications-for-the-unified-labeling-client)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-install.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @juhirao , thanks for your feedback! We do still include Office 2010 information for users who may still have legacy systems in place. 
However, we've included a link to more details in every instance where we've mentioned Office 2010. For more information, see [our known issues article](https://docs.microsoft.com/en-us/azure/information-protection/known-issues#aip-for-windows-and-office-versions-in-extended-support):

**Office 2010 extended support ended on October 13, 2020.**
This support will not be extended, and ESU will not be offered for Office 2010.
We strongly encourage you to upgrade to a newer version of Office 365.
For more information, check with your support contact.
