### ISSUE TITLE
Advanced settings for Labels - No way to query existing advanced settings

### ISSUE THREAD

**Issue by heikobischoff** [MicrosoftDocs/Azure-RMSDocs#1324]
The page describes very detailed how to set advanced settings for labels and label policies, but there is no information how to verify if the change has been applied or how to get existing advanced settings.

I tried to take a look in the documentation of "Get-Label" and verified the output of this commandlet, but I did not find a way to get the advanced settings. 

It would be great to reach out to the PG to implement a way to retrieve existing additional settings and to add this to our documentation.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#feedback)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for your feedback @heikobischoff !

I've reached out to the team for this information and will update the article when we have instructions for doing this.
In the meantime, I recommend that you also post a request on our Yammer group, where you might also be able to get some tips from experts and users. See https://www.yammer.com/askipteam/
