### ISSUE TITLE
Microsoft.InformationProtection.File 1.8.86 incompatible with documentation

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1328]
Hello, I am using the C++ version of the documentation and the Quickstart: Client application initialization (C++) section provides some instructions that appear out of date.

```
auto mipContext = mip::MipContext::Create(appInfo,
    "file_sample",
    mip::LogLevel::Trace,
    nullptr /*loggerDelegateOverride*/,
    nullptr /*telemetryOverride*/);

FileProfile::Settings profileSettings(
    mipContext,
    mip::CacheStorageType::OnDisk,
    authDelegateImpl,
    consentDelegateImpl,
    profileObserver);`

FileEngine::Settings engineSettings(
    mip::Identity("<engine-account>"),
    "<engine-state>",
    "en-US");
```

Gives syntax errors, I believe they should be:

```
auto mipContext = mip::MipContext::Create(appInfo,
    "file_sample",
    mip::LogLevel::Trace,
    false,
    nullptr /*loggerDelegateOverride*/,
    nullptr /*telemetryOverride*/);

FileProfile::Settings profileSettings(
    mipContext,
    mip::CacheStorageType::OnDisk,
    consentDelegateImpl,
    profileObserver);`

FileEngine::Settings engineSettings(
    mip::Identity("*****"),
    authDelegateImpl,
    "*****",
    "en-US");
```

However, with these changes made, I am receiving the following exception when I try to run step 2 of Build and test the application in the next section (Quickstart: List sensitivity labels (C++))

`line 24: Unhandled exception at 0x7574A842 in ConsoleApplication1.exe: Microsoft C++ exception: std::bad_alloc at memory location 0x003EF1DC.`

**Comment by batamig** [comment]
Hi @catmanjan - thanks for the feedback! We always appreciate input from our users.
I'm tagging the authors on this page to bring this to their attention. @msmbaldwin and @tommoser can you take a look?

**Comment by tommoser** [comment]
Thanks for the feedback. On the first part, you are correct and we'll need to update that.

The 2nd one is a bug that we're working to fix in the NuGet package. I should have an update out this week. For now, if you use release mode, it'll work without issue.

**Comment by catmanjan** [comment]
Thanks @tommoser 

I now get this exception `Unhandled exception at 0x7574A842 in ConsoleApplication1.exe: Microsoft C++ exception: mipns::FileIOError at memory location 0x004FF7D0.`

at the line: `auto profile = profileFuture.get();`

**Comment by tommoser** [comment]
That's not an error I've seen previously. I'll have to step through the sample. If you clone one of the samples from GitHub and try that, does it work? 

https://docs.microsoft.com/en-us/samples/azure-samples/mipsdk-fileapi-cpp-sample-basic/mipsdk-fileapi-cpp-sample-basic/

**Comment by catmanjan** [comment]
> That's not an error I've seen previously. I'll have to step through the sample. If you clone one of the samples from GitHub and try that, does it work?
> 
> https://docs.microsoft.com/en-us/samples/azure-samples/mipsdk-fileapi-cpp-sample-basic/mipsdk-fileapi-cpp-sample-basic/

I worked it out, the file path I was providing was fully qualified, it worked when I swapped it to a relative file path - not sure why the fully qualified path didn't work though...

**Comment by batamig** [comment]
thanks @catmanjan for getting back to us! I'm closing this for now, but feel free to send us more feedback or comment more as needed.
and thank you @tommoser for handling the details here.

#please-close
