### ISSUE TITLE
Label migration approach for tenant to tenant migration is missing

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#1331]
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#migrate-labels-from-secure-islands-and-other-labeling-solutions

In above link, it is mentioned that labels can be migrated from other solutions but what about a scenario where labels need to be migrated from one tenant (using classic AIP labels) to another tenant (using Sensitivity labels in SCC). Will this given approach will work in tenant to tenant migration scenario also? In any case, this scenario should be covered in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#migrate-labels-from-secure-islands-and-other-labeling-solutions)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @prashant1380 - thanks for sending us your question!

To migrate your labels from the classic client and the AIP portal to sensitivity labels in the Microsoft 365 compliance center, you'll need to upgrade from the classic client to unified labeling.

You can learn more about that scenario here: https://docs.microsoft.com/en-us/azure/information-protection/tutorial-migrating-to-ul

I'm going to close this issue for now, but please feel free to add more comments as needed. 
#please-close

**Comment by prashant1380** [comment]
I am not sure if I have explained the scenario well. But the scenario is to migrate the labels from one tenant to another tenant. Lets assume that in both tenants I am using Sensitivity labels but different ones and now as an outcome of company mergers, I need to map the labels from one tenant to another so that once the documents from source tenant are migrated to destination tenant, destination tenant should be applicable to migrated documents as per the mapping or rules.
This scenario is missing in the documentation.

**Comment by batamig** [comment]
Ah - I see. I'm going to look for more info about this and consult with the development team.
This might be in the M365 documentation if it's done on the side of the sensitivity labels and policies themselves.
I've added an item to our backlog to add more details about this as needed when it's clearer. 

I also recommend that you ask your question on our yammer group: https://www.yammer.com/askipteam/
There are experienced professionals from both the field and the PM team who might be able to help you.

Hope that helps!

**Comment by batamig** [comment]
Hi @prashant1380 
Here's a relevant blog post that might help your situation. 
https://techcommunity.microsoft.com/t5/microsoft-security-and/mergers-and-spinoffs/ba-p/910455 

If you have more questions, please feel free to add them as a comment directly on the blog post, or post in Yammer as above. 
I'll be adding this link into the docs so that it's clearer for users moving forward.

Thank you for raising this issue!
