### ISSUE TITLE
Crash in MIP SDK java wrapper for version 1.8.86

### ISSUE THREAD

**Issue by bishnu1184** [MicrosoftDocs/Azure-RMSDocs#1332]
Hi,

I am using MIP SDK 1.8.86 JAVA wrapper sample to work with MIP labels.
When I am using JAVA wrapper sample It is failing while trying to add MIP Engine. 
I am using plain text user name and password to the sample and I can see that in AuthDelegateUserCredentials::acquireToken(), I am getting token as well, but then before addEngineAsync()->Future() returns it crashes somewhere underneath.
In MIP log I am getting error message 

"Error	2021-02-16 13:50:18.220	common/api_utils.h:232	java (7616)	"Unrecognized exception: profile_add_engine_async"	mipns::TryExecuteFailureCallback	10728"

In windows evenviewer I am getting windows event 

Faulting application name: java.exe, version: 8.0.2420.8, time stamp: 0x5e246f62
Faulting module name: ntdll.dll, version: 10.0.17763.475, time stamp: 0x3230aa04
Exception code: 0xc0000374
Fault offset: 0x00000000000fb049
Faulting process id: 0x32d4
Faulting application start time: 0x01d7042ebd1e7569
Faulting application path: C:\code\depot\tools\windows\OpenJDK\1.8.0_242\x64\bin\java.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: efd2af40-701d-4dab-a3b0-640a77a48881
Faulting package full name: 
Faulting package-relative application ID: 

Which look like to some kind of memory corruption.
Because of above issue, I am not able to test JAVA wrapper sample.
Can you please suggest where I should look into, to identify and fix the issue ?

Thanks,
Bishnu

**Comment by batamig** [comment]
Thanks for taking the time to send us your question! I'm tagging the content owner to reply
@tommoser can you take a look?

**Comment by batamig** [comment]
Hi @bishnu1184 I'm going to close this issue as it's been open for a while with no response. 
You can still reply though - feel free to tag me and we can re-open as needed.
Thanks for getting in touch!

#please-close
