### ISSUE TITLE
Unified labeling not only for content also for workspaces

### ISSUE THREAD

**Issue by bullipauline** [MicrosoftDocs/Azure-RMSDocs#1335]
Is there a plan to offer MIP unified labeling like label an Office document by using an existing custom property or to replace SharePoint IRM wiith unified labeling?

Is there a plan to use the following advanced classic client settings also in unified labeling?
SyncPropertyName | Label an Office document by using an existing custom property
SyncPropertyState | Label an Office document by using an existing custom property

Thanks
Christopher

**Comment by batamig** [comment]
Thanks for taking the time to send us your questions! We don't address questions about future support planned in the docs, but recommend that you check the following resources:

- [Microsoft 365 roadmap](https://www.microsoft.com/en-ww/microsoft-365/roadmap?=&filters=Azure%20Information%20Protection)
- [The AIP group on Yammer](https://www.yammer.com/askipteam/)

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
