### ISSUE TITLE
Latest release in preview?

### ISSUE THREAD

**Issue by ToninoBruno** [MicrosoftDocs/Azure-RMSDocs#1336]
Hi,

in the Release Information section you mention "The latest version of Azure Information Protection is currently in PREVIEW.", however the latest version of AIP is actually GA isn't it? Can you perhaps clarify this?

2.9.116 is mentioned as GA on the download link: https://www.microsoft.com/en-us/download/details.aspx?id=53018

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection unified labeling client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history?source=docs#version-29116)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi - Thanks for taking the time to send us your question! You are correct, and we'll get this fixed to a more neutral and sustainable wording.

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
