### ISSUE TITLE
Clarify the more than one classification paragraph

### ISSUE THREAD

**Issue by kebuijs** [MicrosoftDocs/Azure-RMSDocs#1338]
This section: "Can a file have more than one **classification?**" Only applies to the Classic Azure Information client. With Unified Labeling we no longer store the parent label in the meta data of the document. I had a customer asking for this based on this article. Perhaps clarify the article that this only applies to AIP Classic.

Thanks
Best,

Kevin Buijs
Customer Engineer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb834-9023-f79b-115e-199c4e1af17b
* Version Independent ID: a0ea852a-eedd-b205-91c0-bfa8732fa9f3
* Content: [FAQs for classification & labeling - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#can-a-file-have-more-than-one-classification)
* Content Source: [Azure-RMSDocs/faqs-infoprotect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-infoprotect.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @kebuijs - thanks for this! It must have been missed when we re-organized the docs for classic vs UL client. We'll move this FAQ to this page instead:
https://docs.microsoft.com/en-us/azure/information-protection/faqs-classic

We always welcome input on docs - feel free to be in touch if you have further feedback.

**Comment by batamig** [comment]
#please-close
