### ISSUE TITLE
Does the Azure RMS Connector support Unified Labelling?

### ISSUE THREAD

**Issue by mtwelve** [MicrosoftDocs/Azure-RMSDocs#1339]
Hello,

It is not clear from the documentation if existing deployments of the Azure RMS Connector are supported once a Tenant migrates to use Unified Labelling.

Can you please confirm? and potentially add it in to the FAQ.

Thanks

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0547cf-7694-72e8-1c35-05502fc18233
* Version Independent ID: 3bdb8088-8d87-32aa-6252-f3f9c4944adc
* Content: [FAQs for Azure Information Protection (AIP)](https://docs.microsoft.com/en-gb/azure/information-protection/faqs)
* Content Source: [Azure-RMSDocs/faqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @mtwelve , thanks for getting in touch! Yes, the connector component doesn't affect the labeling, so nothing changes.
In general, we've tried to call out any differences post-migration. You can see some helpful links in the migration tutorial here:
https://docs.microsoft.com/azure/information-protection/tutorial-migrating-to-ul#planning-your-migration

We'll consider a collection of migration FAQs and appreciate the suggestion!

I'm closing this issue for now, but feel free to comment further if you have additional feedback.
#please-close
