### ISSUE TITLE
Dead Link for "View label usage with label analytics"

### ISSUE THREAD

**Issue by MichaelTGS** [MicrosoftDocs/Azure-RMSDocs#1340]
Heyo

At the end of the page it says:

> If you have a Microsoft 365 subscription, you can also view label usage in the Microsoft 365 compliance center and Microsoft 365 security center. For more information, see **View label usage with label analytics**.

The Link at the end leads to a 404 - Page not found: View label usage with label analytics - https://docs.microsoft.com/en-us/microsoft-365/compliance/label-analytics

I don't know where this should actually lead to.

Cheerio and thanks a lot

Michael

**Comment by batamig** [comment]
Hi @MichaelTGS , thanks for letting us know about this error!
In M365, as a Public Preview feature, you can view label analytics in the Activity Explorer.

You can read more about this here:
- https://www.yammer.com/askipteam/#/Threads/show?threadId=1085834054254592
- https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer

I'm going to update the docs and close this issue for now, but feel free to continue commenting as needed. 
#please-close
