### ISSUE TITLE
This page has old information including old 'Office 365' plans listed including Microsoft 365 plans. It also links to a PDF that is relevant in 2018 with inaccurate data on it.

### ISSUE THREAD

**Issue by useyourblinker** [MicrosoftDocs/Azure-RMSDocs#1346]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @useyourblinker - thanks for your comment on docs! We'll be doing a full refresh of this page in an upcoming sprint and will be sure to update with any fixes required. 

I'm closing this issue for now, but please feel free to continue to comment as needed.
#please-close
