### ISSUE TITLE
Terminology usage in AIP articles

### ISSUE THREAD

**Issue by ww185010** [MicrosoftDocs/Azure-RMSDocs#1347]
Can you guys please stop using the word "deprecate" in your articles? To "deprecate" means to strongly discourage or disapprove of. It does *not* mean decommission, retire, shut down, etc. Deprecating a technology is done with the intention of retiring/removing support for it at some point in the future.

For example, you already deprecated classic AIP last year when announcing the March 31, 2021 end of life and directing customers to the UL platform. What's happening end of this month is decommission/retirement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ww185010 - thanks for the feedback! It's important to us that our docs are clear and use industry-standard terms. 
I'm going to take this back to the team to verify the update and am adding this to the backlog to update the docs as needed.

I'm closing this issue for now, but feel free to continue to comment if you have more input.
#please-close
