### ISSUE TITLE
Disconnect-AipServiceService - Double Service is not correct. please remove one service

### ISSUE THREAD

**Issue by LFAdmin** [MicrosoftDocs/Azure-RMSDocs#1349]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c1dfd71-5c6f-0a5c-e5cf-fd3f030cd6d4
* Version Independent ID: 314c4efc-5b52-de27-8ebe-512d9f69ded1
* Content: [Migrate software-protected key to software-protected key - AIP](https://docs.microsoft.com/en-us/azure/information-protection/migrate-softwarekey-to-softwarekey)
* Content Source: [Azure-RMSDocs/migrate-softwarekey-to-softwarekey.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-softwarekey-to-softwarekey.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for the heads up @LFAdmin ! Fixing now. 
I'm closing this issue, feel free to comment further if you have additional feedback.

#please-close
