### ISSUE TITLE
What's new for the portal?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#1351]
This is good info about what's new in the scanner and the client, but where can I find similar information for changes to the actual information protection solution in the M365 Compliance Center? it would be helpful to have a similar page for those changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [What's new in Azure Information Protection (AIP) - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @DeanGross , thanks for getting in touch, and glad to hear that you appreciate our client what's new updates. 
For the portal, Microsoft 365 services send out emails to relevant customers about new updates, and they also maintain this the [https://docs.microsoft.com/en-us/microsoft-365/compliance/whats-new](What's new in Microsoft 365 compliance) article, which includes new items for sensitivity labels. 

There's also the roadmap, which you can check for upcoming features: [Microsoft 365 roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=Microsoft%2CInformation%2CProtection)

I'm closing this issue for now, but feel free to add more comments as needed.

#please-close

**Comment by DeanGross** [comment]
Thanks for the link to that page, it would be helpful to include these links on this page to make it easier for people to find the new info.

**Comment by batamig** [comment]
great idea! will add.
