### ISSUE TITLE
Inconsistent naming

### ISSUE THREAD

**Issue by aashishr** [MicrosoftDocs/Azure-RMSDocs#1353]
This page refers to the same product with 2 different names:
1. Azure Rights Management connector
2. Microsoft Rights Management connector

The download center uses the name Microsoft Rights Management connector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27cf3df-2659-7631-f9dc-0b93dd77c1d0
* Version Independent ID: ae656aa6-3b57-0674-b5b5-daf7b1e64653
* Content: [Deploy the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-rms-connector)
* Content Source: [Azure-RMSDocs/deploy-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
thanks @aashishr ! Updating the branding here throughout this section, keep watch for the updated text.

**Comment by batamig** [comment]
closing this issue for now, feel free to be in touch or comment further as needed.
#please-close
