### ISSUE TITLE
Link to Download Scanner not working

### ISSUE THREAD

**Issue by theodore-august-salve** [MicrosoftDocs/Azure-RMSDocs#1354]
[Enter feedback here]
The link to download the scanner is not currently working:

https://www.microsoft.com/download/details.aspx?id=53018

"We're sorry, this download is no longer available."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0927bf-7a11-d800-f0ae-a1c0ce4dcb06
* Version Independent ID: ef830f65-1986-830e-be04-95d163d2de6c
* Content: [Tutorial - Install the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/tutorial-install-scanner)
* Content Source: [Azure-RMSDocs/tutorial-install-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/tutorial-install-scanner.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @theodore-august-salve and thanks for your feedback!

I'm looking for the broken URL, and don't see one that's not working. 
This site is live, and provides the links to the latest versions of the AIP unified labeling client:
https://www.microsoft.com/en-us/download/details.aspx?id=53018

Here's the direct link to the download:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=53018

The client installation also includes the scanner files. 

Can you explain further which one you're looking at?

**Comment by theodore-august-salve** [comment]
Thank you. It’s working now. The publish date is 4/23/21 perhaps it was down for updating when I tried to download.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Batami Gold ***@***.***>
Sent: Sunday, April 25, 2021 7:15:04 AM
To: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Theodore J. August ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MicrosoftDocs/Azure-RMSDocs] Link to Download Scanner not working (#1354)


Hi @theodore-august-salve<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftheodore-august-salve&data=04%7C01%7Ctheodore.august%40salve.edu%7C2450dbebcfa04d8612bb08d907db60d6%7Cf0e0e20bdffd4b058c6c74ab98a56cd9%7C0%7C0%7C637549461089635932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3NT4L8S%2FZ%2FLaVW7AW8VOspFwam8TdEHE1W7xOLSjiao%3D&reserved=0> and thanks for your feedback!

I'm looking for the broken URL, and don't see one that's not working.
This site is live, and provides the links to the latest versions of the AIP unified labeling client:
https://www.microsoft.com/en-us/download/details.aspx?id=53018<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fdetails.aspx%3Fid%3D53018&data=04%7C01%7Ctheodore.august%40salve.edu%7C2450dbebcfa04d8612bb08d907db60d6%7Cf0e0e20bdffd4b058c6c74ab98a56cd9%7C0%7C0%7C637549461089641019%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zhy%2BMNhWJfPZgkvXHvDFoL8BskD3KD3%2Fo0ERs%2BMNXMw%3D&reserved=0>

Here's the direct link to the download:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=53018<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2Fdownload%2Fconfirmation.aspx%3Fid%3D53018&data=04%7C01%7Ctheodore.august%40salve.edu%7C2450dbebcfa04d8612bb08d907db60d6%7Cf0e0e20bdffd4b058c6c74ab98a56cd9%7C0%7C0%7C637549461089645900%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nb11QKByg7PrxHwXkXubYmFvnCJw2wFSk9WMn%2FgODfA%3D&reserved=0>

The client installation also includes the scanner files.

Can you explain further which one you're looking at?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FAzure-RMSDocs%2Fissues%2F1354%23issuecomment-826306675&data=04%7C01%7Ctheodore.august%40salve.edu%7C2450dbebcfa04d8612bb08d907db60d6%7Cf0e0e20bdffd4b058c6c74ab98a56cd9%7C0%7C0%7C637549461089650876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WRlfX%2B861Z7suGXokn4s37fXwd%2BrRTABPky2n9rZymc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAS2RF6CCKWCCQLCRUBNYRNDTKP2TRANCNFSM43NW2DLA&data=04%7C01%7Ctheodore.august%40salve.edu%7C2450dbebcfa04d8612bb08d907db60d6%7Cf0e0e20bdffd4b058c6c74ab98a56cd9%7C0%7C0%7C637549461089655856%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iItvPMm6PuPDl%2F%2BSRkCHdOuj66bIkXtwweFzxExujEI%3D&reserved=0>.

*** This message was not sent from a Salve Regina University e-mail address. Please exercise caution when responding, clicking on links or opening attachments. ***

**Comment by batamig** [comment]
Thanks for the follow up, @theodore-august-salve! I'm closing this issue for now, but please feel free to comment further as needed.

#please-close
