### ISSUE TITLE
Removing/Replacing the warn, justify, block option for a specific label in outlook

### ISSUE THREAD

**Issue by jonnunez** [MicrosoftDocs/Azure-RMSDocs#1355]
I do not see any documentations about how to remove the custom configuration of either blocking, warning or providing justification for a label that already has it.

For example, I already have a label that shows the block message, how do I replace that or remove it from the label? Or is it not possible? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations#to-implement-the-warn-justify-or-block-pop-up-messages-for-specific-labels)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @jonnunez , thanks for sending your question on docs!

You can remove any advanced setting, including custom configurations for blocking, warning, or justification popups, by running the command again with a null value.

For example: 
```Set-LabelPolicy -Identity Global -AdvancedSettings @{OutlookWarnUntrustedCollaborationLabel=""}```

Run each of the commands you've used to define your settings again with null values to clear the settings you've defined.

You can find more sample commands in this section in the same article: [Examples for setting advanced settings](https://docs.microsoft.com/azure/information-protection/rms-client/clientv2-admin-guide-customizations#examples-for-setting-advanced-settings)

I'm closing this issue for now, but feel free to continue to comment as needed.

#please-close

**Comment by jonnunez** [comment]
I tried it, but still get that Email Blocked message for the specified label.

**Comment by batamig** [comment]
Hi @jonnunez, in this case, please open a support ticket to clarify the issue. For more information, see [Support options and community resources](https://docs.microsoft.com/azure/information-protection/information-support#support-options-and-community-resources) in our docs.

You might also find content in our yammer group helpful. See https://www.yammer.com/AskIPTeam for details.
