### ISSUE TITLE
authorization rule typo causes deployment failure

### ISSUE THREAD

**Issue by ChristianWeisse** [MicrosoftDocs/Azure-RMSDocs#1356]
in  Step 1: To configure AD FS
the powershell script for the Authorization ClaimRule 
(...)

> # AuthorizationRules used by Microsoft Rights Management Mobile Device Extension
> # Allow All users
> $AuthorizationRules = @"
> @RuleTemplate = "AllowAllAuthzRule"
>  => issue(Type = "https://schemas.microsoft.com/authorization/claims/permit",
> Value = "true");
> "@

(...)

incorrectly uses the HTTPS schema but the claim type should be using an HTTP scheme 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ChristianWeisse - thanks for your feedback on docs!
I appreciate your bringing this to our attention, and I'm going to check back with our team before publishing this fix.

I'm closing this issue for now, but feel free to continue commenting as needed.
#please-close
