### ISSUE TITLE
File not found for AIP UL Client 

### ISSUE THREAD

**Issue by arvindsindhu** [MicrosoftDocs/Azure-RMSDocs#1357]
ON the downloads page getting File not found for UL Client. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a057cea1-1a22-ce8a-d5cb-a67ec5356937
* Version Independent ID: 164f11e2-08a5-90d2-a600-9a5beba015c7
* Content: [Download & install the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/install-unifiedlabelingclient-app)
* Content Source: [Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/install-unifiedlabelingclient-app.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @arvindsindhu - thanks for getting in touch!
I'm going to close this issue for now but pass this on to the product team in case they aren't yet aware of an issue.

#please-close
