### ISSUE TITLE
DNS SRV records format is unclear

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1360]
In one section it says:

"The SRV records have the following format: _rmsdisco._http._tcp. <emailsuffix><portnumber><RMSClusterFQDN>"

But the example shows:

"_rmsdisco._http._tcp.contoso.com 443 _rmsserver.contoso.com"

Notice that the former has a space before email suffix and no spaces anywhere else, whereas the latter has spaces surrounding the port number.

Do these differences matter? If so, which one is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device#specifying-the-dns-srv-records-for-the-ad-rms-mobile-device-extension)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @catmanjan , thanks for sending your question to docs! 
I'm going to check back with the team about this one and get a reply / update in our docs as needed.

**Comment by batamig** [comment]
Hi @catmanjan , I've added this item to my other work item to clarify instructions on this page.
In the meantime, I'm going to close this item while we make the updates - if you have other feedback to send, please do! 
We always appreciate input from users on our docs.

Thanks!
#please-close

**Comment by batamig** [comment]
Hi @catmanjan , just coming back to confirm with you that the examples shown have the correct syntax. There should be no space before the email suffix, but there should be spaces around the port. 

Docs should be updated shortly.
