### ISSUE TITLE
Unable to install AD RMS mobile device extension

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1361]
I've tried following the install doco here https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn673574(v=ws.11)#deploying-the-ad-rms-mobile-device-extension

Which is linked in the reported page, after trying to install the extension I get a generic "installation failed and had to roll back" message in the GUI installer

Checking the installation logs %temp% I see the following error:

```
Calling custom action MobileDeviceExtensions!Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.AddUserAccessToConnectionRegkey
start AddUserAccessToConnectionRegkey.
AddUserAccessToConnectionRegkey failed due to error : System.ArgumentException: Mobile Device Extension doesn't support WID.
Parameter name: connectionString
   at Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.VerifyConnectionString(String connectionString)
   at Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.AddUserAccessToConnectionRegkey(Session session)```


---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device#specifying-the-dns-srv-records-for-the-ad-rms-mobile-device-extension)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @catmanjan - thanks for sending your question to docs!

The link you included in your question goes to the "previous versions" area of our docs, which is usually used for services that are already end of life or out of support.
 
Does this page in our main, live AIP docs help you? https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device

**Comment by catmanjan** [comment]
Unfortunately no, I've tried following that guide too and I still get the error `Mobile Device Extension doesn't support WID.`

**Comment by batamig** [comment]
Hi @catmanjan, I would suggest at this point that you open a support ticket. Our Yammer group at https://www.yammer.com/askipteam/ might also be able to help you.

I'm going to close this issue for now, although you can continue to comment here as needed. 
#please-close
