### ISSUE TITLE
All users can sync Microsoft Edge data, regardless of licensing.

### ISSUE THREAD

**Issue by alareed** [MicrosoftDocs/Azure-RMSDocs#1362]
Just thought I would see if you think that maybe this could be a little clearer. 

> Not complaining I realize Stuff Happens!! Just trying to  help when I can.

This is a little confusing, _along with the webpage mentioning the newest updates to Microsoft Edge_.

If you go to this [paragraph](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-enterprise-sync#configure-microsoft-edge-sync) the way it reads to me is: "As long as client has one of Microsoft's 365 Work or School subscriptions that is all that is required in order to have edge since with a Work or School Account, as it states
>All users can sync Microsoft Edge data, regardless of licensing.

Although as soon as you click the last link in that paragraph to get started setting it up A guy gets shot down. LOL

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9c7ecc-5a13-fe26-6998-6d11ca2ed394
* Version Independent ID: 910e8fe7-03a9-f285-b6fd-7b051b2e81c1
* Content: [Activate Azure RMS from the Microsoft 365 admin center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/activate-office365)
* Content Source: [Azure-RMSDocs/activate-office365.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/activate-office365.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @alareed - thanks for sending your comment to docs! We always appreciate hearing from our users.

Can you clarify what you mean by your comments? 
I don't see Edge mentioned on this page at all: https://docs.microsoft.com/en-us/azure/information-protection/activate-office365

I'd be glad to clarify whatever we can and would like to understand more about what's confusing here.

**Comment by alareed** [comment]
Hello,

Due to the fact that I submitted the email on one of Microsoft's support links I do not have the original links to the pages.

Either way it's not a big deal, I wasn't complaining at all, I just got turned around a little bit & thought to maybe help out by mentioning it in case anyone else had the same problem.

Also just wanted to mention that everyone at Microsoft is doing a great job with everything including the help & learning documents. Keep up the great work!!

Wishing you a great Week!!

Thank You,
Allen Reed

**Comment by batamig** [comment]
Hi @alareed - thank you so much for your lovely reply! I'm so glad that our work helps you on a regular basis.

If there's anything we can clear up about this issue you were having here, please let us know and we'll do our best to work it out.

I'm going to close this issue for now, but please feel free to keep commenting as needed.
#please-close
