### ISSUE TITLE
meeting invites?

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/Azure-RMSDocs#1363]
Yall have alot of good stuff.  but where are the labels for meeting invites?  its just as sensitive as literally anything.  

Example:
Meeting invite:
Subject: were selling our company 

no tags .... OH NOOOOOOOOOOOOOOOOOOOOOOOOOOOO

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb834-9023-f79b-115e-199c4e1af17b
* Version Independent ID: a0ea852a-eedd-b205-91c0-bfa8732fa9f3
* Content: [FAQs for classification & labeling - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect)
* Content Source: [Azure-RMSDocs/faqs-infoprotect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-infoprotect.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @SquirrelAssassin - thanks for sending your question to docs! I checked with our PM team, and this is indeed not currently supported by Azure Information Protection.

You can find more information about the roadmap for Microsoft Information Protection here: https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=Microsoft%2CInformation%2CProtection
You're also welcome to post questions to the team in our Yammer group: https://www.yammer.com/askipteam/

Hope this helps! I'm closing this issue for now, but feel free to add more comments as needed.

#please-close
