### ISSUE TITLE
Specifying the DNS SRV records for the AD RMS mobile device extension lists the same instruction twice

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1364]
In one section it has the following instructions:

![image](https://user-images.githubusercontent.com/137350/116831153-fc665e00-abf0-11eb-83c5-d747b3476479.png)

And below, it tells you to create these registrations again

![image](https://user-images.githubusercontent.com/137350/116831165-0be5a700-abf1-11eb-8ed8-a6dd44f6fc17.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
thanks @catmanjan !  This looks like it might be a bug. I'm going to open an item in our backlog to investigate further and will update the page after confirming with our team. 

I'm going to close this issue for now, but feel free to continue commenting as needed.
Thank you so much for your comments on docs - we always appreciate input from our users!

#please-close
