### ISSUE TITLE
Unprotecting Files

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#1365]
This page references the Unprotect-RMSFile for the classic and UL clients, but this cmdlet is only present for the classic client. Is there a separate process for the UL client?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d4b87c-1f20-37b4-be0b-f69354df1830
* Version Independent ID: 2bb88bdb-bbcd-033e-e23e-da88ed8a67e0
* Content: [Configure super users for Azure Rights Management - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-super-users)
* Content Source: [Azure-RMSDocs/configure-super-users.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-super-users.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @terrogin - thanks for your question on docs!
With the unified labeling client, the way to remove protection via PowerShell is by using the Set-AIPFileLabel cmdlet with the RemoveProtection parameter. 
See an example here:
https://docs.microsoft.com/en-us/powershell/module/azureinformationprotection/set-aipfilelabel?view=azureipps#example-8---unified-labeling-client-only--remove-protection-from-a-file

I appreciate you bringing this to our attention - I'll make a point to update this page with the correct cmdlet for the UL client. 
I'm closing this issue for now, but feel free to add more comments as needed! 
#please-close
