### ISSUE TITLE
rights managment activation 

### ISSUE THREAD

**Issue by lifewillfindaway** [MicrosoftDocs/Azure-RMSDocs#1367]
[Enter feedback here]

Under a global admin account, 
I navigate to the rights management page from the admin center: Settings > Org settings > Services tab > Microsoft Azure Information Protection > Manage Microsoft Azure Information Protection settings

On the rights management page, I do not see click activate.

Instead I see " to activate the protection service, please refer to the official documentation"

My user has office 365 premium with the information protection premium P1 add on. 

I am able to create sensitivity labels, but not encrypt files and emails. it states that Rights management is not active for tenet. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f9c7ecc-5a13-fe26-6998-6d11ca2ed394
* Version Independent ID: 910e8fe7-03a9-f285-b6fd-7b051b2e81c1
* Content: [Activate Azure RMS from the Microsoft 365 admin center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/activate-office365)
* Content Source: [Azure-RMSDocs/activate-office365.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/activate-office365.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by lifewillfindaway** [comment]
Resolved issue. 

https://docs.microsoft.com/en-us/azure/information-protection/activate-service#supported-activation-methods

Alternatively, you can use the following PowerShell commands:

Install the AIPService module, to configure and manage the protection service. For instructions, see Installing the AIPService PowerShell module.

From a PowerShell session, run Connect-AipService, and when prompted, provide the Global Administrator account details for your Azure Information Protection tenant.

Run Get-AipService to confirm whether the protection service is activated. A status of Enabled confirms activation; Disabled indicates that the service is deactivated.

To activate the service, run Enable-AipService.

**Comment by batamig** [comment]
Hi @lifewillfindaway, thanks so much for sending your question on docs, and so glad that you were able to resolve your issue with another article in our documentation!
I'm closing this issue for now, but feel free to add more comments or open a new issue as needed.

#please-close
