### ISSUE TITLE
explain Authority , resource and client ID

### ISSUE THREAD

**Issue by dharmendramiet** [MicrosoftDocs/Azure-RMSDocs#1368]
I was exploring this document https://docs.microsoft.com/en-us/information-protection/develop/concept-authentication-acquire-token-py#python-script

 

I wanted to know what should be the value of authority, resource, and client ID here? looks like it is not explained in the document.
 print('auth.py -u <username> -p <password> -a <authority> -r <resource> -c <clientId>')

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c74c069-3608-12d1-8988-461524e2de55
* Version Independent ID: f18cd6ad-c0e2-fca1-9bef-c4edf7c8533c
* Content: [Concepts - Using Python to acquire an access token.](https://docs.microsoft.com/en-us/information-protection/develop/concept-authentication-acquire-token-py)
* Content Source: [mip/develop/concept-authentication-acquire-token-py.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-authentication-acquire-token-py.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @dharmendramiet - thanks for your comment on docs! 
I'm tagging the focal points for this article. @tommoser , @msmbaldwin , can you take a look?

**Comment by tommoser** [comment]
Those values are opaque to the application. MIP SDK passes them in at runtime via AuthDelegate::AcquireOAuth2Token(), except for client ID, which you're required to pass in to your AuthDelegate implementation.

**Comment by batamig** [comment]
Thanks @tommoser !
@dharmendramiet, I'm going to close this issue for now, but feel free to add more comments as needed. 

#please-close
