### ISSUE TITLE
Document comment out of date

### ISSUE THREAD

**Issue by bloodytourists** [MicrosoftDocs/Azure-RMSDocs#1369]
"However, if you have a document that you want to store in SharePoint and this document should not be returned in search results, protect the document before uploading it to SharePoint."

This is no longer the case once you switch on labelling for SPO, which stores all protected content (assuming it is protected with a label) in the clear so searching still function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 122e8638-3a2c-257d-ae9e-2bed351f9011
* Version Independent ID: 520603fa-6658-653c-68b8-7bf92ff0daa0
* Content: [How apps support Azure Rights Management from AIP](https://docs.microsoft.com/en-us/azure/information-protection/applications-support)
* Content Source: [Azure-RMSDocs/applications-support.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/applications-support.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @bloodytourists - thanks for your feedback here! I've checked with the product team and indeed, this example is no longer relevant and we've removed it.
Thanks for your contribution to Microsoft docs!

I'm closing this issue for now but feel free to continue adding comments as needed.

#please-close
