### ISSUE TITLE
Discrepancy between RMS Connector supported OS on download page and documentation

### ISSUE THREAD

**Issue by m49808** [MicrosoftDocs/Azure-RMSDocs#1370]
See download page: https://www.microsoft.com/en-us/download/details.aspx?id=40839

It lists the following system requirements (my emphasis added)

System Requirements
Supported Operating System
**Windows Server 2019,** Windows Server 2016, Windows Server 2012 R2 Datacenter, Windows Server 2012 R2 Standard , Windows Server 2012 R2, Windows Server 2012, Windows Server 2012 Standard, Windows Server 2012 Datacenter

**For connector server**: x64-based server running Windows Server 2012, Windows Server 2012 R2, Windows Server 2016, and **Windows Server 2019** At least 1GB of RAM 64GB of disk space one network interface of 100mbps or faster To use the server configuration tool, follow the instructions at http://technet.microsoft.com/en-us/library/dn375964.aspx.

This document seems to contradict that:

"The RMS connector is a small-footprint service that you install on-premises, on servers that run Windows Server 2016, Windows Server 2012 R2, Windows Server 2012" (**no Server 2019 listed**)

"A 64-bit physical or virtual computer running one of the following operating systems: Windows Server 2016, Windows Server 2012 R2, Windows Server 2012" (**no Server 2019 listed**)

Which is correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27cf3df-2659-7631-f9dc-0b93dd77c1d0
* Version Independent ID: ae656aa6-3b57-0674-b5b5-daf7b1e64653
* Content: [Deploy the Rights Management connector - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-rms-connector)
* Content Source: [Azure-RMSDocs/deploy-rms-connector.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @m49808! I'm checking with the team on this one before we make this update, but I wanted to acknowledge your question! 
I'll get back to you when I get the fixed confirmed.
Thanks for your contribution to docs.

**Comment by batamig** [comment]
Hi - I'm updating that the download page was correct in this case, and we'll be updating the docs page to match.
Thanks for raising the fix that was needed!

I'm closing this issue for now, but feel free to add more comments as needed.
#please-close
