### ISSUE TITLE
 Azure Information Protection pricing link 404Error 

### ISSUE THREAD

**Issue by AureliaDumitru** [MicrosoftDocs/Azure-RMSDocs#1372]
Hi,

I get an error when try to access :  Azure Information Protection pricing.
Error: We're sorry, this download is no longer available /404Error

Kind Regards,
Aurelia Dumitru

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements#feedback)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks @AureliaDumitru for getting in touch!

We're in the process of updating all of these links as relevant to the Microsoft 365 page here: [Microsoft 365 licensing guidance for security & compliance](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection)

I hope that the information on the Microsoft 365 page provides the information that you need. If you have further questions, feel free to open a Git issue on that page, or to contact customer support.

I'm closing this issue for now, but you can also feel free to continue commenting here as needed.

#please-close
