### ISSUE TITLE
Error Deploying the AD RMS mobile device extension

### ISSUE THREAD

**Issue by catmanjan** [MicrosoftDocs/Azure-RMSDocs#1374]
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn673574(v=ws.11)#deploying-the-ad-rms-mobile-device-extension

If you try to install the ADRMS.MobileDeviceExtension.exe linked above you get the following error

```Calling custom action MobileDeviceExtensions!Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.AddUserAccessToConnectionRegkey
start AddUserAccessToConnectionRegkey.
AddUserAccessToConnectionRegkey failed due to error : System.ArgumentException: Mobile Device Extension doesn't support WID.
Parameter name: connectionString
   at Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.VerifyConnectionString(String connectionString)
   at Microsoft.Adrms.MobileDeviceExtensions.CA.CustomActions.AddUserAccessToConnectionRegkey(Session session)```

Last time I reported this issue I was told to ask on Yammer, but nobody from Microsoft responded so I am back here - if you can provide me with the proper support place I can ask there

**Comment by batamig** [comment]
Hi @catmanjan sorry to hear you didn't get a response on yammer.
The article you're referring to resides in an area called "previous versions", which is for docs on products and product versions that are already out of support.

You can also try any of the support contacts listed in our docs here: [Support options and community resources](https://docs.microsoft.com/azure/information-protection/information-support#support-options-and-community-resources)

I'm closing this issue for now, but feel free to continue commenting as needed.
#please-close
