### ISSUE TITLE
EnableLoggingAuditEventsToEventLog - Dword or string

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#1378]
EnableLoggingAuditEventsToEventLog is registry entry but no clarity on type.
confirm type 
dword or string?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d71431-d9ab-e0f1-decf-9050d2cf174a
* Version Independent ID: 402e3264-3761-de41-18c4-3bb12eecdadc
* Content: [Azure Information Protection unified labeling client files and usage logging](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-files-and-logging#client-side-usage-logging-public-preview)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @bakerm00 - thanks for opening this issue! The answer is that this is a DWORD registry key, and we'll be adding this to the docs shortly.
I'm closing this issue for now, but feel free to continue commenting as needed.
We appreciate your contribution to Microsoft docs!
#please-close
