### ISSUE TITLE
wrong contents

### ISSUE THREAD

**Issue by shikanem** [MicrosoftDocs/Azure-RMSDocs#1379]
[Enter feedback here]

The statement that customers with Premier Support request from the Services Hub is incorrect.
If you actually select Azure Information Protection from the Services Hub, you will be directed to this Docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ba68bca-ce18-9eed-3ead-05a52ccfbd49
* Version Independent ID: 212526ff-d6c8-ab87-c218-dac87152c7f1
* Content: [Information & support for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/information-support)
* Content Source: [Azure-RMSDocs/information-support.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/information-support.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @shikanem, thanks for getting in touch.
To find out more about how to submit support requests, please see [Get support](https://docs.microsoft.com/en-us/microsoft-365/business-video/get-help-support?view=o365-worldwide).

I'm going to close this issue, but you can feel free to continue commenting if you have more feedback.
We appreciate your contributions to Microsoft docs!
#please-close
