### ISSUE TITLE
Documentation incorrect

### ISSUE THREAD

**Issue by Noparz** [MicrosoftDocs/Azure-RMSDocs#1381]
the steps detailed under https://docs.microsoft.com/en-us/azure/information-protection/activate-service#supported-activation-methods are incorrect. When one goes to the portal it redirects to this document stating the steps has changed, but the doc does not reflect it.

in addition the powershell provided does not work, below is what has worked consistently. 

# this section disables the old version, if it is still active and causing problems
Set-IRMConfiguration -AzureRMSLicensingEnabled $false -InternalLicensingEnabled $false -RMSOnlineKeySharingLocation $null -Force -Confirm:$false;

# this section enables the new IRM config. 
Set-IRMConfiguration -AzureRMSLicensingEnabled $true -InternalLicensingEnabled $true;

**Comment by batamig** [comment]
Hi @Noparz, thanks for getting in touch!
I'm going to take your comments back to the team and verify the update before fixing the doc.
In the meantime, I'm closing this issue as it's now in our backlog, but feel free to add more comments if you have additional input.

We appreciate your contribution to docs!
#please-close
