### ISSUE TITLE
'Additional requirements per client' does not clearly state if unified AIP client installation on the client machines is necessary?. 

### ISSUE THREAD

**Issue by ranabanerjee15** [MicrosoftDocs/Azure-RMSDocs#1382]
under the section **Additional requirements per client** it is not clearly mentioned if the unified client is required to be installed on the client machine and what will be the difference if it is installed or not installed ?. it further links to the section specific to client installation related requirements.

Please clarify if it is a requirement by the client Operating system ? and what difference would it make if the unified client is not installed ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ranabanerjee15, 
Thanks for sending your question to Microsoft docs!
The AIP unified labeling client must be installed on any machine where you want to use AIP unified labeling features.
To understand what's supported by built-in labeling vs AIP, you can compare the clients at [The client side of Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client).

We'll take another look at this page to understand how we can clarify this for our users. 
I'm going to close this issue in the meantime, but feel free to tag me in any additional comments you may have.

I can also recommend the community resources at our yammer group: https://www.yammer.com/AskIPTeam

Thanks for contributing to docs!
#please-close
