### ISSUE TITLE
AIP unified client logging

### ISSUE THREAD

**Issue by Afsars12** [MicrosoftDocs/Azure-RMSDocs#1384]
[Enter feedback here]
Hi Team,

How can we determine, which policies are being applied in client logs of the unified client? Also how to enable the AIP event logs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a0638e6-3711-42a6-ada9-5939060de772
* Version Independent ID: 42c396a5-f378-8a8e-bc84-cee5307d56de
* Content: [Azure Information Protection classic client files and usage logging](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-files-and-logging)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-files-and-logging.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Afsars12 thanks for sending your question to docs! 

I'm not sure that the Azure Information Protection reports have any details about the specific policy being applied, as that's on the Microsoft 365 side.

I'm going to check back with the team just in case though and will update the docs if there's something we've missed there. 
In the meantime, I recommend that you also ask your question on our yammer group at: https://www.yammer.com/askipteam/, where we have a wonderful community of experts. 

I'm going to close this issue for now, but feel free to continue commenting if you have more feedback.
Thanks for your contribution to Microsoft docs!

#please-close

**Comment by batamig** [comment]
@Afsars12 - one more point, I see that you can view the DLP policy applied in the Microsoft 365 activity explorer.
Check there for your policy information - it might be listed there as well. 
For more information, see:

- [Labeling activities that are available in Activity explorer](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer-available-events)
- [Get started with activity explorer](https://docs.microsoft.com/en-us/microsoft-365/compliance/data-classification-activity-explorer)

Hope that helps - good luck!
