### ISSUE TITLE
 Microsoft 365 Compliance Licensing Comparison spreadsheet 

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/Azure-RMSDocs#1385]
Hi Team, the  Microsoft 365 Compliance Licensing Comparison spreadsheet link is dead and it is much needed for licensing discussions: https://docs.microsoft.com/en-us/azure/information-protection/requirements#subscription-for-azure-information-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @rtrigueiro thanks for bringing our attention to this! I'm going to remove this broken link for now. 

Generally we have been sending users to the [service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection) for licensing details. If this spreadsheet was valuable to you, I'll pass that back on to the team for more details, and will add a new link back when we have it.

I can also recommend that you post this feedback as a question on our yammer group, where there are experts available to answer questions like these. See https://www.yammer.com/askipteam/.

I'm going to close this issue for now, but feel free to continue commenting here if you have more feedback.
Thanks for your contributions to docs!
#please-close

**Comment by batamig** [comment]
Hi @rtrigueiro,
The response I got from our focal points on licensing is that these are the two resources with up-to-date and relevant information:

- https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#information-protection

- https://go.microsoft.com/fwlink/?linkid=2139145

Hope these help, and again - thank you for your feedback.
