### ISSUE TITLE
Turn on usage logging

### ISSUE THREAD

**Issue by Afsars12** [MicrosoftDocs/Azure-RMSDocs#1388]
Hi Team,

In this document, there are instructions to turn on usage logging. It is mentioned to turn on support for usage logging for both the unified labeling client and scanner, set the registry key as follows:

Registry path: HKEY_CURRENT_USER\SOFTWARE\Microsoft\MSIP\EnableLoggingAuditEventsToEventLog
Type: DWORD
Value: 1

I have configured the registry as mentioned above.

![image](https://user-images.githubusercontent.com/50680948/127904754-7c8ad9bb-e21a-4185-af23-a1ddbcc5f5d2.png)

However not getting any events in the event viewer.  Kindly provide the instructions on how to configure and get the events in client-side usage logging.

![image](https://user-images.githubusercontent.com/50680948/127905053-236ef42e-73e0-4363-900e-71c607dc4136.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05d71431-d9ab-e0f1-decf-9050d2cf174a
* Version Independent ID: 402e3264-3761-de41-18c4-3bb12eecdadc
* Content: [Azure Information Protection unified labeling client files and usage logging](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-files-and-logging)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-files-and-logging.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Afsars12, thanks for sending your question in to docs.
I'm checking with the dev team to see whether there are any steps missing and will update the page as needed in a coming publish.

In the meantime, if this issue persists, please open a support ticket. You can find information about how to do that here: [To contact Microsoft support](https://docs.microsoft.com/en-us/azure/information-protection/information-support#to-contact-microsoft-support)

I'm going to close this issue in the meantime, but feel free to continue commenting if you have more feedback. I'll also come back here and update the issue when we have a definitive answer about the doc update. 

Thanks for contributing to docs!
#please-close

**Comment by batamig** [comment]
Hi @Afsars12, we checked with the engineering team, and the instructions here are correct.

Please check that you have the latest version of the Azure Information Protection client installed - you can see here for details: [Version 2.12.62.0](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#version-212620) and the [Microsoft Download Center](https://www.microsoft.com/en-us/download/details.aspx?id=53018).

If the issue persists, please open a support ticket.
Thanks!
