### ISSUE TITLE
[LOC]Unnecessary asterisks are displayed (ja-jp) 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/Azure-RMSDocs#1390]
ja-jp:"https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#version-291110"
![unifiedlabelingclient-version-release-history_j](https://user-images.githubusercontent.com/40815708/128634675-df1305c9-5f21-4566-982c-cedbb9c27cce.png)

en-us:"https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#version-291110"
![unifiedlabelingclient-version-release-history_e](https://user-images.githubusercontent.com/40815708/128634681-0dc2218b-bdcd-4658-9581-eaa78e026000.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [What's new in Azure Information Protection (AIP) - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @hyoshioka0128 - thanks for sending this issue into docs! 
We've added it to our localization team's backlog, and it should get updated in a coming publish.

I'm going to close this issue for now, but feel free to continue commenting if you have additional feedback.
We appreciate your contribution to Microsoft docs!
#please-close

**Comment by batamig** [comment]
Hi @hyoshioka0128, I wanted to come back and update you, as we've been notified that this fix will not be made at this time.
This article is machine translated, and as the error doesn't impact readiness, it doesn't currently make the criteria for fixes. 

We appreciate your input on docs, and always welcome feedback and contributions from our users.

**Comment by hyoshioka0128** [comment]
@batamig - Thanks for notifications.
