### ISSUE TITLE
HORRIBLE this page is just HORRIBLE!

### ISSUE THREAD

**Issue by ncollins64** [MicrosoftDocs/Azure-RMSDocs#1392]
For people with COGNITIVE DISORDERS you sure make it difficult to get ANYTHING COMPELTED... the prompts the security the time wasted is all a JOKE to you all - Your leaders dont take into affect that we all are not created equal but we do have the ability to treat one another as though we DO - this is the way to fix the issue!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d01ed44-c873-ea84-0fda-44ea8ab13409
* Version Independent ID: 4b005dc9-5456-1229-4346-62f1c6147dfc
* Content: [View protected files with the Azure Information Protection classic client viewer](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-view-use-files#prompts-for-authentication)
* Content Source: [Azure-RMSDocs/rms-client/client-view-use-files.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-view-use-files.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @ncollins64, thanks for opening a GitHub issue on Microsoft docs.
The page that you linked from is relevant only for the *classic* version of the Azure Information Protection client, which was deprecated back in March 2021. For more information about the deprecation, see our blog at: https://techcommunity.microsoft.com/t5/security-compliance-and-identity/azure-aip-portal-label-amp-policy-management-admin-experience/ba-p/2182678

We're continuing to keep this page live for any customers who have extended support. Are you using extended support, and is there something specific that you were looking for here and couldn't find?

If you're looking for the parallel page for the unified labeling client, which is the main version available now, please see here instead: https://docs.microsoft.com/azure/information-protection/rms-client/clientv2-view-use-files

We always appreciate hearing feedback from our users.
Thanks!

**Comment by batamig** [comment]
Hi @ncollins64, thanks for opening a GitHub issue on Microsoft docs.
The page that you linked from is relevant only for the *classic* version of the Azure Information Protection client, which was deprecated back in March 2021. For more information about the deprecation, see our blog at : https://techcommunity.microsoft.com/t5/security-compliance-and-identity/azure-aip-portal-label-amp-policy-management-admin-experience/ba-p/2182678

We're continuing to keep this page live for any customers who have extended support. Are you using extended support, and is there something specific that you were looking for here and couldn't find?

If you're looking for the parallel page for the unified labeling client, which is the main version available now, please see here instead: https://docs.microsoft.com/azure/information-protection/rms-client/clientv2-view-use-files

We always appreciate hearing feedback from our users.
Thanks!

**Comment by batamig** [comment]
Hi @ncollins64 - I haven't seen any updates on this issue, so I'm going to close it for now.

You can still feel free to add any additional comments or feedback you may have. 

#please-close
