### ISSUE TITLE
Next step links are broken

### ISSUE THREAD

**Issue by vikashsonar** [MicrosoftDocs/Azure-RMSDocs#1393]
[Enter feedback here]

Looks like the links for following are broken
File SDK profile concepts
File SDK engine concepts
Policy SDK profile concepts
Policy SDK engine concepts
Protection SDK profile concepts
Protection SDK engine concepts

Every link takes you to single page.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c569a6a-6adb-5d61-c6b2-25044804f9ce
* Version Independent ID: be504a2e-d786-2add-2f2f-74a1620c5abf
* Content: [Concepts - The core concepts in the MIP SDK - Profile and Engine](https://docs.microsoft.com/en-us/information-protection/develop/concept-profile-engine-cpp)
* Content Source: [mip/develop/concept-profile-engine-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @vikashsonar - thanks for sending your comment in to docs!

I'm going to tag some other focal points for this doc - @msmbaldwin, @tommoser, can one of you take a look at these links and see what updates are needed?

**Comment by tommoser** [comment]
Thanks! Fixed in PR: https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4534

**Comment by batamig** [comment]
Hi - thanks @tommoser!
I'm closing this issue for now. @vikashsonar, please feel free to continue commenting as needed. Thank you for your contribution to docs!
#please-close
