### ISSUE TITLE
Doesn't Azure Information Protection administrator role support Track and Revoke

### ISSUE THREAD

**Issue by hideyukiw** [MicrosoftDocs/Azure-RMSDocs#1394]
Hi Teams,

This page states that Track and Revoke is not supported in Azure Information Protection Administrator(AIP Admin).

> This role doesn't support tracking and revoking documents for users, and is not supported in the Azure portal if your tenant is on the unified labeling platform.

However, this page (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/track-and-revoke-admin) says that AIP Admin can run Track and Revoke.

The FAQ seems to be outdated as far as the actual behavior is concerned.
Is it possible to correct it if necessary?

Compliance administrator or Compliance data administrator also have the same description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0547cf-7694-72e8-1c35-05502fc18233
* Version Independent ID: 3bdb8088-8d87-32aa-6252-f3f9c4944adc
* Content: [FAQs for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/faqs)
* Content Source: [Azure-RMSDocs/faqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @hideyukiw - thank you for this! Indeed, the AIP Admin is supported for track and revoke, and we'll be fixing this on the FAQ page in a coming publish.

I'm going to close this issue for now, but feel free commenting here if you have more feedback.
Thanks for your contribution to docs!

#please-close
