### ISSUE TITLE
Details missing on how assigning usage rights and access controls to external groups works

### ISSUE THREAD

**Issue by NileshGhodekar** [MicrosoftDocs/Azure-RMSDocs#1396]
The section on this page "Assigning usage rights and access controls to external groups" has following statement:

"In addition to using the Azure AD proxyAddresses for groups in your tenant, Azure Information Protection also uses this attribute in the same way to authorize groups from another tenant."

Need more details on how exactly this works. It seems that AIP service in one tenant is able to read this information on a group from any other tenant. If that is the case, this seems to be a potential privacy, security and trust concern and departure from the guarantee of consent, control and isolation in a multi-tenant environment. A technical deep dive description of how this work would help to mitigate these concerns.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5223b524-019d-7431-6382-a33d3a104840
* Version Independent ID: d8cb57fa-6b0e-a20d-c34d-f0a54f58cab8
* Content: [Prepare users and groups for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/prepare#assigning-usage-rights-and-access-controls-to-external-groups)
* Content Source: [Azure-RMSDocs/prepare.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/prepare.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @NileshGhodekar - thanks for sending your question into docs!

Before I reply, I'm going to check with the team to make sure we get the exact information out to you.
Please know that we're working on this, I'll update the issue here when we get the response and will also update the article as needed in a coming publish.

**Comment by batamig** [comment]
Hi @NileshGhodekar,

After discussing with the team, I can confirm that the information you're concerned about is not shared. 

We appreciate your suggestion to add a deeper dive. To get earlier clarification, please open a support case or check to see if our community resources are helpful.

You can find more information about those options here: [Support options and community resources](https://docs.microsoft.com/azure/information-protection/information-support#support-options-and-community-resources). 

I'm going to close this issue for now, but feel free to continue commenting as needed! 
Thanks for your contributions to docs.
#please-close
