### ISSUE TITLE
Wrong URL for "Import-AIPServiceTemplate"

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/Azure-RMSDocs#1398]
Hi,

within the section [https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase2#procedure-if-you-created-custom-templates-before-the-migration](url) the Link to "Import-AIPServiceTemplate" has the wrong URL Target. Correct would be [https://docs.microsoft.com/en-us/powershell/module/aipservice/import-aipservicetemplate?view=azureipps](url).
Currently the link has the correct text, but wrong link. Please change the URL that it matches the link text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 541db35d-3017-8b5d-b8bd-0cedbfb17661
* Version Independent ID: a4506005-f24e-fc79-f1c3-7bc43b549d32
* Content: [Migrate AD RMS-Azure Information Protection - Phase 2](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase2)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase2.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase2.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @myfope - thanks for giving us a heads up on this! We're fixing this now and it should be updated live shortly. 

I'm closing this in the meantime, but feel free to continue commenting here as needed.
We appreciate your contribution to Microsoft Docs!

#please-close
