### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by shigerin** [MicrosoftDocs/Azure-RMSDocs#1399]
[Enter feedback here]
mipContext = MIP.CreateMipContext(mipConfiguration); →Error
MipContext mipContext = MIP.CreateMipContext(mipConfiguration); →OK

mipContext.Shutdown(); →Error
mipContext.ShutDown(); →OK

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0261682a-a7cb-7362-4386-4fc77975ebf6
* Version Independent ID: 4ddc7104-90e0-1468-22b9-9b96344aa205
* Content: [Quickstart - Initialization for Microsoft Information Protection (MIP) SDK C# clients](https://docs.microsoft.com/en-us/information-protection/develop/quick-app-initialization-csharp)
* Content Source: [mip/develop/quick-app-initialization-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-app-initialization-csharp.md)
* Service: **information-protection**
* GitHub Login: @tommoser
* Microsoft Alias: **tommos**

**Comment by batamig** [comment]
Hi @shigerin, thanks for sending your comment in to docs!
I'm going to tag the author here for more details - @tommoser, can you take a look at this one? Thanks!

**Comment by tommoser** [comment]
Thanks! Fixed in PR: https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4534

**Comment by batamig** [comment]
Hi - thanks @tommoser!
I'm closing this issue for now. @shigerin, please feel free to continue commenting as needed. Thank you for your contribution to docs!
#please-close
