### ISSUE TITLE
DNS redirection requires the old server to remain online

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/Azure-RMSDocs#1400]
Hello , please add here this important fact / note :

https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#step-7-reconfigure-windows-computers-to-use-azure-information-protection
https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#client-reconfiguration-by-using-dns-redirection

Using "client reconfiguration using dns" requires that the old ARMS cluster will remain online because the mechanism is based on providing "access denied" on a specific url and IIS service must be running. 

Please consider removing "Simplest and preferred method" because it's simple but not preferred because it doesn't target the decommission of on-prem servers.

Thanks

Daniele Bona
dabona@microsoft.com
Security Pfe/Ce

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0d29ee-00b5-5a48-b259-d62e75c22d05
* Version Independent ID: 8c6632dc-5926-a431-7f7b-f3f2469170f6
* Content: [Migrate AD RMS-Azure Information Protection - Phase 3](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase3.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase3.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @dbona75 - thanks for sending your suggestion. 

I'll just check this with the team before we make any updates to these pages. I'm also going to close this for now while we verify, but feel free to continue commenting as needed.
We appreciate your contribution to docs!

#please-close

**Comment by dbona75** [comment]
After reviewing the infrastructure in my Lab,  I can confirm  it is possible to completely decommission the OLD ADRMS cluster using DNS Redirection method.
I am investigating what was preventing to work (probably the SRV record was not well propagated). 

Starting yesterday everything worked as expected. 

So I correct myself : the requirement of access denied in the old ADRMS IIS is needed only if you want to have both infrastructures running and pilot users using which.

Please close

**Comment by dbona75** [comment]
Hello,

After reviewing the infrastructure in my Lab,  I can confirm  it is possible to completely decommission the OLD ADRMS cluster using DNS Redirection method.
I am investigating what was preventing to work (probably the SRV record was not well propagated).

Starting yesterday everything worked as expected.

So I correct myself : the requirement of access denied in the old ADRMS IIS is needed only if you want to have both infrastructures running and pilot users using which.

The document is ok.

Please close


Thanks

Da: Batami Gold ***@***.***>
Inviato: martedì 14 settembre 2021 08:18
A: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Daniele Bona ***@***.***>; Mention ***@***.***>
Oggetto: Re: [MicrosoftDocs/Azure-RMSDocs] DNS redirection requires the old server to remain online (#1400)


Hi @dbona75<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdbona75&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C8c08a065ddec4156d77308d9774757f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671970597245490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y%2FgOpyFdWo6PZxxw91fjaH98IVI1uYABGRZDrybp5wk%3D&reserved=0> - thanks for sending your suggestion.

I'll just check this with the team before we make any updates to these pages. I'm also going to close this for now while we verify, but feel free to continue commenting as needed.
We appreciate your contribution to docs!

#please-close

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FAzure-RMSDocs%2Fissues%2F1400%23issuecomment-918842313&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C8c08a065ddec4156d77308d9774757f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671970597245490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2B0IqPbWbiSZmd2XCb5GJLR7l%2B1i%2Fz9mekXilWSTmNCk%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQCECSDQP2DWDQRU2ND7Q4LUB3SH5ANCNFSM5D3BYAAQ&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C8c08a065ddec4156d77308d9774757f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671970597255485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RtJ%2FUj60SEXpcmOKicxU3xMLv75hzgAftlIU0tAVRlk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C8c08a065ddec4156d77308d9774757f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671970597265476%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=k8lfn%2BA6GK6zeA8tCz6NnK9WjFNqRPnoMktAnKz%2FX4I%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cdaniele.bona%40microsoft.com%7C8c08a065ddec4156d77308d9774757f2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637671970597265476%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=C6YhL5iBr%2FtKRjxBPDwi6QQT2zTBlu6o%2FLNa57%2FZpew%3D&reserved=0>.

**Comment by PRMerger18** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.
