### ISSUE TITLE
ADRMS can't be deprovisioned if you opted for Client reconfiguration using DNS redirection 

### ISSUE THREAD

**Issue by dbona75** [MicrosoftDocs/Azure-RMSDocs#1401]
[Enter feedback here]

Hello, please add this precious information here : 

 https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase5#step-10-deprovision-ad-rms

The point is :  If you used Client reconfiguration using DNS redirection 
https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3#client-reconfiguration-by-using-dns-redirection
the ADRMS can't be deprovisioned because the old service must respond to the clients with access denied to make them routed to AIP service

Indeed this is the behavior described during phase 3 :
"To confirm this configuration is working as expected, try to connect to the licensing.asmx file directly from a browser. You should see the following error message, which triggers the client running Microsoft 365 apps or Office 2019 or Office 2016 to look for the SRV record:

Error message 401.3: You do not have permissions to view this directory or page using the credentials you supplied (access denied due to Access Control Lists)."

Daniele Bona
dabona@microsoft.com
GTT Global Technology Team - Security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 591da5d0-4f5f-a929-c9dc-62aef2f64121
* Version Independent ID: fcf5fd4b-36b7-4837-8ba0-dd2cc3616181
* Content: [Migrate AD RMS-Azure Information Protection - Phase 5](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase5)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase5.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase5.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @dbona75 - thanks for sending your suggestion. 

I'll just check this with the team before we make any updates to these pages. I'm also going to close this for now while we verify, but feel free to continue commenting as needed.
We appreciate your contribution to docs!

#please-close

**Comment by dbona75** [comment]
After reviewing the infrastructure in my Lab,  I can confirm  it is possible to completely decommission the OLD ADRMS cluster using DNS Redirection method.
I am investigating what was preventing to work (probably the SRV record was not well propagated). 

Starting yesterday everything worked as expected. 

So I correct myself : the requirement of access denied in the old ADRMS IIS is needed only if you want to have both infrastructures running and pilot users using which.

The document is ok.

Please close
