### ISSUE TITLE
Page does not specify data sources included

### ISSUE THREAD

**Issue by acruz2021** [MicrosoftDocs/Azure-RMSDocs#1402]
I work as support engineer within Microsoft. A customer requested that the page be updated to display that the Azure Information Protection analytics part, the one that is used on the Sentinel's data connector only holds data for labeling on desktop applications. As it does not make the statement that other data seen in the compliance portal will not be stored there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Analytics and central reporting for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip#how-to-modify-the-reports-and-create-custom-queries)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @acruz2021, thanks for forwarding this request.
The [Audit log reference page](https://docs.microsoft.com/en-us/azure/information-protection/audit-logs) does list the platform and application for each log generated. Would that help this customer?

**Comment by acruz2021** [comment]
Hi @batamig thanks for reaching out. 
That reference works and doesn't at the same time. Let me expand a little bit.
I'm from the Sentinel team. The request comes from one specific customer, but we keep getting customers being "mislead" expecting that log types from any platform will be ingested into their log analytics workspace. When in fact, it is only logs from the desktop versions that are ingested to the Log Analytics workspace. So, the request is really to have the documentation explain the limitation that the data ingestion to LAW is only from desktop apps.
The Audit log reference page mentions that for most logs apply both: windows and cloud versions. So, it does not work as to limit what data can be ingested into Log Analytics workspace.
Hope this makes it clearer. Thanks in advanced.

**Comment by batamig** [comment]
Hi @acruz2021 thanks for your patience while we get back to this.
We're considering adding the following note to the top of the audit log reference page:

> Note:
> Azure Information Protection collects data from desktop apps only, and not from mobile devices.
> For more information, see the details in the **Platform** columns in this article.

Do you think this would suffice? Thanks

**Comment by acruz2021** [comment]
Thanks!
I think it works as to limit their expectations.

Thanks again,
Alejandro
