### ISSUE TITLE
 Get-AipServiceUserLog -fordate out by one bug

### ISSUE THREAD

**Issue by shane-m1** [MicrosoftDocs/Azure-RMSDocs#1403]
[Enter feedback here]
The module has an error:
 Get-AipServiceUserLog

You specify -fordate and the date needs to be one day greater than you're requesting. If I request the 18th, the module returns data for the 17th.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600cf5db-0c6e-b14e-8d86-5ae5df551d6d
* Version Independent ID: ee9b0706-7f66-3537-a74f-779066357621
* Content: [Log & analyze the protection usage from Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/log-analyze-usage)
* Content Source: [Azure-RMSDocs/log-analyze-usage.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/log-analyze-usage.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @shane-m1, thanks for sending your comments!

We're just confirming this with the team, and then will make any updates required both here and in the [PowerShell page](https://docs.microsoft.com/powershell/module/aipservice/get-aipserviceuserlog).

I'm going to close this issue for now while we work through the verification, but feel free to continue commenting as needed.

We appreciate your contribution to docs!
#please-close

**Comment by batamig** [comment]
Hi @shane-m1, 
Returning to your request here, I got this response from the team:

Please check with the user whether they're using UTC offset time while specifying the -ForDate. By default, the time specified will be converted to UTC, with an offset used based on the current time zone. The query is executed as data is stored in UTC.  
Please ask the user to check example 3 & 4 and accordingly add offset in PowerShell query to make it work.

This may help your issue. I understand that this functionality is common to all of our PowerShell cmdlets. If this isn't clear in our general PowerShell documentation, we'll look for how we can clarify. 
Thanks!
