### ISSUE TITLE
Ignite links don't allow access

### ISSUE THREAD

**Issue by chrisweis** [MicrosoftDocs/Azure-RMSDocs#1404]
Hello,

When I try to navigate to the Ignite links in this page I get "Looks like you are not authorized to access MyIgnite."  I suggest either updating the links to be public content or removing them.

Thanks,
Chris
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @chrisweis, thank you for this!
I've updated these links to the archived addresses, as this content is indeed still available.
Registration is also open for Ignite 2021! Find out more here: https://myignite.microsoft.com/home

We appreciate your contribution to docs!
