### ISSUE TITLE
Labelling SharePoint Online documents (without E3/E5 license which has automatic labelling)

### ISSUE THREAD

**Issue by wtfiwtz** [MicrosoftDocs/Azure-RMSDocs#1410]
To manually label O365 **SharePoint Online** documents in bulk, I had to follow these steps which weren't really documented anywhere I could find...

Previous attempts at labelling in SPO: https://answers.microsoft.com/en-us/msoffice/forum/all/sensitivity-label-in-sharepoint/c2f48dac-a4f7-4d8d-ba52-cb166c78a149

1. Install Unified Labelling client for Windows

2. `Install-Module AipService` (as Administrator in PowerShell)

3. Run the following PowerShell

```powershell
cd "C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell\AzureInformationProtection\"
import-module .\AzureInformationProtection.psd1
Connect-AipService
<login as domain admin>
Set-AipAuthentication
<login as normal user>

# syncs down the OneDrive files (using your normal O365 account)
Get-ChildItem "C:\users\Admin\<OneDrive Path>\<Doc Library Path>" -File -Recurse -Exclude *.msg,*.pdf | Get-AIPFileStatus | where {$_.IsLabeled -eq $False} 

# applies label to docs in Doc Library without labels
Get-ChildItem "C:\users\Admin\<OneDrive Path>\<Doc Library Path>" -File -Recurse -Exclude *.msg,*.pdf | Get-AIPFileStatus | where {$_.IsLabeled -eq $False} | Set-AIPFileLabel -LabelId <Label GUID> -PreserveFileDetails
```

You definitely can't use SharePoint Online paths directly (only for on-premise versions of SharePoint) and WebDAV mapped drives (via Internet Explorer 11 Trusted Sites) doesn't work either.

I'm running this from an Azure server in the cloud so I don't have to sync down the entire SharePoint Online set of documents

Hope this helps someone else!

Cheers,
Nigel

**Comment by batamig** [comment]
Thanks so much for the feedback @wtfiwtz! We're going to take this back to the team and see if we can clarify our docs here with your comments.

I'm going to close this issue in the meantime, but feel free to continue commenting if you have anything else to add. 
Thanks for contributing to docs!
#please-close
