### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/Azure-RMSDocs#1413]
Current page has

"The File, Profile, and Protection SDK engines provide an interface for operations performed **on by** a specific identity."

Likely "on" should be removed there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c569a6a-6adb-5d61-c6b2-25044804f9ce
* Version Independent ID: be504a2e-d786-2add-2f2f-74a1620c5abf
* Content: [Concepts - The core concepts in the MIP SDK - Profile and Engine](https://docs.microsoft.com/en-us/information-protection/develop/concept-profile-engine-cpp)
* Content Source: [mip/develop/concept-profile-engine-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @cdietschrun, thanks for writing into docs!
Since you have a PR on this item, I'm going to close this issue and to enable any further comments to happen on the PR itself.
We appreciate your contributions!

#please-close
