### ISSUE TITLE
Reorder the delegated examples

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/Azure-RMSDocs#1415]
The page's examples for the Protection SDK are, in order:

.NET-delegated publish
.NET-delegated consume
C++-delegated consume
C++-delegated publish

The C++ examples should also be publish, then consume for symmetry. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba062633-b05b-8f3f-adda-54e5fa296dde
* Version Independent ID: e405e510-20d8-95f3-e477-fb676fc59fda
* Content: [Concepts - Delegation](https://docs.microsoft.com/en-us/information-protection/develop/concept-delegation)
* Content Source: [mip/develop/concept-delegation.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-delegation.md)
* Service: **information-protection**
* GitHub Login: @tommoser
* Microsoft Alias: **tommos**

**Comment by batamig** [comment]
Hi @cdietschrun, thanks for writing into docs!
Since you have a PR on this item, I'm going to close this issue and to enable any further comments to happen on the PR itself. 
We appreciate your contributions!

#please-close
