### ISSUE TITLE
Confusing example metadata

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/Azure-RMSDocs#1416]
The file metadata must be intact. This metadata includes:
Attribute1
Attribute2

Is that list of metadata accurate? Or a placeholder?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 343a5700-26c0-fc29-2aa5-aedcd5b2208e
* Version Independent ID: e9a91815-5186-dac8-6bcb-6a61a794c960
* Content: [Concepts - File handlers in the MIP SDK.](https://docs.microsoft.com/en-us/information-protection/develop/concept-handler-file-cpp)
* Content Source: [mip/develop/concept-handler-file-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-handler-file-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @cdietschrun, thanks for writing in to docs!
I'm tagging other focal points on our team. @tommoser  and @msmbaldwin, can you take a look? Thanks!

**Comment by batamig** [comment]
Hi - updating to tag a current content owner to address
@aashishr, can you advise?

**Comment by aashishr** [comment]
@Krishna ***@***.***> - can you look into this?

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
