### ISSUE TITLE
Error in syntax for PowerShell

### ISSUE THREAD

**Issue by davidguest44** [MicrosoftDocs/Azure-RMSDocs#1418]
In the section "Customize Outlook popup messages" there is a piece that shows:

<Key> is a name for your rule. Use the following syntax, where <#> is the serial number for your rule:

OutlookCollaborationRule_<x>

The note in the text suggests that <#> should be used but the example uses <x>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @davidguest44,
Thanks for writing into docs! The syntax shown is only meant as an example - you're meant to replace the <#> with the actual serial number. 
But you are correct- this is a doc bug in consistency, and I'm updating it now. 

I'm closing this issue for now, but feel free to continue commenting if you have more feedback.
We appreciate your contribution to docs!
#please-close
