### ISSUE TITLE
This page mentions AIP and Documents

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/Azure-RMSDocs#1419]
Do emails have the ability to track who looks at them but not revoke.  And if I can track who looks at a email how can I do this.  Or are emails excluded from all of these features?

I'm a little confused because they all have to reach back out to Microsoft so I'm confused why this is not provided, my spidy sense says Microsoft doesn't want to do all that because of the volume of email, which I get.  Just want to verify so I can check my box off.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179f78bb-2202-5c69-16ec-28f544f7676c
* Version Independent ID: b6a6ebe6-3ce9-9cff-84c3-484479afe7d4
* Content: [Track and revoke access - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/track-and-revoke-admin)
* Content Source: [Azure-RMSDocs/rms-client/track-and-revoke-admin.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/track-and-revoke-admin.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @SquirrelAssassin! I'm going to check back with the team on this one to make sure before I reply - but I wanted to let you know that we're on it.

Thanks for writing into docs! I'll update here when I have more details.

**Comment by batamig** [comment]
Hi - coming back to confirm that track and revoke is supported for Office documents only - tracking access to emails is not supported.

I'm closing this issue now, but feel free to add more comments as needed. Thanks again for writing into docs!
#please-close
