### ISSUE TITLE
external users

### ISSUE THREAD

**Issue by SquirrelAssassin** [MicrosoftDocs/Azure-RMSDocs#1420]
If I make a distribution group .... add in external users to that group .. does it work.  If it does work ... what if later I add another user from the external company to that group.   Someone from said external company forwards the new person a email ... can they still open it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5223b524-019d-7431-6382-a33d3a104840
* Version Independent ID: d8cb57fa-6b0e-a20d-c34d-f0a54f58cab8
* Content: [Prepare users and groups for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/prepare)
* Content Source: [Azure-RMSDocs/prepare.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/prepare.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @SquirrelAssassin, thanks for writing into docs!
I'm going to check back with the team on this one before I give you a final answer, but I wanted to let you know that we're on it!
I'll comment back here again when I have more information.

**Comment by batamig** [comment]
Hi @SquirrelAssassin, I got some answers for you, which I'll list below. I'm going to close this issue while we see if we can clarify the docs any further, especially on the last point, but feel free to continue commenting if you have any additional feedback.

Thanks for your contributions to docs!

Some questions answered:

- Can you add external users to a group [add Joe to MyGroup]? **Yes**. You have to invite external members though. For more info, see https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-groups-members-azure-portal

- Can this group with an external user be used with RMS [use MyGroup in a template and protect document called ProjectPhoenix.docx]? **Yes**. The group can be part of the PL directly or through a template. Either way, on consumption, the group will be expanded and we’ll verify if the external user is part of the group and therefore has access to the content or not.

- Can this group be updated with more external users [add Moe to MyGroup]? Yes. This is standard AAD group management

- Can the new external user [Moe] open content that was protected [ProjectPhoenix.docx] with the group [MyGroup] before this user was added to the group? **Yes**. Standard group expansion. One little point: The RMS service caches the expanded members of an AAD group for up to 24 hours. So it’s possible that Moe is not updated in the RMS cache for 24 hours and in this time he cannot access content that this group has access to.

#please-close
