### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by speckles0** [MicrosoftDocs/Azure-RMSDocs#1421]
The article mentions "The remove protection capability is disabled by default and must first be enabled using the Set-LabelPolicy cmdlet." However the Set-LabelPolicy link is dead and goes to a 404 page: https://docs.microsoft.com/en-us/powershell/module/azureinformationprotection/set-labelpolicy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7383893-1714-4be5-a499-7f9463fab5e2
* Version Independent ID: f566dfdf-bbae-f671-f012-b5c71e40bf14
* Content: [Use PowerShell with the Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-powershell)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @speckles0! Thanks for sending your feedback into docs.
This description actually should go here, for a specific case only: [Custom configurations: Enable removal of protection from compressed files](https://docs.microsoft.com/azure/information-protection/rms-client/clientv2-admin-guide-customizations#enable-removal-of-protection-from-compressed-files)

I'm going to update this cross-reference, but also check back with the team to verify whether the ability to remove protection is disabled by default in *all* cases, or whether this is specific to the cases described in this section. 

I'm closing this issue in the meantime, as we're tracking it elsewhere. I hope this helps your situation - please feel free to continue commenting if you have additional feedback.

Thanks for your contributions to docs!
#please-close
