### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by Jawo78** [MicrosoftDocs/Azure-RMSDocs#1422]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50e4e884-2046-564b-8f7d-3cc3596e4a0d
* Version Independent ID: c85a4d22-5347-2d74-a08c-4370f4bb7d1b
* Content: [Classify & protect - Azure Information Protection unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-classify-protect)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-classify-protect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-classify-protect.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Jawo78 please provide more details about your feedback. I'm going to close this issue in the meantime, but we'd look forward to hearing your feedback, and you can feel free to continue commenting here as needed.

Thanks!
#please-close
