### ISSUE TITLE
MAC OS Versions

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/Azure-RMSDocs#1423]
This page is not really useful, if you are looking for compatible MAC clients and all you get is "Mountain Lion 10.8" without and information about newer versions.
 You should add an link to https://docs.microsoft.com/en-us/azure/information-protection/requirements-applications#macos-rms-enlightened-applications or add a description, that newer MacOS Clients are also supportet or that it is only a "office Question"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @FrankCarius!
Thanks for writing into docs. Indeed, this table only currently lists minimum versions, or specifically supported versions, and we could add references between all the requirement pages for more information. I'm adding that now as an item to update in a coming publish.

I'm also closing this issue in the meantime, as we're tracking it internally. Please feel free to continue commenting if you have any additional feedback.

We appreciate your contribution to Microsoft docs!
#please-close
