### ISSUE TITLE
AIP client information page missing the maintenance announcement

### ISSUE THREAD

**Issue by sanderdewit** [MicrosoftDocs/Azure-RMSDocs#1424]
Hi,

please include in this page, that the AIP UL client is in maintenance mode since 01-01-2022.
This will help customer focus on the built-in client as that is the only one to will be actively developed.
AIP UL client will only receive major bugfixes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-labeling-solutions-for-windows-computers)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @sanderdewit - thanks for writing into docs! Yes, updates about the maintenance mode are currently underway.
I'm going to close this issue for now as it's already an item in progress, but feel free to continue commenting here as needed.

We appreciate your feedback and contribution to docs!
#please-close
