### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by anushka499** [MicrosoftDocs/Azure-RMSDocs#1425]
[Enter feedback here]
Please tell how to get value where it's written user1@tenant.com. I have got tenant guid and application id but this value is a big issue for me. Please help

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b0a2b2-7502-f245-9d9b-4bf566633065
* Version Independent ID: f7f5635e-44ec-c1cc-ac35-2ecf57790248
* Content: [Quickstart - Set and get a sensitivity label on a file using the C# MIP SDK](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp)
* Content Source: [mip/develop/quick-file-set-get-label-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-set-get-label-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @anushka499, thanks for writing into docs!
I'm tagging the content editors on this page - @tommoser, can you address?

**Comment by batamig** [comment]
Hi - updating to tag a current content owner to address
@aashishr, can you advise?

**Comment by aashishr** [comment]
@Krishna ***@***.***> - can you look into this?

**Comment by tommoser** [comment]
@anushka499 user1@tenant.com is a placeholder for the user using your application. You need to implement a method in your application that forces the user to log in to know their mail address. This application has an example where it calls Microsoft Graph to get the user ID. 

https://github.com/Azure-Samples/MipSDK-File-Dotnet-Quickstart/tree/main/mip-sdk-dotnet-quickstart

Specifically, look at the AuthDelegateImplementation class: https://github.com/Azure-Samples/MipSDK-File-Dotnet-Quickstart/blob/main/mip-sdk-dotnet-quickstart/AuthDelegateImplementation.cs#L137

**Comment by krishnacloud123** [comment]
@tommoser  provided response to the @anushka499 and it addresses the question. The issue can be closed.

**Comment by msmbaldwin** [comment]
#please-close
