### ISSUE TITLE
Add VMWare Workspace ONE Boxer as RMS-enlightened application?

### ISSUE THREAD

**Issue by heikobischoff** [MicrosoftDocs/Azure-RMSDocs#1427]
Regarding to the documentation of VMWare, the Boxer app supports AIP features and should be added to RMS enlightened Android/iOS apps.

VMWare documentation:
https://docs.vmware.com/en/VMware-Workspace-ONE-UEM/services/Boxer_Admin_Guide/GUID-SecureEmailswithAIP.html

Can you double check that?
Thank you in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75a386a-bf8d-8eb2-8357-98ad613db056
* Version Independent ID: 002a6cae-93c8-c369-57a1-d75a591a75d7
* Content: [Application support for RMS data protection for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/requirements-applications)
* Content Source: [Azure-RMSDocs/requirements-applications.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements-applications.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @heikobischoff, thanks for sending this comment into docs!
Indeed, I'm going to double-check this before updating the article, and then will add it as needed in a coming publish.

I'm going to close this issue for now to prevent double-tracking, but feel free to continue commenting if you have more feedback.
We appreciate your contribution to docs!
#please-close
