### ISSUE TITLE
Is there any matrix that summarize all the file types Microsoft and non-Microsoft that can be inspected from SIT and AIP Scanner?

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/Azure-RMSDocs#1428]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044457bf-06a4-cc9e-3425-780a748c50ed
* Version Independent ID: 4e587393-64eb-4cd7-f2a6-e0e22e22a8bd
* Content: [File types supported by the Azure Information Protection (AIP) unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#file-types-supported-for-inspection)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @sergioandreslq, thanks for sending your question into docs!

The [page you're looking at](https://docs.microsoft.com/azure/information-protection/rms-client/clientv2-admin-guide-file-types) lists the types of supported files, so perhaps I don't understand your question.

The unified labeling client supports the same SITs as the Microsoft 365 sensitivity labels. You can see a list of those here:
[Sensitive information type entity definitions
](https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitive-information-type-entity-definitions)

Please add more details to your question so that I can help direct you to the correct answer. I'd also recommend posting in our Yammer group here: https://www.yammer.com/AskIPTeam#/home

**Comment by sergioandreslq** [comment]
Hi Batamig,

thanks for your quick answer, the question is associated with which kind of format file the SIT or AIP scanner is able to dig inside and identify that the file contains sensitive information.

i.e.: 
is SIT/AIP scanner able to dig inside a photoshop .psd document that contains SSN in as an image or text?

**Comment by sergioandreslq** [comment]
Hello Batamig, 

The question is the matrix associated that SIT or AIP Scanner is able to dig inside and bring up that that document contains sensitive information by default.


I have million of data generated from different software with different extension *.psd, *.pdf, *.html, *.py, *.jpg, *.bmp, *.png, *.zip, *.rar, *.msg, *.xml, *.log, *.odt, *.rtf, *wpd, *.cvs, *.tar, *.csv, *.mp4, *.WAV,  *.WMA, *.MPG, *.tif,*.AI, *.sql, *.db, *.aps, *.css, *.htm, *.htlml, *.php

https://fileinfo.com/filetypes/common#:~:text=Data%20Files%20%20%20%20Extension%20%20,Apple%20Keynote%20Presentation%20%209%20more%20rows%20

That file type format files are stored on: SPO, ODfB, EXO, NAS, On-premise File Share. 

by default what are the files that the tools from Microsoft classification will inspect and show in the report from content explorer or Azure Information protection portal?

The idea is to see if you have a matrix similar than:

https://microsoft-my.sharepoint.com/:x:/p/v-slondono/EbmOtYTr0E1PossBRk7HH2cB1Qhf73oBTIoPMLjo3X1e3A?e=E2ThWu

**Comment by batamig** [comment]
Hi @sergioandreslq,
I appreciate your question and such a matrix would indeed be a nice source of data.

The matrix file you sent as an example looks like someone's own OneDrive - I'm not familiar with a similar one for AIP scanning support. I suggest that you either check on yammer or open a support ticket as your best source of information.

I'm going to close this issue for now, but please feel free to continue commenting if you have additional feedback - I do get the updates.

Thanks for writing into docs!
#please-close
