### ISSUE TITLE
Sharepoint --> SharePoint

### ISSUE THREAD

**Issue by BartSwerts** [MicrosoftDocs/Azure-RMSDocs#1429]
Dear, there's a link on the page "What's new in the Sharepoint admin center?" which has SharePoint capitalized incorrectly. It should be "What's new in the SharePoint admin center?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @BartSwerts - thank you so much for sending this fix into docs! 
We're updating the page ASAP and appreciate your contribution.

I'm closing this issue for now, but feel free to continue commenting here if you have additional feedback.
#please-close
