### ISSUE TITLE
Plz correct typo

### ISSUE THREAD

**Issue by dlRo** [MicrosoftDocs/Azure-RMSDocs#1430]
Here: https://docs.microsoft.com/en-us/azure/information-protection/requirements#firewalls-and-network-infrastructure
"If you have a firewalls or similar intervening network devices ..."
should be
"If you have firewalls or similar intervening network devices ... "

**Comment by batamig** [comment]
Hi @dlRo, thanks for sending this into docs!
We're fixing this ASAP and appreciate your contribution.

I'm closing this issue for now, but feel free to add more comments as needed.
#please-close
