### ISSUE TITLE
Supported version of Sharepoint Server for RMS Connector seems to be incorrect

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/Azure-RMSDocs#1431]
On this article, under "Supported on-premises servers for Azure Rights Management data protection" it shows that only 2010, 2013 and 2016 versions are supported, however, on the RMS connector page: https://docs.microsoft.com/en-us/azure/information-protection/configure-servers-rms-connector#configuring-a-sharepoint-server-to-use-the-connector we can find that the Sharepoint Server versions supported are 2010, 2013, 2016 **and 2019**.

Can you please confirm if this 2019 version is supported and also update the documentation accordingly?

Thank you,

Ricardo Trigueiro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-Us/azure/information-protection/requirements#supported-on-premises-servers-for-azure-rights-management-data-protection)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @rtrigueiro, thanks for writing into docs! We're fixing this and it should be live in a coming publish.
I'm going to close this issue for now, but feel free to continue commenting if you have additional feedback.
Thanks for contributing to docs!

#please-close
