### ISSUE TITLE
What is a file name length in bytes?

### ISSUE THREAD

**Issue by gkneale** [MicrosoftDocs/Azure-RMSDocs#1432]
The formula for calculating the SQL requirements is stated as "100 KB + <file count> *(1000 + 4* <average file name length>)"

Below the formula, is the example "For example, to scan 1 million files that have an average file name length of 250 bytes, allocate 2-GB disk space."

What does "file name length of 250 bytes" mean? A file name length would be a number of characters, right? Or is this supposed to be the file size in bytes? Or are we to assume 1 byte per character (if the name is encoded in ASCII or ISO-8895-1) and up to 4 bytes per character if the name is encoded in UTF-8? Or do we assume 1-4 bytes per character on Windows NTFS systems which encode file names in UTF-16?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de80bee1-1be8-066f-1a28-df502ff60cf8
* Version Independent ID: 56905bf5-2244-8b92-b122-55b8c7f2e4ec
* Content: [Azure Information Protection (AIP) unified labeling scanner prerequisites](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-prereqs)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner-prereqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner-prereqs.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @gkneale, thanks for sending your question into docs.
I've checked back with the team for this - the size is based on the SQL **NVARCHAR** column, which is where the file name is saved.
The calculation for the actual storage size in bytes of a NVARCHAR value is the number of characters entered x2, plus 2 bytes.
I hope that answers your question. We can plan to clarify this in the docs in an upcoming publish.

I'm going to close this issue for now, but feel free to continue commenting if you have more feedback.
Thanks for your contribution!
#please-close
