### ISSUE TITLE
Wording for the AIP conditional Access

### ISSUE THREAD

**Issue by oscarmb6** [MicrosoftDocs/Azure-RMSDocs#1435]
[Enter feedback here]
I believe the place where reads "You can also entitle disable CA within Azure information Protection..."

Should be "You can also entitle disable/Exclude Azure information Protection within CA..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93961dd-63a4-e584-4faa-a905a38964e3
* Version Independent ID: 0fe5c8d8-31ef-27f4-b66a-dc93a402aea5
* Content: [Known issues - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/known-issues#aip-based-conditional-access-policies)
* Content Source: [Azure-RMSDocs/known-issues.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/known-issues.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @oscarmb6, thanks for writing into docs!
I've checked with the team just to verify this and will be publishing an update on this page shortly.
I'm closing this issue for now but please feel free to continue commenting as needed.

We appreciate your contribution to docs!
#please-close
