### ISSUE TITLE
GetSensitivityLabels() should be changed to ListSensitivityLabels()

### ISSUE THREAD

**Issue by rkgain** [MicrosoftDocs/Azure-RMSDocs#1436]
I guess there is no method as GetSensitivityLabels() in file engine or policy engine. If its true then please correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3489bb18-3ac2-3996-3314-a6c291bf1a19
* Version Independent ID: 47e63e8b-ab87-ef70-45a7-115f2bd64089
* Content: [Concepts - The File SDK engine object](https://docs.microsoft.com/en-us/information-protection/develop/concept-profile-engine-file-engine-cpp)
* Content Source: [mip/develop/concept-profile-engine-file-engine-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-file-engine-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @rkgain, thanks for writing into docs!
I'm tagging the content owner on this page. @tommoser, can you take a look?

@rkgain, I can also recommend that you either open a support ticket or ask your question on our Yammer group https://www.yammer.com/askipteam/ for more clarification.

**Comment by tommoser** [comment]
Fixed in https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4717.

**Comment by batamig** [comment]
Thanks @tommoser! I'll close this item.

#please-close
