### ISSUE TITLE
Update for Unified Labeling client ? 

### ISSUE THREAD

**Issue by h4n0sh1** [MicrosoftDocs/Azure-RMSDocs#1437]
Hello 

I am trying to set up FCI with AIP using this script, i've been following the provided [instructions](https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/configure-fci.md), however all the cmdlets used in the script seem to be deprecated by the new UL client. 

Is there an up to date version of this script ? 

Best regards

**Comment by batamig** [comment]
Hi @h4n0sh1, thanks for writing into the docs.
This article is currently written for use with the Azure Information Protection classic client, which is currently deprecated and scheduled for end of life on March 31st.  We don't currently have an update for the script with the unified labeling client.

I'm going to investigate with the team to see how we can replace this information and update as needed in a coming publish. In the meantime, I recommend that you either open a support case or ask your question on our Yammer group at https://www.yammer.com/askipteam/#/home.

I'm going to close this issue for now, but feel free to continue commenting if you have additional questions.
Thanks for your contributions to docs!
#please-close
