### ISSUE TITLE
Requesting examples for the new LabelInfo stream locations

### ISSUE THREAD

**Issue by Chbergman** [MicrosoftDocs/Azure-RMSDocs#1439]
The article is very useful, but the AIP team has introduced a new location for LabelInfo. Custom attributes (for files) are no longer utilized if co-authoring is enabled for Office Desktop apps. Instead, the label meta data is stored in LabelInfo stream locations described here: https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-offcrypto/0c4ec12d-aba0-4dd4-8fd1-710da6735219

Please update the article to include the new LabelInfo location. 
Thanks,

 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4f87ed-6649-6998-889b-58f14556db29
* Version Independent ID: 46468916-b0f0-56b9-23d7-add664cc49b1
* Content: [Exchange Online mail flow rules for Azure Information Protection labels](https://docs.microsoft.com/en-us/azure/information-protection/configure-exo-rules#prerequisite-know-your-label-guid)
* Content Source: [Azure-RMSDocs/configure-exo-rules.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-exo-rules.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @Chbergman, thanks for sending your comments into docs!

Please be advised that this article is relevant in context of the Azure Information Protection classic client and the AIP labeling and labeling policies on the Azure portal.

The classic client is currently deprecated, and we are not making changes to the related articles. If you're looking for information about labeling in Microsoft 365, please see the Microsoft 365 compliance center documentation here: https://docs.microsoft.com/en-us/microsoft-365/compliance/information-protection.

I'm going to close this issue for now, but feel free to continue commenting as needed.
#please-close
