### ISSUE TITLE
xls Worksheet of Excel 5.0/95 not supported

### ISSUE THREAD

**Issue by SRE93** [MicrosoftDocs/Azure-RMSDocs#1442]
Hi, we are trying to encrypt files with .xls extension but version Excel 5.0/95 and receiving the following error:
![image](https://user-images.githubusercontent.com/39616319/155100719-b8dc9270-2915-40f1-9cd6-8d94425b3e6c.png)

Is the fileextension .xls from Excel 5.0/95 not supported for classification and encryption by unified labeling client? Maybe with a wrapper .pfile?

hyperlink:
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#supported-file-types-for-classification-and-protection

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044457bf-06a4-cc9e-3425-780a748c50ed
* Version Independent ID: 4e587393-64eb-4cd7-f2a6-e0e22e22a8bd
* Content: [File types supported by the Azure Information Protection (AIP) unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#supported-file-types-for-classification-and-protection)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by SRE93** [comment]
any updates here? anyone?

**Comment by batamig** [comment]
Hi there - thanks for writing into docs!

To get an answer to this question, please open a support ticket or ask on our Yammer group, which has many active experts. You can find them here: https://www.yammer.com/askipteam/

If changes are required in docs to clarify, those updates will come back to us, and we'll update in a coming publish.

I'm going to close this issue for now, but feel free to continue commenting if you have additional feedback. We always appreciate your input.

#please-close
