### ISSUE TITLE
good app

### ISSUE THREAD

**Issue by triple03** [MicrosoftDocs/Azure-RMSDocs#1443]
[Enter feedback here]
good app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1562feec-bf8f-9e84-b642-bcd259c8a418
* Version Independent ID: 953ab73d-8ee8-b63e-a7d4-52aaa60026f8
* Content: [Mobile viewer apps for Azure Information Protection (iOS and Android) - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/mobile-app-faq)
* Content Source: [Azure-RMSDocs/rms-client/mobile-app-faq.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/mobile-app-faq.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks @triple03 - We love getting feedback from users.
I'm going to close this issue for now, but feel free to continue adding more comments as needed.
Have a terrific day!
#please-close
