### ISSUE TITLE
Adding AIP client 2.11.58.0 to the no longer supported table.

### ISSUE THREAD

**Issue by anilgeo06** [MicrosoftDocs/Azure-RMSDocs#1445]
The AIP client build Version 2.11.58.0 is already out of support on 02/08/2022 but it is not added in the _General availability versions that are no longer supported_ table. Can we add it in the list ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Release management and supportability - Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @anilgeo06 - thanks for writing into docs! Thanks for bringing this to our attention, we'll check it out and update as needed in a coming publish.

I'm closing this issue for now, but feel free to continue commenting if you have more feedback. We appreciate your contribution to docs!
#please-close
