### ISSUE TITLE
Improve wording for excluding AIP in Conditional Access

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/Azure-RMSDocs#1446]
re 'You can also entirely disable/exclude CA within Azure Information Protection if the functionality is not required for your organization, in order to avoid this potential issue." in the section on Conditional Access:   Since multiple policies could result in access to AIP being denied a CA policy that explicitly opens it is needed. Consider rewording along the lines of "If Conditional Access is not required for Azure Information Protection in your organization create a CA policy for AIP that allows all users and set other conditions, if used in other policies, to the least restrictive setting."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93961dd-63a4-e584-4faa-a905a38964e3
* Version Independent ID: 0fe5c8d8-31ef-27f4-b66a-dc93a402aea5
* Content: [Known issues - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/known-issues#known-issues-for-track-and-revoke-features)
* Content Source: [Azure-RMSDocs/known-issues.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/known-issues.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @bholzmmc, thanks for writing into docs! I'm tagging one of our current content owners to address.
@swalkerde - any thoughts on this one?

**Comment by swalkerde** [comment]
I'll discuss with our team lead and update as appropriate.  I’m going to close this issue for now, but feel free to continue commenting below if you have additional feedback.
#please-close
