### ISSUE TITLE
broken link: https://www.microsoft.com/cloud-platform/azure-information-protection-features

### ISSUE THREAD

**Issue by sergioandreslq** [MicrosoftDocs/Azure-RMSDocs#1448]
[Enter feedback here]

Hello team, 

There is a broken link sending to 404 error message

https://www.microsoft.com/cloud-platform/azure-information-protection-features --> Broken!!!!!

"When you access this site, sign in to track your documents. When your organization has a [subscription that supports document tracking and revocation](https://www.microsoft.com/cloud-platform/azure-information-protection-features)!!!!!!!!!!!

 and you are assigned a license for this subscription, you can see who tried to open the files that"

when we click that hyperlink, We got a 404 not found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74c2dca-2883-0833-9176-0f5ea2cd9c62
* Version Independent ID: f02aa653-1300-b8c2-7b75-ad17f082dbfe
* Content: [Track & revoke documents with the legacy tracking portal - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-track-revoke)
* Content Source: [Azure-RMSDocs/rms-client/client-track-revoke.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-track-revoke.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @sergioandreslq - thanks for bringing this to our attention. 

The document tracking site is a legacy service that is still available for customers who have it licensed.

If you're using the unified labeling client, you can find more information about tracking and revoking access with the unified labeling client here:
- [Administrator Guide: Track and revoke document access with Azure Information Protection](https://docs.microsoft.com/azure/information-protection/rms-client/track-and-revoke-admin)
- [User Guide: Revoke document access with Azure Information Protection](https://docs.microsoft.com/azure/information-protection/rms-client/revoke-access-user)

We'll take another look at this content to see how we can clarify this message. I'm going to close this issue in the meantime, but feel free to continue commenting here as needed.
Thanks for your contributions to docs!
#please-close
