### ISSUE TITLE
Missing additional information about timeframe for Track & Revoke

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/Azure-RMSDocs#1450]
_Registering a document for tracking enables admins to track access details, including successful access events and denied attempts, as well as revoke access if needed._

What is missing from my point of view is a statement about the timeframe. Is there a max timeframe/age?
Can I revoke document older than x years? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179f78bb-2202-5c69-16ec-28f544f7676c
* Version Independent ID: b6a6ebe6-3ce9-9cff-84c3-484479afe7d4
* Content: [Track and revoke access - Azure Information Protection](https://review.docs.microsoft.com/en-us/azure/information-protection/rms-client/track-and-revoke-admin?source=docs&branch=main)
* Content Source: [Azure-RMSDocs/rms-client/track-and-revoke-admin.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/track-and-revoke-admin.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @bholzmmc, thanks for writing into docs! Please re-ask your question in the AIP Yammer group at https://www.yammer.com/askipteam/#/home. 
I'm going to close this item here for now, but you can continue commenting here as needed. I'm tagging one of our current content owners for visibility - please see this @swalkerde 

#please-close
