### ISSUE TITLE
Legacy Portal is going away?

### ISSUE THREAD

**Issue by LaPhi** [MicrosoftDocs/Azure-RMSDocs#1451]
From my understanding this Portal is a Legacy Portal and is going away. But in this article is no hind like "Attention this Portal is going away when Classic Client expire etc."
Please can you add this information if the Portal is going away?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74c2dca-2883-0833-9176-0f5ea2cd9c62
* Version Independent ID: f02aa653-1300-b8c2-7b75-ad17f082dbfe
* Content: [Track & revoke documents with the legacy tracking portal - Azure Information Protection](https://review.docs.microsoft.com/en-us/azure/information-protection/rms-client/client-track-revoke)
* Content Source: [Azure-RMSDocs/rms-client/client-track-revoke.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-track-revoke.md)
* Service: **information-protection**
* Sub-service: **doctrack**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @LaPhi, thanks for writing into docs! The page is now updated with the relevant note.
I'm going to close this item, but you can feel free to comment further as needed.

We appreciate your contribution to docs!
#please-close
