### ISSUE TITLE
Co-Authoriing Issues and more information around "Labels with user-defined permissions."

### ISSUE THREAD

**Issue by j-dahl7** [MicrosoftDocs/Azure-RMSDocs#1454]
Can we get a little more information around 

"Labels with user-defined permissions. In Microsoft Word, Excel, and PowerPoint, labels with user-defined permissions are still available and can be applied to documents but are not supported for co-authoring features.

This means that applying a label with user-defined permissions will prevent you from working on the document with others simultaneously."

I have come into contact with specific labels; co-authoring no longer works when using desktop apps like Excel; however, it will work with Excel Online. I am unsure if this is a bug, but it is strange. The MIP policy has protection where the file cannot be shared outside the domain.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a93961dd-63a4-e584-4faa-a905a38964e3
* Version Independent ID: 0fe5c8d8-31ef-27f4-b66a-dc93a402aea5
* Content: [Known issues - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/known-issues)
* Content Source: [Azure-RMSDocs/known-issues.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/known-issues.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @j-dahl7, thanks for writing into docs! Please re-ask your question in the AIP Yammer group at https://www.yammer.com/askipteam/#/home.
I'm going to close this item here for now, but you can continue commenting here as needed. I'm tagging one of our current content owners for visibility and in case any doc updates are needed - please see this @swalkerde

#please-close

**Comment by swalkerde** [comment]
Thanks @j-dahl7 I will investigate this scenario and update docs as needed.

**Comment by j-dahl7** [comment]
@swalkerde thank you!
