### ISSUE TITLE
Need details on SPO permissions needed for super user

### ISSUE THREAD

**Issue by GreggRevak** [MicrosoftDocs/Azure-RMSDocs#1456]
The files that the super user may be managing may be store in SharePoint Online (or OneDrive). The documentation needs to describe the SPO permissions that are required for super user account to be able to manage them. You can use a Global Admin account but that is not best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19d4b87c-1f20-37b4-be0b-f69354df1830
* Version Independent ID: 2bb88bdb-bbcd-033e-e23e-da88ed8a67e0
* Content: [Configure super users for Azure Rights Management - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-super-users)
* Content Source: [Azure-RMSDocs/configure-super-users.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-super-users.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by swalkerde** [comment]
Superuser only interacts with the protection elements.  File access would be controlled by "normal" SPO permissions.  I’m going to close this issue for now, but feel free to continue commenting below if you have additional feedback.
#please-close
