### ISSUE TITLE
Troubleshooting section redirects to missing information

### ISSUE THREAD

**Issue by CommCody** [MicrosoftDocs/Azure-RMSDocs#1457]
Hi all,

I am following the quickstarts of this product. But during the list sensitivity labels quickstart I don't see any output. The troubleshooting section redirects me to the setup for MIP page to a section that doesn't exist:

> If your project builds successfully, but you have no output in the console window, be sure your organization's sensitivity labels are configured correctly. See MIP SDK setup and configuration, under "Define label taxonomy and protection settings" for details.

Because of this I'm stuck following this quickstart. Could you redirect me to the correct information to configure the labels?

Kind Regards,
Joris

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8bdc7d3-923b-947b-47bb-b04b6f53ec7d
* Version Independent ID: 4db29042-dfcf-97b5-4c29-6ec25eeb57fd
* Content: [Quickstart - List sensitivity labels in a Microsoft Information Protection (MIP) tenant using MIP SDK C# Wrapper](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-list-labels-csharp)
* Content Source: [mip/develop/quick-file-list-labels-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-list-labels-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @CommCody, thanks for writing into docs! I'm tagging our content owner to address. @tommoser, can you take a look?

**Comment by batamig** [comment]
Hi - updating to tag a current content owner to address
@aashishr, can you advise?

**Comment by tommoser** [comment]
@CommCody, we'll review the links and update.

You need to have a labeling policy configured in Compliance Center. This doc can help: https://docs.microsoft.com/en-us/microsoft-365/compliance/create-sensitivity-labels?view=o365-worldwide

**Comment by batamig** [comment]
Thanks for addressing! I'm going to close this issue for now, but feel free to continue commenting as needed.
#please-close
