### ISSUE TITLE
Who Manages, Upgrades, and Patches HSMs

### ISSUE THREAD

**Issue by jks05c** [MicrosoftDocs/Azure-RMSDocs#1458]
Hoping for clarification needed between the following statements - [https://docs.microsoft.com/en-us/azure/information-protection/operations-customer-managed-tenant-key#respond-to-a-breach](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Finformation-protection%2Foperations-customer-managed-tenant-key%23respond-to-a-breach&data=05%7C01%7CJoshua.Stallings%40microsoft.com%7C4efc196254b24e335a6808da1c30565d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637853291473877191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cGSwrg2Xi31DYx5VW8ClqY%2Fr6hk9a9u7jFjCtScmUwA%3D&reserved=0)

“Microsoft must update the HSMs. If there is reason to believe that the vulnerability exposed keys, Microsoft will instruct all customers to rekey their tenant keys.”

versus

If there is a security vulnerability found and a patch is released by Thales, who is responsible for upgrading/patching OS/Firmware?  Microsoft does not have the ability to connect to HSMs allocated to customers. Customers must upgrade and patch their HSMs.  Frequently asked questions - Azure Dedicated HSM | Microsoft Docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a7e847-721a-8064-5d47-abcef59ec12f
* Version Independent ID: 9031c4fb-1e77-25cc-25ca-ad1ab07e7dd7
* Content: [Customer-managed - AIP tenant key life cycle operations](https://docs.microsoft.com/en-us/azure/information-protection/operations-customer-managed-tenant-key#respond-to-a-breach)
* Content Source: [Azure-RMSDocs/operations-customer-managed-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/operations-customer-managed-tenant-key.md)
* Service: **information-protection**
* Sub-service: **kms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @jks05c, thanks for writing into docs! Please re-ask your question in the AIP Yammer group at https://www.yammer.com/askipteam/#/home.
I'm going to close this item here for now, but you can continue commenting here as needed. I'm tagging one of our current content owners for visibility and in case any doc updates are needed - please see this @swalkerde

#please-close
