### ISSUE TITLE
wording misleading - states AIP Add-in is "NEW" 

### ISSUE THREAD

**Issue by gbms311** [MicrosoftDocs/Azure-RMSDocs#1461]
The wording is outdated. It states 

_"Example showing the Office add-in for the Azure Information Protection unified labeling client, displaying the **new** Sensitivity button on the ribbon and the optional Azure Information Protection bar:"_

The Add-in is not NEW. It is outdated and not recommended. see: https://docs.microsoft.com/en-us/microsoft-365/compliance/sensitivity-labels-aip?view=o365-worldwide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54a890ae-43df-fa2d-add9-3b2314be89e5
* Version Independent ID: e4cd0cae-dce4-627c-398b-6fa2e22b17c6
* Content: [Azure Information Protection unified labeling client admin guide](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @gbms311! Thanks for writing into docs and bringing this to our attention.
We'll clean this up in a coming publish and appreciate your contribution to docs!
I'm going to close this issue for now but feel free to continue commenting as needed.

#please-close
