### ISSUE TITLE
Supported filetypes for inspection in Sharepoint Online AIP

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/Azure-RMSDocs#1462]
It is not clear that sharepoint online will inspect .pdf file type to apply automatic classification & protection.

In this article, under [file types supported for inspection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types#file-types-supported-for-inspection)  it is mentioned .pdf as a supported file type, however only in the context of the AIP Unified Labeling client with the IFilter. 
Can we have a clarification on the documention what is the supported filetypes for inspection in SPO?

Thank you.

Ricardo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 044457bf-06a4-cc9e-3425-780a748c50ed
* Version Independent ID: 4e587393-64eb-4cd7-f2a6-e0e22e22a8bd
* Content: [File types supported by the Azure Information Protection (AIP) unified labeling client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-file-types)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks @rtrigueiro! I'm tagging a recent content owner to help address your question.
@swalkerde, can you take a look?

**Comment by rtrigueiro** [comment]
Any update?

**Comment by swalkerde** [comment]
@Rtrigueiro I would not be able to weigh in on this scenario (I only work with UL Client).  My suggestion is to open a case with support so they can provide an official support statement for SPO native support.

**Comment by batamig** [comment]
Thanks @swalkerde. 
@rtrigueiro, I'm going to close this issue for now, but feel free to continue commenting as needed.
#please-close
