### ISSUE TITLE
September 31st?

### ISSUE THREAD

**Issue by Luspin** [MicrosoftDocs/Azure-RMSDocs#1463]
There will be no September 31, ever.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Analytics and central reporting for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Thanks for bringing this to our attention! We've fixed this bug and it should be updated in a coming publish.
We appreciate your contribution to docs.

#please-close
