### ISSUE TITLE
Log Analytics is no longer supported in the AIP Portal

### ISSUE THREAD

**Issue by smccnn1** [MicrosoftDocs/Azure-RMSDocs#1464]
Hey there,

Since March/April 2022, newer AIP customers are unable to view or create Log Analytics for AIP. Specifically, logs for scanning on-premises repositories and finding sensitive data in environments seems to be missing from documentation as there is no description of where to find the logs within Purview. While Purview is showing _some_ discovered files, its not what the AIP scanner is scanning.

AIP has scanned 600k files, while in Purview, Files Discovered are under 1000. There is something amiss and there is no documentation which deals with the log issue.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Analytics and central reporting for Azure Information Protection (AIP)](https://docs.microsoft.com/en-gb/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @smccnn1, thanks for writing into docs!

I recommend that you ask your question again on our yammer group, which has a group of experts who should be able to answer: https://www.yammer.com/askipteam/

I'm going to close this issue for now but am also tagging one of our team members for visibility. @swalkerde, are you able to assist?
Feel free to continue commenting here as needed.
#please-close
