### ISSUE TITLE
Type 

### ISSUE THREAD

**Issue by jrdtechnologies** [MicrosoftDocs/Azure-RMSDocs#1467]
type 
"the we have r"
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [Learn about built-in labeling and the AIP unified labeling client - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @jrdtechnologies, thanks for the heads up! We'll get this fixed in a coming publish. 
We appreciate your contribution to docs! 
#please-close
