### ISSUE TITLE
AIP mobile app on Android no longer support ADRMS protected file. Please help to update the document

### ISSUE THREAD

**Issue by JerryChang200008** [MicrosoftDocs/Azure-RMSDocs#1470]
[Enter feedback here]
With the confirmation from AIP PG, the AIP mobile app on Android no longer support ADRMS protected files. AIP has updated the knowns issue document but this document from Office is not updated: [Active Directory rights management services mobile device extension for AIP | Microsoft Docs](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device)

Please help to update the document to indicate the AIP mobile app on Android is no longer supported with ADRMS. This is the AIP document about the known issue: [Known issues - Azure Information Protection | Microsoft Docs](https://docs.microsoft.com/en-us/azure/information-protection/known-issues#adrms-protected-files-on-android-devices)

Please find my alias: v-yifanchang@microsoft.com if you need further information. Thank you!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://docs.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi and thanks for writing into docs! 
I'm tagging a current content owner to advise. @aashishr, can you take a look?

**Comment by aashishr** [comment]
@Krishna ***@***.***> - can you take a look?

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
