### ISSUE TITLE
This article mentions the prior one having Console.ReadKey - which it doesn't.

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/Azure-RMSDocs#1471]
This article says:

> Toward the end of the Main() body, below Console.ReadKey() and above } 

However, none of the prior articles in the series has added a Console.ReadKey - as far as I can see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b0a2b2-7502-f245-9d9b-4bf566633065
* Version Independent ID: f7f5635e-44ec-c1cc-ac35-2ecf57790248
* Content: [Quickstart - Set and get a sensitivity label on a file using the C# MIP SDK](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp)
* Content Source: [mip/develop/quick-file-set-get-label-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-set-get-label-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi and thanks for writing into docs! 
I'm tagging a current content owner to advise. @aashishr, can you take a look?

**Comment by tommoser** [comment]
@zhang-yangchen, can you take a look at this?

**Comment by tommoser** [comment]
https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4866

**Comment by batamig** [comment]
Thanks Tom!
@Dave-Lowndes, I'm closing this issue for now, but feel free to continue commenting as needed.
#please-close

**Comment by Dave-Lowndes** [comment]
I'll assume its fixed as I get a 404 error with the PR link.
