### ISSUE TITLE
Console output shown on page does not correspond to the code shown.

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/Azure-RMSDocs#1472]
The console output shown as an example is different to what the source code would produce.
There appears to be some lines of code missing in the source compared with the example output.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b0a2b2-7502-f245-9d9b-4bf566633065
* Version Independent ID: f7f5635e-44ec-c1cc-ac35-2ecf57790248
* Content: [Quickstart - Set and get a sensitivity label on a file using the C# MIP SDK](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp)
* Content Source: [mip/develop/quick-file-set-get-label-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-set-get-label-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi @Dave-Lowndes, thanks for writing into docs!
I'm tagging the current content owner to advise. @aashishr or @tommoser, can you take a look? Thanks!

**Comment by tommoser** [comment]
https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4866

**Comment by batamig** [comment]
Thanks Tom! 
@Dave-Lowndes, I'm closing this issue for now, but feel free to continue commenting as needed.
#please-close

**Comment by Dave-Lowndes** [comment]
@batamig  I don't have permission to see that PR, so I'm assuming you've fixed the documentation :)

**Comment by batamig** [comment]
Hi @Dave-Lowndes, that's right, you may not be able to access the PR. Please check the updated docs for the fix.
