### ISSUE TITLE
Main code sample ignores proper IDisposable variable handling

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/Azure-RMSDocs#1473]
As people are copying this code, it should either come with a distinct warning, or illustrate better programming practice regarding IDisposable variables for the following items:

Value returned from CreateMipContext
Value from LoadFileProfileAsync
Value from AddEngineAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b0a2b2-7502-f245-9d9b-4bf566633065
* Version Independent ID: f7f5635e-44ec-c1cc-ac35-2ecf57790248
* Content: [Quickstart - Set and get a sensitivity label on a file using the C# MIP SDK](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp)
* Content Source: [mip/develop/quick-file-set-get-label-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-set-get-label-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by batamig** [comment]
Hi, and thanks for writing into docs! I'm tagging a current content owner to advise.
@aashishr, can you please take a look?

**Comment by tommoser** [comment]
@zhang-yangchen, can you take a look at this?

**Comment by tommoser** [comment]
@batamig created PR: https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4873

I added a disclaimer for now. Later, we can look at changing the sample code.
