### ISSUE TITLE
Broken URL (When is the right time to migrate my labels to unified labeling?)

### ISSUE THREAD

**Issue by MSFTEfeedback** [MicrosoftDocs/Azure-RMSDocs#1475]
The URL for "[When is the right time to migrate my labels to unified labeling?](https://docs.microsoft.com/en-us/previous-versions/azure/information-protection/faqs-classic.md#when-is-the-right-time-to-migrate-my-labels-to-unified-labeling)" does not work. Get a 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to unified sensitivity labels - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* Sub-service: **labelmigrate**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi and thanks for letting us know about this broken link! You can find this information here, in our archived docs: https://docs.microsoft.com/previous-versions/azure/information-protection/faqs-classic#when-is-the-right-time-to-migrate-my-labels-to-unified-labeling

I'm going to close this item for now, but feel free to continue commenting as needed. 
#please-close
