### ISSUE TITLE
Clarify the SQL Server requirement that you need a SQL Server installed on the scanner machine.

### ISSUE THREAD

**Issue by rtrigueiro** [MicrosoftDocs/Azure-RMSDocs#1476]
Under the table in https://docs.microsoft.com/en-us/azure/information-protection/tutorial-install-scanner#tutorial-prerequisites it is mentioned "To run the scanner, you'll need SQL Server installed on the scanner machine."

However the AIP Scanner can be installed on remote SQL Server and actually that is also one of the recommended approaches as described in: https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-prereqs#sql-server-requirements and https://techcommunity.microsoft.com/t5/security-compliance-and-identity/best-practices-for-deploying-and-using-the-aip-ul-scanner/ba-p/1878168

Can you please clarify on this article that this "local sql server installation" is only for the purpose of this tutorial? and that installing a remote SQL server it is supported.

Thank you,

Ricardo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0927bf-7a11-d800-f0ae-a1c0ce4dcb06
* Version Independent ID: ef830f65-1986-830e-be04-95d163d2de6c
* Content: [Tutorial - Install the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/tutorial-install-scanner)
* Content Source: [Azure-RMSDocs/tutorial-install-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/tutorial-install-scanner.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi and thanks for writing into docs!
I'm tagging a current content owner to advise here. @aashishr - can you take a look here?

**Comment by aashishr** [comment]
Thanks @Aashish ***@***.***>
To clarify


  1.  In the tutorial "local sql server installation" is only for Non-Production Lab environment
  2.  Remote SQL Server is supported, and SQL Enterprise edition must be used for all Production deployment.

Regards
Krishna

**Comment by rtrigueiro** [comment]
Thank you @aashishr that clarifies it! :)

**Comment by batamig** [comment]
Hi - i'm closing this issue for now, but feel free to continue commenting as needed. 
Thanks for writing into docs!
#please-close

**Comment by aashishr** [comment]
@Krishna ***@***.***> - please have a look

Regards,
Aashish

PS: sent from phone; excuse typos
________________________________
