### ISSUE TITLE
"This Product" goes to a dead UserVoice Link

### ISSUE THREAD

**Issue by timkatsapas** [MicrosoftDocs/Azure-RMSDocs#1477]
Hey there, 
There is a dead link. When you scroll to the bottom of the docs and click "This Product" which should send feedback to the PG, the UserVoice is no longer available. Please can you update this so we can update the PG with features and suggestions.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Release management and supportability - Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi and thanks for writing into docs!
I'm tagging a current content owner to advise here. @aashishr - can you take a look here?

**Comment by aashishr** [comment]
@Yangchen ***@***.***> - please have a look

Regards,
Aashish

PS: sent from phone; excuse typos
________________________________

**Comment by zhang-yangchen** [comment]
@batamig @aashishr There are more than one repo with this issue.

UserVoice feedback service was deprecated in 2021, notice: "We will be moving away from UserVoice feedback sites on a product-by-product basis throughout the 2021 calendar year. We will leverage 1st party solutions for customer feedback."
Other docs use this preview feedback service instead: https://feedbackportal.microsoft.com/feedback/

I will replace this in the .yml files for the following repos that use UserVoice:
1. AIP: https://docs.microsoft.com/en-us/azure/information-protection/
2. MIP SDK: https://docs.microsoft.com/en-us/information-protection/develop/

I will create the PRs and update these links today.

**Comment by batamig** [comment]
Thanks @zhang-yangchen! In that case, I'm going to close this issue for now as the docs should be updated shortly. 
#please-close

**Comment by zhang-yangchen** [comment]
@batamig @msmbaldwin 

It appears I don't have permissions to edit these docs but I have located the docs to be changed: 
1. Azure-RMSDocs/docfx.json [https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/blob/464add8ecb310b6dd843cd0edb74e1c0be09d1ce/Azure-RMSDocs/docfx.json] - LINE 37
2. mip/docfx.json [https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/blob/464add8ecb310b6dd843cd0edb74e1c0be09d1ce/mip/docfx.json] - LINE 43

Replace UserVoice links with: "https://feedbackportal.microsoft.com/feedback/"
