### ISSUE TITLE
The link to the video Azure Information Protection Outlook Popup Configuration is broken

### ISSUE THREAD

**Issue by ancmarti** [MicrosoftDocs/Azure-RMSDocs#1478]
The link to the above section is broken. it takes you to Azure Video s but not to the actual configuration video. It can be confusing for our customers. Please fix it

See the video [Azure Information Protection Outlook Popup Configuration](https://azure.microsoft.com/resources/videos/how-to-configure-azure-information-protection-popup-for-outlook/) for a walkthrough example of how to configure these settings.

**Comment by batamig** [comment]
Hi @ancmarti, thanks for writing into docs!
I'm tagging the current content owner to advise. @aashishr , can you take a look? Thanks!

**Comment by aashishr** [comment]
@Krishna ***@***.***> - can you take a look at this?

**Comment by zhang-yangchen** [comment]
Video has been replaced by a tech blog link for configuring Outlook oversharing popups.

https://github.com/MicrosoftDocs/Azure-RMSDocs-pr/pull/4908

**Comment by msmbaldwin** [comment]
#please-close
