### ISSUE TITLE
Licensing requirements

### ISSUE THREAD

**Issue by FernandoGualano** [MicrosoftDocs/Azure-RMSDocs#1479]
I am reading the docs https://docs.microsoft.com/en-us/azure/information-protection/reports-aip and the type of license required is not specified. What type of license is needed? 

Azure Information Protection for Office 365?
Azure Information Protection Premium P1?
Azure Information Protection Premium P2?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Analytics and central reporting for Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* Sub-service: **analytics**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @FernandoGualano, thanks for writing into docs!
I'm tagging the current content owner to advise. @aashishr , can you take a look? Thanks!

**Comment by aashishr** [comment]
@Krishna ***@***.***>- can you take a look?

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
