### ISSUE TITLE
About AIP UL Client 2.12.62.0 End of Support Date

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Azure-RMSDocs#1480]
[Enter feedback here]
The following statement in "Servicing information and timelines" is confusing to users because the actual AIP client 2.12.62.0 has a different expected end of support date.

++++++++++++++++++++++++++++
For example, version 2.12.62.0 was released on Aug 2, 2021, then the next version - 2.13.49.0, was released on Jan 12, 2022. Therefore, version 2.12.62.0 is fully supported six months after Jan 12, 2022, which is Jul 12, 2022.
++++++++++++++++++++++++++++

In fact, it is stated in the separate versions that 2.12.62.0 will be supported until September 30,2022.
Consider stating that there are exceptions in the support policy depending on the build , or modifying it by using another version as an example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Release management and supportability - Azure Information Protection (AIP)](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @juhirao, thanks for writing into docs!
I'm tagging the current content owner to advise. @aashishr , can you take a look? Thanks!

**Comment by aashishr** [comment]
@Krishna ***@***.***> - can you take a look?

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
