### ISSUE TITLE
Typo or missing words?

### ISSUE THREAD

**Issue by Arne-RFA** [MicrosoftDocs/Azure-RMSDocs#1481]
[Enter feedback here]
"A cloud access security broker or data loss prevention solution that reasons over data encrypted with Azure Information Protection."

While "reasons" could be intended to be along the lines of "form a judgement" or "logic", the usage is quite _weak_, might "provide additional governance" be a better form, or was something else meant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection (AIP)?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by aashishr** [comment]
@Krishna ***@***.***> – can you take a look at this?

From: Arne-RFA ***@***.***>
Sent: Tuesday, August 2, 2022 2:10 AM
To: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Aashish Ramdas ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Azure-RMSDocs] Typo or missing words? (Issue #1481)


[Enter feedback here]
"A cloud access security broker or data loss prevention solution that reasons over data encrypted with Azure Information Protection."

While "reasons" could be intended to be along the lines of "form a judgement" or "logic", the usage is quite weak, might "provide additional governance" be a better form, or was something else meant?

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
  *   Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
  *   Content: What is Azure Information Protection (AIP)?<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Finformation-protection%2Fwhat-is-information-protection&data=05%7C01%7Caashishr%40microsoft.com%7C6c18e1955e9149b3a4cd08da7466d304%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637950282233102131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Oz0Nf5T9pdcy3rhZI8rt0VXhdXbQI3h%2FS3HA4J6bPu4%3D&reserved=0>
  *   Content Source: Azure-RMSDocs/what-is-information-protection.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAzure-RMSDocs%2Fblob%2Fmaster%2FAzure-RMSDocs%2Fwhat-is-information-protection.md&data=05%7C01%7Caashishr%40microsoft.com%7C6c18e1955e9149b3a4cd08da7466d304%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637950282233102131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zxJTtzgbA8oSAGpQp3NvnmaXUEjHmzvAT3DD%2BqWqgsQ%3D&reserved=0>
  *   Service: information-protection
  *   GitHub Login: @aashishr<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faashishr&data=05%7C01%7Caashishr%40microsoft.com%7C6c18e1955e9149b3a4cd08da7466d304%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637950282233102131%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QaETmMERCxOBSySCuK0zIj2yfTMa%2FF%2F%2BQL24oKmsO68%3D&reserved=0>
  *   Microsoft Alias: aashishr

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close

**Comment by Arne-RFA** [comment]
To close a documentation issue because nobody looked at it is ridiculous.
