### ISSUE TITLE
Product Support

### ISSUE THREAD

**Issue by Jlouden9** [MicrosoftDocs/Azure-RMSDocs#1483]
Hi,

Just wondering if there should be a section on this page about Purveiw replacing AIP? 

Regards
John

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Understanding the Azure Information Protection unified labeling scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by aashishr** [comment]
@Krishna ***@***.***> – can you take a look at this?

From: Jlouden9 ***@***.***>
Sent: Thursday, August 4, 2022 7:56 PM
To: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Aashish Ramdas ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Azure-RMSDocs] Product Support (Issue #1483)


Hi,

Just wondering if there should be a section on this page about Purveiw replacing AIP?

Regards
John

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
  *   Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
  *   Content: Understanding the Azure Information Protection unified labeling scanner - AIP<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Finformation-protection%2Fdeploy-aip-scanner&data=05%7C01%7Caashishr%40microsoft.com%7C0158404beb4441548ae008da768e16ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952649890467035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Fs0siaYUHTQEqB%2BvJ%2FI12Y01aUhhwOUh0gqVNi3T99k%3D&reserved=0>
  *   Content Source: Azure-RMSDocs/deploy-aip-scanner.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAzure-RMSDocs%2Fblob%2Fmaster%2FAzure-RMSDocs%2Fdeploy-aip-scanner.md&data=05%7C01%7Caashishr%40microsoft.com%7C0158404beb4441548ae008da768e16ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952649890467035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7k36hCsX0BQ9F9%2B5icDbVB%2B3bpKpe5818l%2BiaQS1SI4%3D&reserved=0>
  *   Service: information-protection
  *   Sub-service: scanner
  *   GitHub Login: @aashishr<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faashishr&data=05%7C01%7Caashishr%40microsoft.com%7C0158404beb4441548ae008da768e16ed%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637952649890467035%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YXRLxuSlzSp3OQXrHg1rBdRUuzy8GguFKRC0qaS6kwY%3D&reserved=0>
  *   Microsoft Alias: aashishr

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
