### ISSUE TITLE
Notes about deprecated capabilities?

### ISSUE THREAD

**Issue by PaulEdlund** [MicrosoftDocs/Azure-RMSDocs#1484]
[Enter feedback here]
Hi Team.  As per the user interface, many features are being deprecated in the Azure portal (like Network Scan Jobs) but this documentation makes no reference to that.  It also makes me wonder if the entire Azure Portal capabilities are being deprecated.  So some clarification might help for our customers.  

Thanks... Paul 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d99ffdbf-da4e-7e91-772a-146dc9a66f4c
* Version Independent ID: 0fbe983b-7c9d-4915-1a6f-5ae12bc8799e
* Content: [Install and configure the Azure Information Protection (AIP) unified labeling scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner-configure-install?tabs=azure-portal-only&source=docs)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner-configure-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner-configure-install.md)
* Service: **information-protection**
* Sub-service: **scanner**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by aashishr** [comment]
@Krishna ***@***.***> – can you take a look at this?

From: PaulEdlund ***@***.***>
Sent: Saturday, August 6, 2022 7:31 AM
To: MicrosoftDocs/Azure-RMSDocs ***@***.***>
Cc: Aashish Ramdas ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/Azure-RMSDocs] Notes about deprecated capabilities? (Issue #1484)


[Enter feedback here]
Hi Team. As per the user interface, many features are being deprecated in the Azure portal (like Network Scan Jobs) but this documentation makes no reference to that. It also makes me wonder if the entire Azure Portal capabilities are being deprecated. So some clarification might help for our customers.

Thanks... Paul

________________________________
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

  *   ID: d99ffdbf-da4e-7e91-772a-146dc9a66f4c
  *   Version Independent ID: 0fbe983b-7c9d-4915-1a6f-5ae12bc8799e
  *   Content: Install and configure the Azure Information Protection (AIP) unified labeling scanner<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Finformation-protection%2Fdeploy-aip-scanner-configure-install%3Ftabs%3Dazure-portal-only%26source%3Ddocs&data=05%7C01%7Caashishr%40microsoft.com%7C5e253faea08c4ffb2c0b08da77b83923%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637953930373996380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XR2y0dq8wAxNPKePk69sF5JK7FgYPOiZg371y5akuek%3D&reserved=0>
  *   Content Source: Azure-RMSDocs/deploy-aip-scanner-configure-install.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FAzure-RMSDocs%2Fblob%2Fmaster%2FAzure-RMSDocs%2Fdeploy-aip-scanner-configure-install.md&data=05%7C01%7Caashishr%40microsoft.com%7C5e253faea08c4ffb2c0b08da77b83923%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637953930373996380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ByixoT4oDa69BaDeiq%2FP0pVnHOvCYPPm2Sk%2FQ%2FpcpEQ%3D&reserved=0>
  *   Service: information-protection
  *   Sub-service: scanner
  *   GitHub Login: @aashishr<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faashishr&data=05%7C01%7Caashishr%40microsoft.com%7C5e253faea08c4ffb2c0b08da77b83923%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637953930373996380%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IQRmLvjlPU98dQVfKKPQLYBFabGAfsCCWmTMAyjTQPU%3D&reserved=0>
  *   Microsoft Alias: aashishr

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
