### ISSUE TITLE
Error in sample code provided on the page

### ISSUE THREAD

**Issue by thinkb4code** [MicrosoftDocs/Azure-RMSDocs#1485]
Hi Team,

When working the code sample provided in this page, I found one issue. The object is not declared before using it. Following are the details:

Section: Construct a Protection Profile and Engine
Error Location: In Sample code
Error Line: mipContext = MIP.CreateMipContext(mipConfiguration);
Error Line Number: 34
Error Detail:  The mipContext object is initialized in this line without declaration.

Solution: MipContext mipContext = MIP.CreateMipContext(mipConfiguration);

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a9bcd6-566c-001c-eb72-1fce9a6413de
* Version Independent ID: 58db6be5-e358-bb58-5667-a0c5999fd8d5
* Content: [Quickstart - Client application initialization - Protection SDK (C#)](https://docs.microsoft.com/en-us/information-protection/develop/quick-protection-app-initialization-csharp)
* Content Source: [mip/develop/quick-protection-app-initialization-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-protection-app-initialization-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
