### ISSUE TITLE
Confusing URL

### ISSUE THREAD

**Issue by paulohanlon** [MicrosoftDocs/Azure-RMSDocs#1486]
Why does the URL for this article end with "/byok-price-restrictions"? The word price isn't mentioned once in the article. This may be off putting to customers thinking of using BYOK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec4e182-6637-fa55-542f-5ae41bab759a
* Version Independent ID: 0bb87536-cb72-1374-5a1a-0964188cb744
* Content: [Bring Your Own Key (BYOK) details - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/byok-price-restrictions)
* Content Source: [Azure-RMSDocs/byok-price-restrictions.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/byok-price-restrictions.md)
* Service: **information-protection**
* Sub-service: **kms**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
