### ISSUE TITLE
Missing Information about EnableSaveMailAfterPropertySetInOnlineMode

### ISSUE THREAD

**Issue by GrayHodar** [MicrosoftDocs/Azure-RMSDocs#1490]
Under the article, we do not see any information about the attribute EnableSaveMailAfterPropertySetInOnlineMode for AdvancedSettings. It would be helpful to have detailed information mentioned in the article with the use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2891c430-f11e-c078-c356-1d98d5947f20
* Version Independent ID: cf3bae4a-3ca4-2d7d-cd34-097da78440d9
* Content: [Custom configurations - Azure Information Protection unified labeling client](https://learn.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide-customizations)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by zhang-yangchen** [comment]
@GrayHodar EnableSaveMailAfterPropertySetInOnlineMode saves the mail item after every property set operation when in Exchange Online Mode. By default, Exchange Online Mode saves the mail item after each instance a label is changed.

To enable this setting in AIP PSH with a policy named "Global", set EnableSaveMailAfterPropertySetInOnlineMode to True.
```PowerShell
Set-LabelPolicy -Identity Global -AdvancedSettings @{EnableSaveMailAfterPropertySetInOnlineMode="True"}
```

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
