### ISSUE TITLE
AIP data connector deprecation date unclear

### ISSUE THREAD

**Issue by gu1llaume-b** [MicrosoftDocs/Azure-RMSDocs#1492]
Hi,

In this [page](https://learn.microsoft.com/en-us/azure/information-protection/removed-sunset-services#azure-information-protection-analytics), it is mentioned the following:

"_Customers who already have AIP audit logs configured will continue to have those audit logs forwarded to their Log Analytics workspaces until **September 30, 2022**. At that point, customers will not be able to have any new AIP data forwarded to their Log Analytics workspace._

_Instead, we highly recommend that you use the Microsoft Purview compliance portal's activity explorer and content explorer, which provide comprehensive logging and reporting._"

However, if we refer to the Azure Information Protection data connector in Microsoft Sentinel, the retirement date has recently been changed to March 31, 2023 (instead of September 30, 2022). "_As of March 18, 2022, we are sunsetting the AIP analytics and audit logs public preview, and moving forward will be using the [Microsoft 365 auditing solution](https://docs.microsoft.com/microsoft-365/compliance/auditing-solutions-overview?WT.mc_id=Portal-fx). Full retirement is scheduled for **March 31, 2023**_."

As the only recommended alternative for the moment is to use the Microsoft Purview compliance portal (which does not allow to centralize log collection), when will the AIP data connector be retired? Will it be end of this month or in March 31, 2023? 

Thank you in advance for the clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06a83798-a8d9-9fd5-8100-95dbcbca9c3e
* Version Independent ID: 06a83798-a8d9-9fd5-8100-95dbcbca9c3e
* Content: [Removed and retired services - Azure Information Protection](https://learn.microsoft.com/en-us/azure/information-protection/removed-sunset-services#azure-information-protection-analytics)
* Content Source: [Azure-RMSDocs/removed-sunset-services.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/removed-sunset-services.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
