### ISSUE TITLE
There is a sentence we would like you to add about the timing of classification.

### ISSUE THREAD

**Issue by kk-koji** [MicrosoftDocs/Azure-RMSDocs#1493]
[Enter feedback here]
We want to add following sentence for UL
----------
When a document is labeled by using File Explorer, PowerShell, or the Azure Information Protection scanner: Visual markings are not immediately applied but are applied by the Azure Information Protection client when that document is opened in an Office app and the document is first saved.
----------

We notice this sentence on classic client docs
https://learn.microsoft.com/en-us/previous-versions/azure/information-protection/configure-policy-markings#when-visual-markings-are-applied

The site has mistranslation in Japanese, and the customer pointed it out.
However, since the above site cannot be feed backed for classic client contents, therefore we are requesting additions in this page.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 65dc2744-9266-8be2-60b4-1798617a7a5b
* Version Independent ID: 34a100e6-0f7d-ada8-f9f8-8b08b78e019b
* Content: [Classify using the Azure Information Protection unified labeling client](https://learn.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-classify)
* Content Source: [Azure-RMSDocs/rms-client/clientv2-classify.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/clientv2-classify.md)
* Service: **information-protection**
* Sub-service: **v2client**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
