### ISSUE TITLE
From Preview to Deprecated

### ISSUE THREAD

**Issue by myfope** [MicrosoftDocs/Azure-RMSDocs#1495]
Hi,

as the network Discovery feature will never be released and the portal itself is already read only (no configuration possible) it would be great to update this article accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0927bf-7a11-d800-f0ae-a1c0ce4dcb06
* Version Independent ID: ef830f65-1986-830e-be04-95d163d2de6c
* Content: [Tutorial - Install the Azure Information Protection (AIP) unified labeling scanner](https://learn.microsoft.com/en-us/azure/information-protection/tutorial-install-scanner)
* Content Source: [Azure-RMSDocs/tutorial-install-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/tutorial-install-scanner.md)
* Service: **information-protection**
* Sub-service: **aiplabels**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
