### ISSUE TITLE
oudated permissions

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/Azure-RMSDocs#1497]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e14c03d2-f258-52ca-4530-85430e0e11b7
* Version Independent ID: a65e7b8d-62f0-58c0-d60a-1cc143ade5a5
* Content: [Microsoft Information Protection (MIP) SDK setup and configuration](https://learn.microsoft.com/en-us/information-protection/develop/setup-configure-mip)
* Content Source: [mip/develop/setup-configure-mip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/setup-configure-mip.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
