### ISSUE TITLE
Add RSS feed to this site

### ISSUE THREAD

**Issue by kk-koji** [MicrosoftDocs/Azure-RMSDocs#1499]
[Enter feedback here]
Several users have requested that add RSS feed to this site.
Is it possible to add RSS feed as like following site?

https://learn.microsoft.com/en-us/defender-for-identity/whats-new
![image](https://user-images.githubusercontent.com/59611341/208586043-b9e9b5c5-0cae-41a6-a26f-16990de8cfac.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ba68bca-ce18-9eed-3ead-05a52ccfbd49
* Version Independent ID: 212526ff-d6c8-ab87-c218-dac87152c7f1
* Content: [Information & support for Azure Information Protection - AIP](https://learn.microsoft.com/en-us/azure/information-protection/information-support#information-about-new-releases-and-updates)
* Content Source: [Azure-RMSDocs/information-support.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/information-support.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
