### ISSUE TITLE
Foxit PDF Editor and Reader supports AIP in Windows, MAC and Mobile platform

### ISSUE THREAD

**Issue by thomasfoxit** [MicrosoftDocs/Azure-RMSDocs#1500]
Foxit announced new version 12.1 by adding new AIP labeling support features.
With Microsoft's updated SDK version, Foxit PDF Editor manages AIP label fully. Foxit PDF Reader also support AIP viewing features.

Platform supported by Foxit are Windows, MAC, iOS and Android.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF viewers for Microsoft Purview Information Protection](https://learn.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers#viewing-protected-pdfs-in-microsoft-edge-on-windows-or-mac)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
