### ISSUE TITLE
I believe there is a missing command in this guidance

### ISSUE THREAD

**Issue by bekirdur** [MicrosoftDocs/Azure-RMSDocs#1501]
[Enter feedback here]

I believe there is a missing command in this guidance.

I experienced errors and I ran this command as well. Otherwise, the office app is not allowed to create a flow for api.rms.rest.com.

**Grant-AdfsApplicationPermission -ClientRoleIdentifier 'd3590ed6-52b3-4102-aeff-aad2292ab01c' -ServerRoleIdentifier api.rms.rest.com**

You may consider adding it to the documentation.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ac18372-201a-0fb5-4ed5-6764330ea1e7
* Version Independent ID: 0c3de759-5357-c5d6-b532-a4cda941d7fb
* Content: [Active Directory rights management services mobile device extension for AIP](https://learn.microsoft.com/en-us/azure/information-protection/active-directory-rights-manage-mobile-device)
* Content Source: [Azure-RMSDocs/active-directory-rights-manage-mobile-device.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/active-directory-rights-manage-mobile-device.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
