### ISSUE TITLE
incorrect hyperlink in document

### ISSUE THREAD

**Issue by maharumman** [MicrosoftDocs/Azure-RMSDocs#1503]
[Enter feedback here]

The link for the [AIP Yammer community post](https://aka.ms/AIPAuditLogDeprecation) is no correct. it doesnt redirect to the appropriate resource

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06a83798-a8d9-9fd5-8100-95dbcbca9c3e
* Version Independent ID: 06a83798-a8d9-9fd5-8100-95dbcbca9c3e
* Content: [Removed and retired services - Azure Information Protection](https://learn.microsoft.com/en-us/azure/information-protection/removed-sunset-services)
* Content Source: [Azure-RMSDocs/removed-sunset-services.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/removed-sunset-services.md)
* Service: **information-protection**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
