### ISSUE TITLE
Add section for GCCH/DOD DNS records needed to properly bootstrap office clients for RMS

### ISSUE THREAD

**Issue by drdenson** [MicrosoftDocs/Azure-RMSDocs#1504]
Hi Team - note that office clients do not automatically bootstrap as this document suggests for sovereign cloud environments. 
 Additional DNS records are required to direct clients to appropriate GOV endpoints.  Of note, the GCCH/DOD config is technically documented in the AIP service description here:

https://learn.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-aip-premium-govt-service-description

That said, I think adding the same details to this document would make it more a more complete/robust reflection of our varied service offerings.  Please reach out internally to discuss as needed.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80433bf5-fdf0-92a2-6b0d-b559511d6ce6
* Version Independent ID: 99d5c616-c99a-dbcd-4ef9-67fcf77c5133
* Content: [Configuration for clients to use Office apps with Azure RMS from AIP](https://learn.microsoft.com/en-us/azure/information-protection/configure-office-apps#microsoft365-apps-office-2021-office-2019-office-2016-and-office-2013)
* Content Source: [Azure-RMSDocs/configure-office-apps.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-office-apps.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @aashishr
* Microsoft Alias: **aashishr**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
