### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/Azure-RMSDocs#1505]
[Enter feedback here]
The document states "The PolicyProfile::Settings constructor accepts four parameters, listed below:"
but it lists only 3

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e27fb2d0-9305-6e42-4c10-cb5e22c44c4e
* Version Independent ID: 0d09947c-a06e-c891-aa84-78de72801d4f
* Content: [Concepts - The Policy SDK profile object](https://learn.microsoft.com/en-us/information-protection/develop/concept-profile-engine-policy-profile-cpp)
* Content Source: [mip/develop/concept-profile-engine-policy-profile-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-policy-profile-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
