### ISSUE TITLE
Typo 2

### ISSUE THREAD

**Issue by cdietschrun** [MicrosoftDocs/Azure-RMSDocs#1506]
[Enter feedback here]

Typo -- docs say here we create a FileEngine::Settings object but then we create a PolicyEngine::Settings object

"Here we create a FileEngine::Settings object called engineSettings using the identity of the application user:

PolicyEngine::Settings engineSettings("

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b54cab9b-d73c-7886-c2e5-10c158f0b367
* Version Independent ID: 0567b870-19a6-fcaa-a4f5-aa726b947349
* Content: [Concepts - The Policy SDK engine object](https://learn.microsoft.com/en-us/information-protection/develop/concept-profile-engine-policy-engine-cpp)
* Content Source: [mip/develop/concept-profile-engine-policy-engine-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-policy-engine-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
