### ISSUE TITLE
Code documentation accidentally escapes HTML-encoded characters

### ISSUE THREAD

**Issue by lvkv** [MicrosoftDocs/Azure-RMSDocs#1518]
Many, if not all of the HTML-encoded characters like `&gt;` (AKA `>`) and `&lt;` (`<`) in the MIP SDK class reference Markdown are incorrectly escaped. This leads to hundreds of difficult-to-read entries when templates are involved. For example, this confusing thing:

```C++
public std::vector&lt;std::pair&lt;std::string, std::string&gt;&gt; GetProperties(uint32_t version)
```

should actually be rendered like this:

```C++
public std::vector<std::pair<std::string, std::string>> GetProperties(uint32_t version)
```

This is probably because whatever tool you're using to sync documentation is mistakenly escaping these sequences with a backslash (`\`) instead of leaving them alone:

```
public std::vector\&lt;std::pair\&lt;std::string, std::string\&gt;\&gt; GetProperties(uint32_t version)
```

This affects _at least_ all Markdown under `mip/develop/reference/`. It could be more widespread, but I haven't looked. Can we get this fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59b59a5c-f340-a00a-e971-d8ca8f6667cf
* Version Independent ID: 0538e714-6251-3c3f-9a0b-5cc682ccc1a3
* Content: [class FileHandler](https://learn.microsoft.com/en-us/information-protection/develop/reference/class_mip_filehandler)
* Content Source: [mip/develop/reference/class_mip_filehandler.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/reference/class_mip_filehandler.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
Thanks for calling this to our attention, @lvkv. We have fixed this issue. We appreciate your help. #please-close
