### ISSUE TITLE
Dates are inconsistent

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#202]
The SDK page at https://docs.microsoft.com/en-us/information-protection/develop/release-notes-rtm shows that it was update in February 2017, the heading shows February 2016, and the Note says SDK download dated 12/11/2015. Please review and resolve these inconsistencies.

**Comment by lleonard-msft** [comment]
Hi @DeanGross - Thanks for the suggestion.

Some differences between update dates are to be expected, as documentation updates are not necessarily synchronized to releases or release numbers.  The docs continue to be refined based on feedback and other requirements.  

The best measure of "freshness" (for lack of a better word) for a download is to check the Details on the [SDK download page](https://www.microsoft.com/en-us/download/details.aspx?id=38397) itself, which currently shows the last update as 28 November 2017, even though the version number of the SDK (or the language used to describe it) has not changed.
