### ISSUE TITLE
Manual download of scoped policies

### ISSUE THREAD

**Issue by staible-keyon** [MicrosoftDocs/Azure-RMSDocs#561]
How are the labels that need to be applied to a policy computed in the case the policy is downloaded manually from the AIP portal? As I understand the documentation, labels are merged depending on the groups assigned to the policy. If a user was a member of multiple scoped policies he'd inherit all the labels of all the scoped policies he's a member of if he uses the AIP client to download the policy. However if the policy is downloaded manually from the AIP admin portal there is no information about the user available that will use the downloaded policy. How does AIP determine which labels to add to this downloaded policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efbe5859-37fd-cd1a-b743-6311eb196728
* Version Independent ID: f5452d88-7a86-ebb1-9c8e-b6b88de72604
* Content: [Configure scoped policies for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/deploy-use/configure-policy-scope)
* Content Source: [Azure-RMSDocs/deploy-use/configure-policy-scope.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-use/configure-policy-scope.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@staible-keyon Thanks for your question.  It's now addressed in the disconnected computers client customization section (https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#support-for-disconnected-computers): "..exporting the policy does not support the scenario where a user belongs to more than one scoped policy". Exporting the policy is not a key scenario for Azure Information Protection.
