### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by frobnitzz** [MicrosoftDocs/Azure-RMSDocs#563]
The paragraph which starts "Select a predefined template" is written twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63e296ee-d3a5-8fea-7605-daaa88e4ebe0
* Version Independent ID: 46f9f6a6-13cd-1988-5e9e-fa9131b2d0bf
* Content: [Configure an Azure Information Protection label for protection](https://docs.microsoft.com/en-us/azure/information-protection/deploy-use/configure-policy-protection)
* Content Source: [Azure-RMSDocs/deploy-use/configure-policy-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-use/configure-policy-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@frobnitzz Hi!  Thanks for flagging this.  Now fixed.

**Comment by cabailey** [comment]
@frobnitzz Checking in - any reason why we can't now close this issue?

**Comment by frobnitzz** [comment]
@cabailey all good, thanks :)
