### ISSUE TITLE
Conflicting information

### ISSUE THREAD

**Issue by LeonardoFelippine** [MicrosoftDocs/Azure-RMSDocs#565]
Hello.

In this document, it is said "When you share Office documents by email, you can attach the document to an email that you protect, and the document is automatically protected with the same restrictions that apply to the email.", however, on the AIP classification and labeling FAQ (https://docs.microsoft.com/en-us/azure/information-protection/get-started/faqs-infoprotect#when-an-email-is-labeled-do-any-attachments-automatically-get-the-same-labeling), it is said exactly the opposite. Can you please clarify?

Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6de0a0a4-df7d-49fa-9d82-d6dde8a39a67
* Version Independent ID: 21509720-10d5-b218-8943-9bbb7f6ee335
* Content: [Classify & protect files & emails by using Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-classify-protect)
* Content Source: [Azure-RMSDocs/rms-client/client-classify-protect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-classify-protect.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@LeonardoFelippine Can you explain why you see this as conflicting information?  The attachment doesn't inherit the email's label, but it does inherit the email's protection settings, as stated in the FAQ ("..if the label for the email applies protection, that protection is applied to Office attachments").

►

**Comment by cabailey** [comment]
@LeonardoFelippine Hi, checking in because I haven't seen a response from you. Did my reply answer your question?

**Comment by LeonardoFelippine** [comment]
Hello, @cabailey . Sorry for the long delay in the reply.

As I understand it, a label can be comprised of visual markings, protection, or both.
So, in the text you quoted, if I apply a label to an email that sets visual markings and protection, only protection will be applied to the attachments?

Regards.

**Comment by cabailey** [comment]
@LeonardoFelippine  Can we close this issue, now?  I do not see a contradiction in the documentation.  There is an inconsistency in the product behavior and if this is important to you, I see that there's a UserVoice entry that you might want to consider adding your voting to (currently, only 2 votes):  https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/34471249-add-option-to-automatically-classify-attachment-do

**Comment by LeonardoFelippine** [comment]
Hello, Carol.


Sure, I thought I had mentioned it on my previous comment. Sorry about that.


Regards.

________________________________
De: Carol Bailey <notifications@github.com>
Enviado: quarta-feira, 22 de agosto de 2018 17:12:40
Para: MicrosoftDocs/Azure-RMSDocs
Cc: LeonardoFelippine; Mention
Assunto: Re: [MicrosoftDocs/Azure-RMSDocs] Conflicting information (#565)


@LeonardoFelippine<https://github.com/LeonardoFelippine> Can we close this issue, now? I do not see a contradiction in the documentation. There is an inconsistency in the product behavior and if this is important to you, I see that there's a UserVoice entry that you might want to consider adding your voting to (currently, only 2 votes): https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/34471249-add-option-to-automatically-classify-attachment-do
