### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by stephenegriffin** [MicrosoftDocs/Azure-RMSDocs#568]
I don't see any obvious place in this documentation where the concept of a "label" is clearly defined. It just assume you know what a label is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f28cca2a-061c-7526-730e-269f749a8512
* Version Independent ID: 1db6aab8-dbb5-fe09-c78c-448b78f62bbe
* Content: [New Azure Information Protection label](https://docs.microsoft.com/en-us/azure/information-protection/deploy-use/configure-policy-new-label)
* Content Source: [Azure-RMSDocs/deploy-use/configure-policy-new-label.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-use/configure-policy-new-label.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@stephenegriffin  Hi Stephen. That's a good observation. "Label" as a generic term is usually understood in context. However, if we were to provide the following definition for an Azure Information Protection label, would you find this helpful?

Azure Information Protection label: An item that applies a classification value to documents and emails, and can optionally protect them. The Azure Information Protection client displays labels for your users in Office apps and when users right-click from File Explorer. These labels can also be applied by using PowerShell and the Azure Information Protection scanner.

**Comment by stephenegriffin** [comment]
something like that would work. I found more context at https://docs.microsoft.com/en-us/azure/information-protection/understand-explore/what-is-information-protection, which still doesn't actually say what a label is, but gives context to help guess.

I also found this: https://support.office.com/en-us/article/Overview-of-labels-af398293-c69d-465e-a249-d74561552d30, which does a much better job of explaining the concept of a label without assuming the reader just knows.

**Comment by msmbaldwin** [comment]
https://docs.microsoft.com/en-us/azure/information-protection/deploy-use/configure-policy now contains the following clarification:

---
The policy contains labels and settings:

Labels apply a classification value to documents and emails, and can optionally protect this content. The Azure Information Protection client displays these labels for your users in Office apps and when users right-click from File Explorer. These labels can also be applied by using PowerShell and the Azure Information Protection scanner.

The settings change the default behavior of the Azure Information Protection client. For example, you can select a default label, whether all documents and emails must have a label, and whether the Azure Information Protection bar is displayed in Office apps.
---

Closing this Issue, as internal MS employees ought to contact us directly.
