### ISSUE TITLE
Export a File without IRM

### ISSUE THREAD

**Issue by nirmalkumarv** [MicrosoftDocs/Azure-RMSDocs#579]
The document doesn't mention anything about how one can export a file from the IRM Folder. I mean, in my scenario, the File Should be in IRM until the Draft Version. Once its crosses the Draft Mode, i need to move to a NON-IRM Library. So i need to export to a PDF. How to achieve this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5089be5-ab21-9713-24cf-e88b3de6596f
* Version Independent ID: 00db5cf0-54f1-8a93-1ff9-75c3848e3869
* Content: [Configure usage rights for Azure Rights Management - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights)
* Content Source: [Azure-RMSDocs/configure-usage-rights.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-usage-rights.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@nirmalkumarv  As we discussed over email, what you are asking for is not a usage right but how SharePoint is designed to work with IRM-protected libraries. You can download a document from an IRM-protected library, unprotect it, and then upload to a non-IRM protected library. Simply moving a protected document from one location to another should not remove the protection.

**Comment by lar1c** [comment]
Can you please confirm that Set-IRMConfiguration -DecryptAttachmentForEncryptOnly $true is available to configure ?
