### ISSUE TITLE
How to extend protection to all users with permission on SharePoint

### ISSUE THREAD

**Issue by JMyner** [MicrosoftDocs/Azure-RMSDocs#584]
"By default, the protection is restricted to the person who downloads the document. You can change this default with a configuration option that extends the protection to all users who have access to the document on SharePoint, or to a group that you specify."

How can you configure an IRM policy to extend the protection to all users who have access to the document in SharePoint online?
I cannot find any documentation on this within the configuration articles. Is this a feature?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e647478-e7b5-549a-040d-11c34e2fc2a8
* Version Independent ID: 9660a681-a663-2f60-4148-beac607d2f34
* Content: [How Office apps & services support Azure RMS from AIP](https://docs.microsoft.com/en-us/azure/information-protection/office-apps-services-support#sharepoint-online-and-sharepoint-server)
* Content Source: [Azure-RMSDocs/office-apps-services-support.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/office-apps-services-support.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@JMyner  Look for the SharePoint IRM option "Allow group protection", documented here: https://support.office.com/en-us/article/apply-information-rights-management-to-a-list-or-library-3bdb5c4e-94fc-4741-b02f-4e7cc3c54aa1

**Comment by JMyner** [comment]
Unless I am missing something, that article tells me I can enter in a single groups name to allow sharing within that group.

However, the original article suggests that I am able to use a default configuration option to allow sharing with all users who have access to the document on SharePoint.

Am i missing something here like a group name which picks up on all the members who currently have access to the document? Or is the original documentation wrong?

**Comment by cabailey** [comment]
@JMyner I'm not sure I understand your question.  The original article says "You can change this default [the protection is restricted to the person who downloads the document] with a configuration option .."  

So for example, you don't set this option and download the document. You then email it to somebody who has access to it on SharePoint - they won't be able to open it. Only you can open it.  But if you do set this option and specify the name of the group that has permissions to the document library in SharePoint, when you email the downloaded document to a member of that group, they will be able to open it.  Or, you set this option and specify the name of a group that contains users who have no access to this document in SharePoint but when you email them the downloaded copy, they will be able to open it.  Both configurations could be valid scenarios, depending on your requirements.

That's my understanding of how this option works.  It seems to match with another explanation I found in this helpful blog post: http://dotnetmafia.com/blogs/dotnettipoftheday/archive/2015/02/03/configuring-information-rights-management-irm-on-a-document-library-in-office-365.aspx

**Comment by JMyner** [comment]
@cabailey That is my understanding of the group protection configuration as well.

The issue here is in the documentation then "You can change this default with a configuration option that extends the protection to **all users who have access to the document on SharePoint**, or to a group that you specify."

The group protection is only able to extend the protection to a group that you specify.

It is not always the case that group protection is able to extend protection to all users who have access to the document on SharePoint. This is only possible when access to the document library is managed with a single group.

This becomes an issue when managing SharePoint environments, in order to apply IRM I will need to create an additional group with all members of the groups used to provide access to the document library. As I cannot nest the groups, when the groups used to provide access to the document library are updated with new staff the group used for IRM will have to be updated manually.

I would suggest that the documentation is updated to  "You can change this default with a configuration option that extends the protection to a group that you specify." As there is no option for this setting to select all users that have access to the document on SharePoint.

**Comment by cabailey** [comment]
@JMyner The intent behind the original wording was to give two typical example scenarios (the ones we hear most often) for how you might use this option. If you interpreted this as two different options, I can see why you got confused. I'll look at clarifying the wording. We always hear that having example scenarios is helpful in the documentation rather than just how to specify a value for an option. Thank you for pointing out that document libraries are not always managed with a single group (the first example scenario).

**Comment by cabailey** [comment]
@JMyner Doc is updated now.
