### ISSUE TITLE
Rekey instructions don't indicate that a new security world not required if one already exists

### ISSUE THREAD

**Issue by andyschan** [MicrosoftDocs/Azure-RMSDocs#602]
The section https://docs.microsoft.com/en-us/azure/information-protection/operations-customer-managed-tenant-key#rekey-your-tenant-key refers you to https://docs.microsoft.com/en-us/azure/information-protection/plan-implement-tenant-key#implementing-byok-for-your-azure-information-protection-tenant-key for detailed instructions, which points you to "How to generate and transfer HSM-protected keys for Azure Key Vault" (https://docs.microsoft.com/en-us/azure/key-vault/key-vault-hsm-protected-keys#step-3-generate-your-key). This final one says that the 1st step is to generate a new Thales security world, though; this should indicate that a new security world is only necessary if one doesn't already exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a7e847-721a-8064-5d47-abcef59ec12f
* Version Independent ID: 9031c4fb-1e77-25cc-25ca-ad1ab07e7dd7
* Content: [Customer-managed - AIP tenant key life cycle operations](https://docs.microsoft.com/en-us/azure/information-protection/operations-customer-managed-tenant-key)
* Content Source: [Azure-RMSDocs/operations-customer-managed-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/operations-customer-managed-tenant-key.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Fixed as per offline discussion.

**Comment by cabailey** [comment]
#please-close
