### ISSUE TITLE
Fix links to SDK documentation from external pages

### ISSUE THREAD

**Issue by mikekaganski** [MicrosoftDocs/Azure-RMSDocs#631]
https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rights-management and https://docs.microsoft.com/en-us/windows/desktop/SrvNodes/rms-code-samples-and-tools refer to "not-regularly-updated" https://docs.microsoft.com/en-us/previous-versions/windows/desktop/msipc/microsoft-information-protection-and-control-client-portal. Please update the links to point to actualized content.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22a9fe14-5439-0fb2-d89d-6c2d225eefad
* Version Independent ID: f326cbdb-3f66-c69b-1848-3c60d277c513
* Content: [Rights Management Services SDK 2.1](https://docs.microsoft.com/en-gb/azure/information-protection/develop/microsoft-information-protection-and-control-client-portal)
* Content Source: [Azure-RMSDocs/Develop/microsoft-information-protection-and-control-client-portal.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/Develop/microsoft-information-protection-and-control-client-portal.md)
* Service: **information-protection**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **alleonar**

**Comment by BryanLa** [comment]
This should be resolved in issue https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/632. 

#please-close
