### ISSUE TITLE
include service cost of storing information

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#640]
include service cost of storing information for AIP reporting..

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @bakerm00  Azure Information Protection uses Azure Log Analytics for storage and you'll find pricing information for this service on their pricing page, first link in the prerequisites table.
