### ISSUE TITLE
example 2 needs the correct GUID Applied

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#645]
just to make sure people don't get confused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc4f87ed-6649-6998-889b-58f14556db29
* Version Independent ID: 46468916-b0f0-56b9-23d7-add664cc49b1
* Content: [Configure Exchange Online mail flow rules for Azure Information Protection labels](https://docs.microsoft.com/en-us/azure/information-protection/configure-exo-rules)
* Content Source: [Azure-RMSDocs/configure-exo-rules.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-exo-rules.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bakerm00 I see what you mean …. result of testing multiple times with different labels, I suspect!  Will get this fixed today. Thanks for flagging.

**Comment by cabailey** [comment]
Fixed now.
