### ISSUE TITLE
Another exception required - KeyTransferRemote.exe -ModifyAcls needs -KeyAppName for existing key, not simple

### ISSUE THREAD

**Issue by andyschan** [MicrosoftDocs/Azure-RMSDocs#663]
In "Part 1: Transfer your HSM key to Azure Key Vault", it says to follow the instructions at  "Implementing bring your own key (BYOK) for Azure Key Vault" (https://azure.microsoft.com/documentation/articles/key-vault-hsm-protected-keys/#implementing-bring-your-own-key-byok-for-azurekey-vault), with mentioned exceptions. Another exception that needs to be added is that at https://docs.microsoft.com/en-us/azure/key-vault/key-vault-hsm-protected-keys#step-4-prepare-your-key-for-transfer, the "KeyTransferRemote.exe -ModifyAcls" command needs to be adjusted as follows to change the "KeyAppName" parameter; the documentation specifies to use "-KeyAppName simple", but for existing AD RMS keys the parameter needs to be "-KeyAppName mscapi". This can be confirmed by running the Thales command "nfkinfo -k" and viewing the "AppName" parameter for the key in question:

KeyTransferRemote.exe -ModifyAcls -KeyAppName mscapi -KeyIdentifier contosokey -ExchangeKeyPackage BYOK-KEK-pkg-NA-1 -NewSecurityWorldPackage BYOK-SecurityWorld-pkg-NA-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12cb8a9-1687-36c0-0dcc-c390e9ba32ca
* Version Independent ID: 3f2594b5-08f6-7c7e-7b5a-5995262489da
* Content: [Migrate HSM-protected key to HSM-protected key - AIP](https://docs.microsoft.com/en-us/azure/information-protection/migrate-hsmkey-to-hsmkey)
* Content Source: [Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thanks for your feedback! Investigating.

**Comment by cabailey** [comment]
"mscapi" is now incorporated into the instructions - thanks again for this feedback!
#please-close
