### ISSUE TITLE
Part 1: Transfer your HSM key to Azure Key Vault requires another exception (identify keyidentifier)

### ISSUE THREAD

**Issue by andyschan** [MicrosoftDocs/Azure-RMSDocs#666]
In "Part 1: Transfer your HSM key to Azure Key Vault" of this article, the reference to "Implementing bring your own key (BYOK) for Azure Key Vault" (https://docs.microsoft.com/en-us/azure/key-vault/key-vault-hsm-protected-keys#step-4-prepare-your-key-for-transfer) requires another exception:

In step 4.1 at https://docs.microsoft.com/en-us/azure/key-vault/key-vault-hsm-protected-keys#step-4-prepare-your-key-for-transfer. for the "-KeyIdentifier contosokey" parameter "contosokey" needs to be replaced with the identifier for the existing key. But, we have no direction on how to determine this identifier; it took a conference call with Premier, Thales, MCS and the customer to determine this:

In the AD RMS console, expand "&lt;clustername&gt; (Local)", expand "Trust Policies", and select "Trusted Publishing Domains". In the Details pane, select the row for the pertinent TPD; the value shown for "Key Container" is what is used for the "-KeyIdentifier" parameter for step 4.1 (the "KeyTransferRemote.exe -ModifyAcls -KeyAppName simple -KeyIdentifier contosokey" parameter; contosokey is replaced with the "Key Container" value from the AD RMS console).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12cb8a9-1687-36c0-0dcc-c390e9ba32ca
* Version Independent ID: 3f2594b5-08f6-7c7e-7b5a-5995262489da
* Content: [Migrate HSM-protected key to HSM-protected key - AIP](https://docs.microsoft.com/en-us/azure/information-protection/migrate-hsmkey-to-hsmkey#part-1-transfer-your-hsm-key-to-azure-key-vault)
* Content Source: [Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-hsmkey-to-hsmkey.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Thanks for your feedback! Investigating.

**Comment by cabailey** [comment]
Updated the instructions as agreed offline. Your help was much appreciated!
#please-close
