### ISSUE TITLE
Encrypt-Only not available for label configuration

### ISSUE THREAD

**Issue by stevep4** [MicrosoftDocs/Azure-RMSDocs#676]
"Exchange Online is rolling out a new option, Encrypt-Only. This option is not available for label configuration."

Will it ever be?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4b8020d-3f87-1a2d-74e4-f132640010c4
* Version Independent ID: cb6f52e8-2d35-d899-8011-6f16058490de
* Content: [Configure an Azure Information Protection label for protection](https://docs.microsoft.com/en-gb/azure/information-protection/configure-policy-protection#example-configurations)
* Content Source: [Azure-RMSDocs/configure-policy-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by stevep4** [comment]
Hi @cabailey, Thank you so much for a great summary, that's really useful.... being new to AIP with what it can (and can't) do for me in emails, I'm finding it a bit of a minefield of information to figure out how I can achieve what I'd like. For me, I think if in AIP label Protection settings, along with the option for "In Outlook apply Do Not Forward", there was a "In Outlook apply Encrypt" then that would do the trick, nothing needed client side other than an AIP tool tip explainer, and then trap the header in Exchange and do the work, similar to Example 2, but with the benefit that the labels only show in Outlook and would be hidden in Word etc. But I can understand that automating the Exchange rule probably wouldn't be possible, so maybe that's too difficult to implement. Ideally what I'd like is a label, say, "Commercial" which internally sets some protection options, but when emailed externally the recipient can get to without needing to be in the AIP permissions (we don't want AnyAuthenticated)... i.e. for an external recipient, in Exchange kind of almost remove the permissions and set DNF, *or* have some sort of dynamic AIP permission based on the Exchange recipient... it just doesn't seem possible, so I need to have two labels, one "Commercial" for internal use, and one "Commercial Encrypt" for people to use to email out to external folk. Kind of annoying... unless I'm missing something? Thanks again for your time above, much appreciated.

**Comment by cabailey** [comment]
@stevep4  I don't think we could support a label that configures Exchange Online mail flow rules  - for a start, there's no dependency that customers using Azure Information Protection labels have to use Exchange Online (the same way we can't mandate that customers only use Outlook versions that support the Encrypt-Only action).  From what you're describing with two different lots of protection settings, yes, I think you need two different labels and educate users which one to select.  Or, you have one label with no protection configured and use Exchange Online mail flow rules to apply one set of protection for internal users, and a different set of protection for external users.  But you can't show the label only in Outlook - file that UserVoice entry for this request.

It's worth filing a request for the Encrypt-Only action as well if you can't find it already filed. Although it's problematic to implement, you might get an official answer from the product group.

**Comment by stevep4** [comment]
Hi @cabailey thanks again for your reply, it's really appreciated. It's good to know that I don't think I've particularly missed anything and am on the right lines. I'll get a request or two into UserVoice! :-)

**Comment by cabailey** [comment]
@msmbaldwin #please-close
