### ISSUE TITLE
Tell us how to log OUT of the AIP client 

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/Azure-RMSDocs#687]
Once the client is installed it seems impossible to log out of it, which is crazy.. please tell us how to log out so we can log into it as another logon!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection unified labeling client - Version release information](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@blouwagie  Is your question specific to the unified labeling client, where you filed this question?  We have this for the Azure Information Protection client but I don't know if it works for the new, preview client:  https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#sign-in-as-a-different-user

However, unlike Office, the Azure Information Protection client doesn't support multiple accounts on the same computer (documented here https://docs.microsoft.com/en-us/azure/information-protection/requirements#applications). I don't think this changes for the unified labeling client.

**Comment by cabailey** [comment]
@blouwagie  Confirmed: The signing out behavior for the Azure Information Protection unified labeling client is the same as for the Azure Information Protection client.  So, use the same instructions to sign out of the client so you can then sign in as a different user: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#sign-in-as-a-different-user

**Comment by cabailey** [comment]
@msmbaldwin #please-close

**Comment by markgort86** [comment]
I used the instruction on the following page: https://docs.microsoft.com/nl-nl/azure/information-protection/rms-client/clientv2-admin-guide-customizations#sign-in-as-a-different-user to sign-in as a different user in the new Azure Information Protection Client. But i'm not able to sign in again with a different user. Is there someone who can help me further? The status of the client is "Working offline". On the page i'm referencing to after deleteting the TokenCache file and cookies from Internet Explorer there must pop-up a sign-in box.

**Comment by cabailey** [comment]
@markgort86  Hi Mark. As you know, the documentation says "If you do not see a prompt in your Office application to sign in to the Azure Information Protection service, return to the Microsoft Azure Information Protection dialog box and select Sign in from the updated Client status section"  If you have closed and reopened your Office apps without being prompted to sign in again, and you're not seeing that Sign in option in the client status section, please open a support ticket with Microsoft.

**Comment by markgort86** [comment]
Okay thanks for this very fast feedback. I'm missing the Sign in option in the client status. I will open a support ticket with Microsoft.
