### ISSUE TITLE
Clarity of Office 365 for Mac capabilities

### ISSUE THREAD

**Issue by kayleeefish** [MicrosoftDocs/Azure-RMSDocs#704]
It would be good, for clarity, if you could confirm the Mac Office requirements for consuming content.

For example, can Office 365 Business (specifically Business, not ProPlus) consume content on a Mac?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f75a386a-bf8d-8eb2-8357-98ad613db056
* Version Independent ID: 002a6cae-93c8-c369-57a1-d75a591a75d7
* Content: [Application support for RMS data protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements-applications)
* Content Source: [Azure-RMSDocs/requirements-applications.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements-applications.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@kayleeefish I think Office for Mac editions follow the same behavior as Office for Windows - as in, all editions support consumption.  But I'll check and confirm.

**Comment by cabailey** [comment]
@kayleeefish Now officially confirmed and the page is updated.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
