### ISSUE TITLE
RMS Developer's Corner (blog) not more available

### ISSUE THREAD

**Issue by nicolgit** [MicrosoftDocs/Azure-RMSDocs#707]
please check

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c02a404-c389-4d1a-160b-b506310ac027
* Version Independent ID: 5a8feb29-5274-1373-3869-34d79d220f89
* Content: [Azure Information Protection Developer's Guide](https://docs.microsoft.com/en-us/azure/information-protection/develop/developers-guide)
* Content Source: [Azure-RMSDocs/develop/developers-guide.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/develop/developers-guide.md)
* Service: **information-protection**
* GitHub Login: @lleonard-msft
* Microsoft Alias: **bryanla**

**Comment by lleonard-msft** [comment]
@BryanLa - FYI

**Comment by BryanLa** [comment]
Thanks for reporting this, @nicolgit, and apologies for the delay..

I believe this was cleaned up a few days after you reported it, in some related work I was doing. I'll close for now, but please let us know if you have any additional concerns.

@msmbaldwin #please-close
