### ISSUE TITLE
PDF reader preference

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#713]
Why do you prefer the Adobe reader over the Foxit reader?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by kkanakas** [comment]
We have partnerships with both companies and provide them with the same interfaces for integration. Most customers prefer Adobe's PDF experience and based on the feedback of our customers of  both companies, we decided that preference for Adobe's reader would be the right step forward. 
Foxit is our partner as well and we will continue to working with them.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
