### ISSUE TITLE
DecryptAttachmentForEncryptOnly

### ISSUE THREAD

**Issue by michevnew** [MicrosoftDocs/Azure-RMSDocs#716]
Is this parameter supposed to be available yet? I've tested multiple tenants, I don't have it in any of them. It's not even listed in the definition of the Set-IRMConfiguration cmdlet so it doesn't look like it's a permission issue. Has the rollout completed yet?

Similarly for the DecryptAttachmentFromPortal parameter.

If there are any requirements in terms of licenses, admin roles or anything else, can you please update the document accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5089be5-ab21-9713-24cf-e88b3de6596f
* Version Independent ID: 00db5cf0-54f1-8a93-1ff9-75c3848e3869
* Content: [Configure usage rights for Azure Rights Management - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights#encrypt-only-option-for-emails)
* Content Source: [Azure-RMSDocs/configure-usage-rights.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-usage-rights.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@michevnew I'm not aware of any reasons why these parameters wouldn't be available for tenants using Exchange Online, but I'll see if I can find out anything more for you. When I originally documented them, they weren't in the PowerShell help, but I see they are now:  https://docs.microsoft.com/en-us/powershell/module/exchange/encryption-and-certificates/set-irmconfiguration?view=exchange-ps

There's nothing in this help from the Exchange team that suggests you need anything different from the other parameters, so this might need a support call to that team to resolve this issue.  However, I will update this if I find out anything that will help you.

**Comment by cabailey** [comment]
@michevnew After investigating, it seems they have removed the DecryptAttachmentFromPortal parameter, but you should be able to use the original parameter you asked about, DecryptAttachmentForEncryptOnly. I confirmed that it's deployed worldwide, not still rolling out.  So if you can't run it, please do open a support ticket with the Exchange team.

I've updated the page to reflect the removed parameter.

**Comment by cabailey** [comment]
@msmbaldwin #please-close
