### ISSUE TITLE
The Install-AIPScanner powershell command doesn't exist.

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/Azure-RMSDocs#736]
If you get an error that the Install-AipScanner powershell command doesn't exist, verify that you have the Azure Information Protection Client installed, then import the powershell module with....

cd "C:\Program Files (x86)\Microsoft Azure Information Protection\powershell\AzureInformationProtection"

import-module .\AzureInformationProtection.psd1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#install-the-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Elizabeth - thanks for your tips!  Yes, installing the Azure Installation Protection client is included in the prerequisites table.  I'm told you shouldn't have to manually import the module but it should automatically load when you run a cmdlet from the AzureInformationProtection module.  If that didn't happen for you, can you tell me what version of the Azure Information Protection client you have, and what version of PowerShell you're running ($PSVersionTable in a PowerShell session) on what version of the operating system?

**Comment by cabailey** [comment]
@ElizabethGreene : Hi Elizabeth, any update on the import requirement you commented on?

**Comment by ElizabethGreene** [comment]
I saw it on a Server 2016 Azure VM, but I'm not able to Repro it on my Win10 1809 machine now.  I'll grab the version details in the morning.  Thanks!

**Comment by ElizabethGreene** [comment]
I am inexplicably unable to reproduce this on the VM where I was experiencing the issue now.  Odd.

**Comment by cabailey** [comment]
@ElizabethGreene OK, I appreciate the update (and your closing the issue). Please do reopen this if you can reproduce it.
