### ISSUE TITLE
Sign Up for RMS for Individuals Issue

### ISSUE THREAD

**Issue by JohnAClark** [MicrosoftDocs/Azure-RMSDocs#738]
When I follow steps 1, 2 and 3 to request an RMS for Individuals account as mentioned above I am never allowed to actually set up an RMS for Individuals Account for my personal (non-corporate) email address.  I enter my personal email address and am told "That looks to be a personal email address. Enter your work address so we can connect you with others in your company..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e15dd52f-475d-3d6e-c025-7fff439c5501
* Version Independent ID: 15ed2b81-c0ea-7101-aa0c-4f6a3e30db19
* Content: [RMS for individuals and Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-for-individuals)
* Content Source: [Azure-RMSDocs/rms-for-individuals.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-for-individuals.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Yes, that's expected.  From the introduction::" ..this free sign-up service can create an account in Azure Active Directory for a user. As a result, these users can now authenticate by using their company email address and then read the protected files on computers or mobile devices."  It's not designed for personal email accounts, but work email accounts for organizations that aren't using Office 365 or Azure AD.

**Comment by cabailey** [comment]
I'm not seeing the conflict - where does it say in these instructions that personal email addresses are supported for this subscription?

**Comment by JohnAClark** [comment]
Ah, you are right, my mistake.  I was reading “organization” but not thinking corporate organization.  My small business uses what could be defined as personal email accounts to transact business.  Thank you for the clarification.

**Comment by cabailey** [comment]
#please-close
