### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by cthulhu-uu** [MicrosoftDocs/Azure-RMSDocs#768]
The link to download the Azure Information Protection plugin pulls up the following error: "We are sorry, the page you requested cannot be found."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@cthulhu-uu  Sorry to hear that - is it still a problem?  The link for "Install the Adobe plug-in" works for me when I tried it - resolves to https://helpx.adobe.com/acrobat/kb/mip-plugin-download.html.  The other download links are working for me, as well.

**Comment by cabailey** [comment]
@cthulhu-uu  Any update or can this thread be closed?

**Comment by cabailey** [comment]
#please-close
