### ISSUE TITLE
mistyping

### ISSUE THREAD

**Issue by jojoblaze** [MicrosoftDocs/Azure-RMSDocs#772]
Under the section "Implement an authentication delegate", the point 5 states
:
Add the public string AcquireToken() class. This class should accept Microsoft.InformationProtection.Identity....

I think AcquireToken is a method, not a class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0261682a-a7cb-7362-4386-4fc77975ebf6
* Version Independent ID: 4ddc7104-90e0-1468-22b9-9b96344aa205
* Content: [Quickstart - Initialization for Microsoft Information Protection (MIP) SDK C# clients](https://docs.microsoft.com/en-us/information-protection/develop/quick-app-initialization-csharp)
* Content Source: [mip/develop/quick-app-initialization-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-app-initialization-csharp.md)
* Service: **information-protection**
* GitHub Login: @tommoser
* Microsoft Alias: **tommos**

**Comment by msmbaldwin** [comment]
We updates this to make it clear that it is a method, not a class. Thanks you for the feedback! #please-close
