### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by thedrum808** [MicrosoftDocs/Azure-RMSDocs#774]
Is MS Edge supported for opening encrypted PDFs using Windows Information Protection?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13769f09-0e43-6597-be6d-abe0bfc8caa7
* Version Independent ID: eb1e4a9d-a262-a614-39e7-feba86d83151
* Content: [Protected PDF readers for Microsoft Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/protected-pdf-readers)
* Content Source: [Azure-RMSDocs/rms-client/protected-pdf-readers.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/protected-pdf-readers.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@thedrum808  No, a browser by itself doesn't have the capability to decrypt protected content. That's why we list readers that have this capability.

**Comment by thedrum808** [comment]
Got it, thanks! #pleaseclose
