### ISSUE TITLE
Visual C++ Redistributable for Visual Studio 2015 needs to be installed

### ISSUE THREAD

**Issue by tdracz** [MicrosoftDocs/Azure-RMSDocs#777]
The whole feature doesn't seem to work without it. An exception "LoadLibrary failed for: [sdk_wrapper_dotnet.dll]" is thrown otherwise. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14c03d2-f258-52ca-4530-85430e0e11b7
* Version Independent ID: a65e7b8d-62f0-58c0-d60a-1cc143ade5a5
* Content: [Microsoft Information Protection (MIP) SDK setup and configuration](https://docs.microsoft.com/en-us/information-protection/develop/setup-configure-mip#configure-your-client-workstation)
* Content Source: [mip/develop/setup-configure-mip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/setup-configure-mip.md)
* Service: **information-protection**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by tommoser** [comment]
Thanks! We're working on adding that to the docs.

**Comment by msmbaldwin** [comment]
Thanks, @tdracz!  You can see the addition to the docs at https://docs.microsoft.com/information-protection/develop/setup-configure-mip#ensure-your-app-has-the-required-runtime

**Comment by tdracz** [comment]
Awesome, thanks!
