### ISSUE TITLE
Service Account rights, what machine are you talking about and link to How-to

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/Azure-RMSDocs#779]
Hi
I copied the relevant text from the document below.
1. When you talk about the Service Account needing those rights, please indicate WHICH machine(s) the service account needs that right on.
2. Please link to articles that explain how to access those rights.

This service account has the following requirements:

- Log on locally right. This right is required for the installation and configuration of the scanner, but not for operation. You must grant this right to the service account but you can remove this right after you have confirmed that the scanner can discover, classify, and protect files. If granting this right even for a short period of time is not possible because of your organization policies, see the Deploying the scanner with alternative configurations section.

- Log on as a service right. This right is automatically granted to the service account during the scanner installation and this right is required for the installation, configuration, and operation of the scanner. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@blouwagie  Thanks for your feedback, I'm looking into how to make this clearer in the doc.  The scanner runs on a Windows Server computer, so this row ("Service account to run the scanner service") runs on the Windows Server computer that's listed first in the table. The account rights you listed are standard user right assignments that you can configure with Active Directory Group Policy. I couldn't find a current Microsoft link for how to use Group Policy to configure these security settings, but you should be able to find other references with a web search.

**Comment by cabailey** [comment]
Last week the following changes were made for this row in the scanner prerequisites table:

- Changed the wording for the scanner service account to clarify in the "More information" column that this account runs on the Windows Server computer that runs the scanner.
- For the "Log on locally right" and "Log on as a service right", these are now referred to with their full technical name of "user right assignment". This change should help those unfamiliar with these Windows user rights to identify documentation to configure them for their version of Windows Server, or give this information to their Active Directory administrator. 
- This row is also moved to be immediately after the Windows Server computer row, so these two prerequisites are grouped together.

**Comment by blouwagie** [comment]
Thank you!


Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)

http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call is needed)

**Comment by cabailey** [comment]
#please-close
