### ISSUE TITLE
MKLink Example incorrect

### ISSUE THREAD

**Issue by MarcHowe** [MicrosoftDocs/Azure-RMSDocs#780]
The mklink example provided is incorrectly formatted. 

It states:
"For example, using the Mklink command: mklink /j C:\Users\aipscannersvc\AppData\Local\Microsoft\MSIP\Scanner\Reports D:\Scanner_reports"

The &lt;link&gt; is the first parameter after options so should read: 

"For example, using the Mklink command: mklink /j D:\Scanner_reports C:\Users\aipscannersvc\AppData\Local\Microsoft\MSIP\Scanner\Reports "

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#using-the-scanner-with-alternative-configurations)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@MarcHowe  Thanks for flagging this.  Now fixed.

**Comment by cabailey** [comment]
#please-close
