### ISSUE TITLE
Make more clear when you need cloud app security

### ISSUE THREAD

**Issue by blouwagie** [MicrosoftDocs/Azure-RMSDocs#782]
Hi

The section copied below is NOT clear. We spent a long time with Microsoft support about the confusion caused by the text below. Please make sure that you more clearly say that ONLY ON Premise Sharepoint is supported directly *without* also installing Cloud App Security. See also https://docs.microsoft.com/en-us/cloud-app-security/azip-integration

This is the section of this document I refer to is:

Sites and libraries for SharePoint Server 2016 and SharePoint Server 2013. SharePoint 2010 is also supported for customers who have extended support for this version of SharePoint.

To scan and label files on cloud repositories, use Cloud App Security.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@blouwagie  I wasn't sure I understand your feedback until I read your other post, saying you were trying to use the scanner to protect documents in SharePoint Online.  So it sounds as if we change the current sentence to "To scan and label files on cloud repositories, use Cloud App Security instead of the scanner." it would address this clarification.

**Comment by blouwagie** [comment]
Hi,
Yes that would help. But and make that sentence stand out. I added a few
more words:

"To scan and label files on cloud repositories, do not use the AIP scanner,
use Cloud App Security instead"

After spending days on this I have come to realize that

There are three parts that each work on RMS but are needed for different
situations.
- AIP is really for front end settings using full Microsoft Office clients
only. I.e. a user who has the AIP viewer installed on a computer and who
works with Microsoft Office fat clients.
- AIP Scanner is for when you have files on your own servers/infrastructure
(even if the server is in the cloud), and is to set/review labels and
protection.
- CAS is for when you have files in the cloud and / or use cloud
applications to access your files.

You should show that breakdown in this document and in other related
documents please

Thank you
Bart

**Comment by cabailey** [comment]
The sentence is now updated. As I explained in my other response, the technical documentation for a service focuses on what it can do, not what it can't do,

The overview information for Azure Information Protection and the key scenarios that it supports is included in [What is Azure Information Protection?](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection).  

That article has a section for classifying and protecting existing documents where we introduce the scanner: "For your on-premises data stores, use the Azure Information Protection scanner to discover, classify, and protect documents on local folders, network shares, and SharePoint Server sites and libraries."

**Comment by blouwagie** [comment]
Thank you Carol


Bart Louwagie
Holmes, NY
bart@louwagie.com
845 202 0239 (google voice)

http://louwagie.com
https://www.linkedin.com/in/bart-louwagie/

(when conference call is needed)

**Comment by cabailey** [comment]
#please-close
