### ISSUE TITLE
LabelingOptions - Documentation

### ISSUE THREAD

**Issue by mohanse** [MicrosoftDocs/Azure-RMSDocs#788]
Could you provide documentation for methods in LabelingOption please

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4828d4bc-f00b-b976-8d1b-8599fafb983a
* Version Independent ID: d3dcdb7d-0052-c824-cfc4-6c29626e348e
* Content: [class mip::LabelingOptions](https://docs.microsoft.com/en-us/information-protection/develop/reference/class_mip_labelingoptions)
* Content Source: [mip/develop/reference/class_mip_labelingoptions.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/reference/class_mip_labelingoptions.md)
* Service: **information-protection**
* GitHub Login: @BryanLa
* Microsoft Alias: **bryanla**

**Comment by BryanLa** [comment]
Thanks for your feedback, @mohanse. We've filed a bug with engineering on this to add the required comment decoration.

#please-close
cc: @tommoser @msmbaldwin
