### ISSUE TITLE
Detailed URL and Ports for AIP Scanner

### ISSUE THREAD

**Issue by alfino78** [MicrosoftDocs/Azure-RMSDocs#795]
What are the URL(s) and port(s) required for AIP scanner in terms of internet connectivity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@alfino78 Hi, you'll find the URLs (port 443 over HTTPS) listed in the first row of the [prerequisites table](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#prerequisites-for-the-azure-information-protection-scanner)

**Comment by cabailey** [comment]
Hi @alfino78  If this resolves your question, I'll ask for this GitHub Issue to be closed.

**Comment by cabailey** [comment]
No update & it seems your issue is addressed, but please reopen if not.
#please-close
