### ISSUE TITLE
Cloud-based protection using user-defined permissions in Word, Excel, and PowerPoint for unified labeling clients

### ISSUE THREAD

**Issue by bjornbf** [MicrosoftDocs/Azure-RMSDocs#797]
When will Cloud-based protection using user-defined permissions in Word, Excel, and PowerPoint be available for unified labeling clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to the Office 365 Security & Compliance Center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bjornbf  The technical documentation can't include information about future release plans, but if you click the **Product feedback** option, you can request this feature on the UserVoice site, or you can ask on the [Yammer site](https://www.yammer.com/AskIPTeam).

**Comment by cabailey** [comment]
#please-close
