### ISSUE TITLE
Configuring AD RMS servers to locate the certification URL

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/Azure-RMSDocs#803]
Why is Configuring AD RMS servers to locate the certification URL step needed at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d475e54-14a8-9a51-a509-782ebe7a65fa
* Version Independent ID: 164664ff-d57c-46a3-97dc-760d2365f978
* Content: [HYOK protection for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/configure-adrms-restrictions#configuring-ad-rms-servers-to-locate-the-certification-url)
* Content Source: [Azure-RMSDocs/configure-adrms-restrictions.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-adrms-restrictions.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@pawp81 It's doing the same job as a SCP, which can't be used for HYOK.

**Comment by cabailey** [comment]
@pawp81 No update & it seems this issue is addressed, but please reopen if not.
#please-close
