### ISSUE TITLE
Wording

### ISSUE THREAD

**Issue by AaronDinnage** [MicrosoftDocs/Azure-RMSDocs#804]
"RSA 1024 but is also supported"
should read
"RSA 1024 bit is also supported"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 412d9675-1c12-35f0-e1fd-d9d827216a1d
* Version Independent ID: 03d5ac22-1099-ef67-9d25-20c95fbd1d9c
* Content: [Compliance & information for Azure Information Protection](https://docs.microsoft.com/en-au/azure/information-protection/compliance#feedback)
* Content Source: [Azure-RMSDocs/compliance.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/compliance.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@AaronDinnage Thanks for flagging this typo - fixed now.

**Comment by cabailey** [comment]
#please-close
