### ISSUE TITLE
Getting error while calling FileProfile::LoadAsync

### ISSUE THREAD

**Issue by abhijsri** [MicrosoftDocs/Azure-RMSDocs#809]
When I try to use any of static function of FileProfile class I am getting ld: symbol(s) not found for architecture x86_64 error.
I have downloaded the mac os version of the library and trying to load FileProfile on Mac OS platform only. Following the instruction as provided above, added #include "mip/file/file_profile.h" in my header and c++ file.
But when I call any of static function (mip::FileProfile::GetVersion() or mip::FileProfile::LoadAsync), I am getting this error-
| =&gt; g++ -std=c++0x -I ~/mip_sdk_file_macos_1.1.217/include/  -L ~/mip_sdk_file_macos_1.1.217/bins/debug/x86_64/  Main.cpp action.cpp auth_delegate_impl.cpp auth.cpp  consent_delegate_impl.cpp file_profile_observer_impl.cpp utils.cpp pch.cpp 
Undefined symbols for architecture x86_64:
  "mip::FileProfile::GetVersion()", referenced from:
      sample::file::Action::AddNewFileProfile() in action-01139f.o
  "mip::FileProfile::LoadAsync(mip::FileProfile::Settings const&, std::__1::shared_ptr&lt;void&gt; const&)", referenced from:
      sample::file::Action::AddNewFileProfile() in action-01139f.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d41672-1477-2a65-2a7b-1922032e9a25
* Version Independent ID: 3c1c1f99-11cb-8795-ad5e-0f2a30bdc820
* Content: [Concepts - The File API profile object](https://docs.microsoft.com/en-us/information-protection/develop/concept-profile-engine-file-profile-cpp#feedback)
* Content Source: [mip/develop/concept-profile-engine-file-profile-cpp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/concept-profile-engine-file-profile-cpp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by msmbaldwin** [comment]
The most recent version of the MIP SDK, 1.7, addresses this issue. Thank you for the feedback! #please-close
