### ISSUE TITLE
Cloud App Security

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/Azure-RMSDocs#811]
This article or subsequent article: https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-labels-in-azure-information-protection-and-labels-in-office-365 

Do not make clear if Cloud App Security is wanting to be utilized to provide governance over OneDrive and SharePoint and apply a particular classification label as an action, which portal that label should be configured in. AIP? or Security and Compliance Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to the Office 365 Security & Compliance Center - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#considerations-for-unified-labels)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Mark7even  Thanks for your question about whether Microsoft Cloud App Security can support unified labels. Generally, you should consult the documentation for the specific service to determine whether it supports Office 365 sensitivity labels. But in this case, I asked & will share the response. If I get signoff from the PM, I'll add it to this page:

Microsoft Cloud App Security supports labels both before the migration to the unified labeling store, and after the migration, using the following logic: 
    - If the Office 365 Security & Compliance Center has the same labels as those in the Azure portal, and the labels have been published from the Security & Compliance Center: Labels and policy settings from the Security & Compliance Center are used.
    - If the Office 365 Security & Compliance Center doesn't have the same labels as those in the Azure portal: Labels and policy settings from the Azure portal are used. 

Using this logic, you should be able to answer which management portal to use to configure the labels that you want to use with Cloud App Security.

**Comment by Mark7even** [comment]
I appreciate the response and I would hope that's the case, but its seems that after activating Unified Labeling that "Apply classification label" in MCAS is greyed out and unable to be selected. It was working prior to Unified Labeling.

**Comment by cabailey** [comment]
And have you published the labels in the Office 365 Security & Compliance Center after the migration completed?  This required step is in the docs, but people often miss it.  If you have, and the labels still aren't available to select in Cloud App Security, please open a support ticket to get this resolved.  It would be helpful to say whether you see the labels in the Azure Information Protection unified labeling client, for comparison.

**Comment by cabailey** [comment]
I asked what would happen if you migrated your labels but didn't publish them from the Security & Compliance Center - and I think it matches what you're seeing.  Following the logic, after migration, the labels would be the same in both portals so MCAS looks for labels from SCC. If labels are published from SCC (published to any user), MCAS displays all published labels for you to select.  If labels aren't published to at least one user, there are no labels to display for selection.

**Comment by Mark7even** [comment]
Does it take time like 24 hours to show in MCAS once the labels are
published?

**Comment by cabailey** [comment]
Up to 3 hours, apparently - so I'm hoping it's working for you, now?

I'll ask the MCAS documentation team to add some clarifications if needed, in their docs.  Meanwhile, I added the logic of where/how MCAS gets the labels to display in this section: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#services-that-currently-support-unified-labeling-include

**Comment by blouwagie** [comment]
Hi @Mark7even about 2 weeks ago a lot of the synchronization of labels between AIP and MCAS was simply completely broken and affected a lot of customers wordwide. That was at least the feedback I learned from spending many hours with Microsoft Support. Ours got fixed maybe about 10 days or so ago. So I wonder if you were affected by the same issue.

**Comment by cabailey** [comment]
@Mark7even I'm assuming I can ask for this issue to be closed now, but please reopen if needed.
#please-close

**Comment by Mark7even** [comment]
Yes I verified it to be working now, thank you for the assistance and clarification.
