### ISSUE TITLE
Microsoft Cloud App Security & AIP/Labels

### ISSUE THREAD

**Issue by Mark7even** [MicrosoftDocs/Azure-RMSDocs#812]
This article or subsequent article: https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-labels-in-azure-information-protection-and-labels-in-office-365 

Do not make clear if Cloud App Security is wanting to be utilized to provide governance over OneDrive and SharePoint and apply a particular classification label as an action, which portal that label should be configured in. AIP? or Security and Compliance Portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0547cf-7694-72e8-1c35-05502fc18233
* Version Independent ID: 3bdb8088-8d87-32aa-6252-f3f9c4944adc
* Content: [FAQs for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-labels-in-azure-information-protection-and-labels-in-office-365)
* Content Source: [Azure-RMSDocs/faqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Duplicate of https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/811 
#please-close
