### ISSUE TITLE
Decrypt Office365

### ISSUE THREAD

**Issue by Cisvhenriksen** [MicrosoftDocs/Azure-RMSDocs#813]
Does not state how Exchange Online is affected by decommission? Does already protected files get inaccessible after decom ? and how come key export is a paid feature, if this is the only way to make sure you have access to protected files after decommission?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5a21021-bfaa-92e4-990c-943740a3ee8f
* Version Independent ID: fa95fb8d-be31-3ebb-d9d3-4404a8c8bee4
* Content: [Decommission & deactivate Azure RMS](https://docs.microsoft.com/en-us/azure/information-protection/decommission-deactivate#feedback)
* Content Source: [Azure-RMSDocs/decommission-deactivate.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/decommission-deactivate.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Cisvhenriksen  I'm assuming I can ask for this issue to be closed now, but please reopen if needed.
#please-close

**Comment by Cisvhenriksen** [comment]
#confused ? Don't believe answer helped in any way. SMB users unable to know if this can be disabled without loosing access to data, and Key export behind Paywall ? unsure.

**Comment by cabailey** [comment]
@Cisvhenriksen  The instructions documented apply to all services and apps that use the protection service from Azure Information Protection - there isn't anything different or specific to Exchange Online or SMB users.  If you have questions about costs or would like further discussions for your specific environment, I do encourage you to talk to your Technical Account Manager or open a support ticket (see https://docs.microsoft.com/azure/information-protection/information-support#to-contact-microsoft-support).
