### ISSUE TITLE
How to color the labels

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#818]
In this article in latest preview release notes, its mentioned that colors for the labels is supported. But how to configure the colors and where? I checked in SCC, there is no settings for labels under Classification, so wondering where to configure it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection unified labeling client - Version release information](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#feedback)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @prashant1380  Yes, you're quite right - the unified labeling client supports colors for labels, but unfortunately, the Security & Compliance Center does not have a configuration option for this and new labels you create in that portal have the default, black color.  

If you migrated labels from the Azure portal, the client shows the label colors when you hover over them in your Office apps.  After the migration, you can still configure the colors in the Azure portal for this client, but I know it's not ideal.  I'm told you can use PowerShell to configure the label colors, but I'm not sure whether this is available yet - checking for you.

**Comment by prashant1380** [comment]
Thanks @cabailey for quick response. Looking forward to know if I can somehow configure this using PS.

**Comment by cabailey** [comment]
@prashant1380 I've just been told this PowerShell support isn't yet available and I don't have an ETA, but when it becomes available, I'll add a reference on this migration article.  I've also updated my previous comment because although a new label in the Azure portal is assigned black as the default color, a new label created in SCC isn't assigned a color (so I corrected my statement to avoid confusion).  This is a fast-moving feature, so hang tight :)

**Comment by cabailey** [comment]
@prashant1380  I'm assuming I can ask for this issue to be closed now (I still have no ETA on the PowerShell release), but please reopen if needed.
#please-close
