### ISSUE TITLE
All AIP Labels and Global Policy disappeared 

### ISSUE THREAD

**Issue by mbell85** [MicrosoftDocs/Azure-RMSDocs#825]
We've been using this in my tenant for several months now. All of a sudden while working today all labels disappeared from the AIP bar for users reloading certain MS applications. When I checked in AIP blade in Azure, everything has been reset. All of our labels are gone and the "Global" policy is missing. All of the labels with protection are now back under protection templates. All of my work to add partner domains, etc. is just gone all of a sudden. What the heck is going on? I'm very upset about this...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 603aa64b-3813-ca4a-9df6-19aed2193f60
* Version Independent ID: b6ec3e81-f89f-53c6-78a8-4ed0b43dd91c
* Content: [Configure the Azure Information Protection policy - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy#feedback)
* Content Source: [Azure-RMSDocs/configure-policy.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi Mark, if you haven't already done so, please open a support ticket immediately. This is obviously unexpected behavior and I understand why you're upset. However, it might be a display issue only, so hang tight for the time being while somebody looks into this.

**Comment by mbell85** [comment]
I have filed a support ticket. Sorry for being on edge, but this is the worst possible time for this to happen. haha. We just trained the entire company on how to use AIP a couple of weeks ago. Now I'm notifying all departments to not use the AIP bar right now until this gets figured out.

**Comment by bholzmmc** [comment]
Nonetheless, it would be useful to know what happened, how it got resolved and if there's any actions as customers that would be recommended to prevent this from occurring.

**Comment by mbell85** [comment]
@bholzmmc I'll definitely follow up on here.

**Comment by mbell85** [comment]
Hey guys. Just an update. I haven't heard from Azure Support yet, but I filed with O365 Support as well after noticing the same thing had happened to all our retention labels that were previously set up in the Office Portal's Security & Compliance Center. Talking to a tech, he saw some kind of tenant-level relocation activity that initiated on our domain around the time the issue started. Believe I heard that correctly but won't swear to it.

This is something that is automated on Microsoft's end, apparently. We are waiting for Azure Support to check in and he (O365 Support) will follow up with me tomorrow. I have a feeling it may well end up working itself out, as I've seen this kind of "strange" activity happen with other features in O365 in the past (things going away only to reappear later on). Only time will tell I suppose... 

I'll be sure to update. 

Oh. And just for clarity's sake for those that may not be aware, the AIP labels in our domain actually appear in the AIP blade in Azure AND in O365 under sensitivity labels for configuration. This is a newer feature in AIP called Unified Labeling that can be enabled from the Azure Portal. We'd never had any issues with AIP until today, but then again we haven't used it on an organization-wide basis for very long, even though we've had the service for the past couple of years at least (just a department or two were using it prior and even then it didn't get used very much).

**Comment by mbell85** [comment]
So I ended up spending a good while rebuilding the policies. We are in a healthcare environment and don't have time to wait for our encryption and permissions policies to work the way they are designed to. Luckily, all of the labels that did have protection applied kept their protection settings and moved to protection templates when this happened, so we actually didn't lose that vital part of those policies (at first I thought those were gone too). All the labels without protection applied did disappear completely, but luckily I had all the definitions backed up to a Word file, so those didn't take too long to rebuild. Azure Support will look into the reason this happened in the first place, I was told. The rep kept asking me when I enabled Unified Labeling. It was at least a month ago, if not longer.

**Comment by mbell85** [comment]
And the same thing happened again ...   They disappeared 30 minutes after adding them back... Now when I try to add a label back again Azure is spitting out an error saying the label already exists... Still working with Azure Support.

**Comment by mbell85** [comment]
Whatever was going on appears to have calmed down overnight. I built the definitions back a third time late last night and they are still there this morning and have successfully synced to the O365 Security & Compliance Center again, unlike yesterday when they disappeared after rebuilding for the second time. Still no word back from Azure Support on what caused it to begin with, but I will follow up once I've heard something.

**Comment by mbell85** [comment]
Nope. It happened again. Heard back from Azure Support that the product team is aware of the ongoing issue and working towards resolution.

**Comment by mbell85** [comment]
I was contacted by a member of the Azure Information Protection Product Team this morning. They have identified about 100 organizations that are having the same issues with the disappearing labeling. They have requested we not continue to rebuild labels on the front end while they work on the backend, as they plan to restore the labeling at all affected organizations. Apparently, the fix involves both the AIP Product Team and the Security & Compliance Center Team, according to an email I received.

**Comment by mavieg** [comment]
Hello all. Thank you very much for your feedback. This issue has been resolved by our engineers and everything should be back to normal. 
If you are still experiencing any issues with your labels please open a support ticket. 
This thread will be now closed.

**Comment by mbell85** [comment]
Thank you! Appreciate the swift resolution.
