### ISSUE TITLE
How to publish labels to all organization users?

### ISSUE THREAD

**Issue by prashant1380** [MicrosoftDocs/Azure-RMSDocs#834]
As per this article i understand that if i want to scope label policy then i can use mail enabled group, but what if i want to publish labels to all users via SCC (i am not using AIP portal)? Is there any possibility to use a security group instead of mail enabled group which will hold all users? If no, then why mail enabled is required? Its difficult in organization to convince to get a mail enabled group which contains all users

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5223b524-019d-7431-6382-a33d3a104840
* Version Independent ID: d8cb57fa-6b0e-a20d-c34d-f0a54f58cab8
* Content: [Prepare users and groups for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/prepare#feedback)
* Content Source: [Azure-RMSDocs/prepare.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/prepare.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@prashant1380 When you publish labels in the Security & Compliance Center, on the "Publish these labels" page, you can select "All" for your users and groups, which sounds like what you want. But as requested, if you don't find the information you want in the Office 365 Security & Compliance documentation, please open a GitHub Issue there.  This page is specifically for Azure Information Protection.

**Comment by cabailey** [comment]
Since this is a question for a different doc set, asking for this to be closed.
#please-close
