### ISSUE TITLE
fromdate todate doesn't seem to exist

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#838]
only fromtime totime
Name             : Get-AadrmAdminLog
CommandType      : Cmdlet
Definition       :
                   Get-AadrmAdminLog -Path &lt;string&gt; [-FromTime &lt;datetime&gt;] [-ToTime &lt;datetime&gt;] [-Force] [-WhatIf]
                   [-Confirm] [&lt;CommonParameters&gt;]

Path             :
AssemblyInfo     :
DLL              : C:\Program Files\WindowsPowerShell\Modules\AADRM\2.13.1.0\Microsoft.RightsManagementServices.Online.
                   Admin.PowerShell.dll
HelpFile         : Microsoft.RightsManagementServices.Online.Admin.PowerShell.dll-Help.xml
ParameterSets    : {-Path &lt;string&gt; [-FromTime &lt;datetime&gt;] [-ToTime &lt;datetime&gt;] [-Force] [-WhatIf] [-Confirm]
                   [&lt;CommonParameters&gt;]}
ImplementingType : Microsoft.RightsManagementServices.Online.Admin.PowerShell.GetAadrmAdminLogCommand
Verb             : Get
Noun             : AadrmAdminLog

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600cf5db-0c6e-b14e-8d86-5ae5df551d6d
* Version Independent ID: ee9b0706-7f66-3537-a74f-779066357621
* Content: [Log & analyze usage of the Azure RMS service - AIP](https://docs.microsoft.com/en-us/azure/information-protection/log-analyze-usage#feedback)
* Content Source: [Azure-RMSDocs/log-analyze-usage.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/log-analyze-usage.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by bakerm00** [comment]
aadrmuserlog works fine

**Comment by cabailey** [comment]
@bakerm00 What version of the AADRM module do you have?

**Comment by cabailey** [comment]
@bakerm00 I'm not seeing an update to this - is your issue resolved now, and this can be closed?

**Comment by cabailey** [comment]
No update and I think this can be closed but please reopen it if your issue wasn't addressed.
#please-close
