### ISSUE TITLE
Use-AadrmKeyVaultKey rather than Set-AadrmKeyProperties?

### ISSUE THREAD

**Issue by jinop** [MicrosoftDocs/Azure-RMSDocs#840]
Isn't it right to use the powershell, Use-AadrmKeyVaultKey rather than Set-AadrmKeyProperties as mentioned above to use a customer-managed tenant key?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf8412fc-3bea-8925-169c-24f2f85d5fb5
* Version Independent ID: 58c2c518-b291-70f0-c146-c116e8159c17
* Content: [Your Azure Information Protection tenant key](https://docs.microsoft.com/en-us/azure/information-protection/plan-implement-tenant-key)
* Content Source: [Azure-RMSDocs/plan-implement-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/plan-implement-tenant-key.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jinop Hi, I'm not sure I understand your question. As documented, you need both cmdlets to use a customer-managed tenant key: First use Use-AadrmKeyVaultKey to specify your key URL, then use Set-AadrmKeyProperties to tell Azure Information Protection that you want to start using this key as your active tenant key. From this page "If you do not do this step [run Set-AadrmKeyProperties], Azure Information Protection will continue to use the default Microsoft-managed key that was automatically created for your tenant."

**Comment by cabailey** [comment]
Hi @jinop - is your issue resolved now with my earlier reply?  If not, can you please clarify your question.

**Comment by jinop** [comment]
Hi @cabailey. My question resolved. thanks.

**Comment by cabailey** [comment]
@jinop Thanks for the update.
#please-close
