### ISSUE TITLE
Can't open attachments protected by IRM in Outlook Web

### ISSUE THREAD

**Issue by erenoglu** [MicrosoftDocs/Azure-RMSDocs#849]
I am using Office 365 Outlook Web, but when I try to preview an attachment by clicking on it, if the attachment is protected by IRM, I can't view it. 

This forces me to revert to Outlook desktop client and breaks Outlook Web usage. (or download & open)

Is this feature supported or is this a limitation of IRM that Outlook Web is not usable for those IRM protected attachments?

**Comment by nihendle** [comment]
Hi. Currently there is no online capabilities to consume protected documents. Not in Office Online or OWA. Only documents that inherit DNF or Encrypt Only protection from the mail can be viewed inside OWA. 
This functionality is currently under work and expected later into 2019.

**Comment by cabailey** [comment]
@erenoglu  Assuming your question has been answered now, I'll ask for this to be closed but you can always reopen it, or start a new issue.
#please-close

**Comment by Crefix** [comment]
Hi!

Is the newer version (either the OWA or the new Outlook one) available to consume protected documents yet? I switched to the preview version and everytime I need to open a IRM mail I need to either switch to the old version or open the Android app
