### ISSUE TITLE
Connecting AIP to Workspace in different tenat

### ISSUE THREAD

**Issue by vrat87** [MicrosoftDocs/Azure-RMSDocs#854]
Hi Team how to connect AIP to sump data to a log analytics workspace that is in a different tenant  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b75d85e-3cea-279c-feaf-c8f828f3d201
* Version Independent ID: 97d9a1b1-4db3-a1c0-69fe-8032ce615fc7
* Content: [Central reporting for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/reports-aip)
* Content Source: [Azure-RMSDocs/reports-aip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/reports-aip.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@vrat87 Hi, thanks for your question. I had wondered if you simply needed the Azure permissions for your account that were documented.  But after checking, this won't work - the Azure subscription needs to be for the same tenant that you're using for Azure Information Protection. I've added this clarification to the prereqs.

**Comment by cabailey** [comment]
#please-close
