### ISSUE TITLE
Download client = no loger available

### ISSUE THREAD

**Issue by MichaelBerntsen** [MicrosoftDocs/Azure-RMSDocs#862]
"We're sorry, this download is no longer available." (https://www.microsoft.com/en-us/download/details.aspx?id=57440)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a4d7084-e736-2d1a-5376-58c1187a63ff
* Version Independent ID: f4942d95-dd63-6f30-6e69-a129d728068d
* Content: [Azure Information Protection unified labeling client - Version release information](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/unifiedlabelingclient-version-release-history#feedback)
* Content Source: [Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/unifiedlabelingclient-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@MichaelBerntsen You caught us in the middle of updating things :) This client has now moved to https://www.microsoft.com/en-us/download/details.aspx?id=53018 and you'll notice that this documentation page is also updated.

**Comment by cabailey** [comment]
Hi @MichaelBerntsen I haven't heard back from you for a while and this does seem to be resolved so I will ask for this documentation issue to be closed.
#please-close
