### ISSUE TITLE
IPIA requirement

### ISSUE THREAD

**Issue by hobpoblin** [MicrosoftDocs/Azure-RMSDocs#865]
Hello, it is not clear from this page if a company/organization must complete the IPIA process for an internally developed application that will not be made available to the public (e.g. commercialized software). Can you please clarify the cases where an IPIA is and is not required?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e14c03d2-f258-52ca-4530-85430e0e11b7
* Version Independent ID: a65e7b8d-62f0-58c0-d60a-1cc143ade5a5
* Content: [Microsoft Information Protection (MIP) SDK setup and configuration](https://docs.microsoft.com/en-us/information-protection/develop/setup-configure-mip#feedback)
* Content Source: [mip/develop/setup-configure-mip.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/setup-configure-mip.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by cabailey** [comment]
#assign:msmbaldwin

**Comment by laeeq** [comment]
I think IPIA requirement is only for apps, which are multi-tenant. For internal use of the Api, I dont think IPIA is required.

In fact, IPIA url is not required to run the sample apps for this Protection (MIP) SDK. I have successfully registered an app in AAD, and ran the 'mipsdk-dotnet-protection-quickstart' sample.

**Comment by msmbaldwin** [comment]
@hobpoblin: @laeeq is correct. Let us know if you require more information.  #please-close
