### ISSUE TITLE
Comparison table - DNF Button in Outlook

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/Azure-RMSDocs#866]
Hi team, you have the above twice in the first comparison table. Once as "Display the Do Not Forward button in Outlook" (8th to last) and once as "Do Not Forward button in Outlook" (3rd to last).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Michael-Sampson  Thanks for your sharp eyes!  Now fixed & will go live tomorrow morning.

**Comment by cabailey** [comment]
#please-close
