### ISSUE TITLE
MacOS refresh does not happen automatically

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/Azure-RMSDocs#868]
Is there anything more we can do for MacOS machines that don't display new templates? I routinely see up-to-date Office apps on MacOS that are not showing current templates after 48 hours. Removing and re-adding accounts doesn't address the issue, and if I've used more than one account the templates seem to get "confused" and show the wrong templates for the currently signed in user. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2af8c9c8-cf06-49a4-5f22-bba526bc2734
* Version Independent ID: 868c2079-00f4-eae3-822f-49ae6c8ef63c
* Content: [Refresh Azure RMS templates - AIP](https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates)
* Content Source: [Azure-RMSDocs/refresh-templates.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/refresh-templates.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@terrogin Are you referring to Office 2019 for Mac and/or Office 2016 for Mac?  I'm told there are multiple and various triggers that download the templates, so even though a refresh doesn't happen immediately, it should happen soon after using the app. Have you tried signing out (not switching) and signing back in again?  As far as I can remember, that should trigger a download, but there are others, so this inconvenience shouldn't be necessary.

How templates are refreshed is different in Office for Mac than for Windows so I recommend you open a support case for this so an engineer can look at some debug logging on the client to see what's going on - or not going on that should be.  When you file the support request, it would be helpful to include your exact version and build of Office, and the client operating system version.  If Windows computers download the updated templates, that would be good information to include as well (eliminate a problem service-side).

**Comment by terrogin** [comment]
I've tried signing out and back in, as well as removing the accounts and adding them back alongside other accounts, but that doesn't resolve the issue. The refresh seems to occur randomly and after great lengths of time. The windows side functions as expected as far I've ever seen. I'll continue with a support case, thanks.

________________________________

**Comment by cabailey** [comment]
@terrogin  I haven't heard back from you for a while and this does seem to be a problem for technical support to look into so I will ask for this documentation issue to be closed.
#please-close

**Comment by terrogin** [comment]
Apologies Carol! Yes, we found that the templates do not refresh on their own in some cases (in my case, it was after switching O365 accounts). The instructions I received from support, and that worked, were:

1. Open the Terminal, then type “defaults write ~/Library/Containers/com.microsoft.Outlook/Data/Library/Preferences/com.microsoft.Outlook ResetRMSCache 1"
2. Restart Outlook on Mac 
3. Compose a new email, select "Encrypt" then "Verify Credentials."

**Comment by terrogin** [comment]
Any way we can get the above added, or something similar? There is definitely the occasional need to refresh the templates on Mac when they don't happen automatically, and I often use the above to force it.

**Comment by cabailey** [comment]
@terrogin Thanks for the update!  Looking into this.

**Comment by cabailey** [comment]
@terrogin After discussions with the developers, I got more clarification on when templates should refresh automatically, so I added this to the documentation with a new section that includes the ResetRMSCache command: https://docs.microsoft.com/en-us/azure/information-protection/refresh-templates#office-2019-for-mac-and-office-2016-for-mac-how-to-force-a-refresh-for-templates

It's important to note that there is no command that will just refresh templates, however - running this command effectively deletes all cached files relating to RMS, which forces everything to reset.  They are looking into adding a template refresh action after a reboot, which would be a much better solution.

**Comment by terrogin** [comment]
That's great, thank you. The most common issue I run into that requires this kind of 'total reset' is when we're signed into Outlook on MacOS with multiple valid accounts. Removing the primary account still causes the old template information to linger, so something like this becomes necessary.
________________________________
