### ISSUE TITLE
Access denied during New-PSSession portion of the instructions

### ISSUE THREAD

**Issue by ExR90** [MicrosoftDocs/Azure-RMSDocs#869]
New-PSSession command returns the following error below. I do have MFA enabled, and don't get the MFA prompt when the Get-Credential prompt appears, not sure if that's related.

New-PSSession : [ps.outlook.com] Connecting to remote server ps.outlook.com failed with the following error message : Access is denied. For more information, see the 
about_Remote_Troubleshooting Help topic.
At line:1 char:12
+ $Session = New-PSSession -ConfigurationName Microsoft.Exchange -Conne ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingTransportException
    + FullyQualifiedErrorId : AccessDenied,PSSessionOpenFailed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0f9004-6541-428f-120f-48e1cc006e4d
* Version Independent ID: bd791ddb-d4a2-8ac4-0a7a-201bdc175c94
* Content: [Configuration for Office 365 clients and online services to use Azure RMS from AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-office365#feedback)
* Content Source: [Azure-RMSDocs/configure-office365.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-office365.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@ExR90 Sorry to hear you're having a problem with this.  I see the Office documentation (https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-new-message-encryption-capabilities) now has the same instructions, with the only difference I can see is you must be a global admin, and they don't have the step about checking the account is enabled for remote Shell access. If neither of these resolve your issue, please open a support case and let me know if there is something that is missing from the documentation. I've not heard of this error, before.

**Comment by cabailey** [comment]
@ExR90 I don't see an update from you, so I'll ask for this to be closed now. You can always reopen if you have additional feedback for the documentation.
#please-close
