### ISSUE TITLE
delegate access

### ISSUE THREAD

**Issue by brebant** [MicrosoftDocs/Azure-RMSDocs#877]
What happens if a delegate tries to read the mail of their manager? Will they be able to? Should they be able to? If they are able to read it, how can one send a encrypted mail to the manager without the delegate being able to read it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a1cb834-9023-f79b-115e-199c4e1af17b
* Version Independent ID: a0ea852a-eedd-b205-91c0-bfa8732fa9f3
* Content: [FAQs for classification & labeling - AIP](https://docs.microsoft.com/en-us/azure/information-protection/faqs-infoprotect#feedback)
* Content Source: [Azure-RMSDocs/faqs-infoprotect.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs-infoprotect.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@brebant Thanks for your question.  Mailbox delegation for protected email isn't currently supported, so the delegate will not be able to read these emails.  This scenario is under review and you might like to vote on it in the UserVoice site: https://msip.uservoice.com/forums/600097-azure-information-protection/suggestions/20038450-allow-mailbox-delegates-to-access-protected-conten

**Comment by cabailey** [comment]
#please-close
