### ISSUE TITLE
Information Types in Version 1.48.204.0

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#879]
I think more clarity is needed regarding this in the document "The following sensitive information types are no longer supported for labels that you configure for recommended or automatic classification:

EU Phone Number
EU GPS Coordinates"

Having installed this client version when using the AIPScanner, it still identifies files with these information types in the Detailed Report "Information Type Name" column.  This was kind of unexpected and they are seemingly irrelevant if none of a tenants labels can take action when they exist.    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d40811-9908-39df-a632-a31be13d9ad9
* Version Independent ID: b5c3157d-20d1-57d3-5332-41e385ebd7b9
* Content: [Azure Information Protection client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bholzmmc My understanding is that Office 365 DLP stopped supporting these sensitive information types, and we use their classification engine. So if they don't support them, we can't either, and stopped displaying them in the Azure portal so you can't select them, there. Are you seeing these sensitive information types reported by the scanner when in discovery mode, or enforcement mode?

**Comment by bholzmmc** [comment]
Discovery mode.

**Comment by cabailey** [comment]
@bholzmmc I was told that the latest client shouldn't be reporting these in discovery mode (local files on the scanner). Or were you referring to the reports in the Azure portal? (still in preview)?

**Comment by bholzmmc** [comment]
I observed them in the DetailedReport_yyyy-mm-dd_hh_mm_ss.csv file generated on the server running the scanner in C:\Users\<scanner-user>\AppData\Local\Microsoft\MSIP\Scanner\Reports.

We don’t have a Log Analytics subscription yet so I can’t view them in the Azure portal even if I wanted to.

Brian

**Comment by cabailey** [comment]
@bholzmmc Hi Brian, sorry it's taken me a while to chase this down.  It was unexpected to still see them reported in the scanner reports with this version of the client, but it's not a bug in the client itself, which takes a dependency on the Office classification engine. Taking this into account, here's an official answer to what "not supported" means in this scenario:

1. You can no longer define it as a condition in the portal
2. If you defined this in the past, we cannot ensure that the client detects it properly
3. Scanner might report it, but this info should be ignored and it will be removed from the code in future versions

In the docs, I can't say what will happen in future versions but I have now updated the following section (with a link from the version history) to reflect this additional information: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-classification#sensitive-information-types-that-require-a-minimum-version-of-the-client 

Thank you for bringing this to our attention!

**Comment by bholzmmc** [comment]
Thanks for getting back to me on this.

Brian

**Comment by cabailey** [comment]
#please-close
