### ISSUE TITLE
Clarification Required

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/Azure-RMSDocs#881]
In content consumption section step 1, it shows Azure RMS is using private key of org's tenant key pair to decrypt the policy - so Azure RMS has access to private tenant key. While on this page it states if using BYOK to create org tenant key pair, the tenant private key will be stored AKV connected HSM with no ability to export the tenant private key out of HSM. 

Does this mean in the entire section of "first use, content protection, content consumption" it is using Microsoft generated/managed tenant key scenario, not BYOK scenario? 

Thank you. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce7f3d8e-57eb-43db-e03c-3eadba114e86
* Version Independent ID: 2c3d65a1-9f43-4849-e674-f9ceda054c67
* Content: [How Azure RMS works - Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/how-does-it-work)
* Content Source: [Azure-RMSDocs/how-does-it-work.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/how-does-it-work.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@dennisxu2019 The concepts and flow for this section apply to both a Microsoft-managed key, and a customer-managed key that's stored in Key Vault (BYOK). The only difference is where the organization's key is stored. If it's stored in Key Vault, Azure Information Protection is configured to know which key to use, in which key vault.  That key vault in turn, is configured to allow access to Azure Information Protection.  For these operations, the key is not exported but accepts operations of decrypt, sign, and get.

**Comment by cabailey** [comment]
@dennisxu2019  I don't see any further questions on this, so I'll ask for this issue to be closed. You can always reopen it, or open another issue if you have questions about the documentation.
#please-close

**Comment by cabailey** [comment]
#please-close
