### ISSUE TITLE
Tenant Key Rotation Period

### ISSUE THREAD

**Issue by dennisxu2019** [MicrosoftDocs/Azure-RMSDocs#882]
Please clarify in Microsoft Managed Tenant Key scenario, how often is this tenant key rotated? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07125161-894c-d29d-cf0c-8dd2d852b3bb
* Version Independent ID: 3210c3e8-6a58-2909-27b0-072fc31c5f3d
* Content: [Microsoft-managed - AIP tenant key life cycle operations](https://docs.microsoft.com/en-us/azure/information-protection/operations-microsoft-managed-tenant-key)
* Content Source: [Azure-RMSDocs/operations-microsoft-managed-tenant-key.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/operations-microsoft-managed-tenant-key.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Hi @dennisxu2019: For a Microsoft-managed key, there is no automatic key rotation, which is why it's not included in the documentation.  If this is something that's important to you, use a customer-managed key so you have control over this operation.

**Comment by cabailey** [comment]
@dennisxu2019 If you have no further questions about this, I'll ask for this to be closed.

**Comment by dennisxu2019** [comment]
@cabailey Thank you for the clarification and I have no further question.

**Comment by cabailey** [comment]
#please-close
