### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Breaker119** [MicrosoftDocs/Azure-RMSDocs#897]
Please include screenshots with the new unified labeling client which is the recommended add-in

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c72dfc5-ed52-fb68-bcf1-db7ffcc9152f
* Version Independent ID: dab5d4fd-bab4-76d7-fdfe-7ffd487916ed
* Content: [What is Azure Information Protection? - AIP](https://docs.microsoft.com/en-us/azure/information-protection/what-is-information-protection#feedback)
* Content Source: [Azure-RMSDocs/what-is-information-protection.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/what-is-information-protection.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Breaker119 Hi, thanks for your feedback!  Yes, we'll be updating the screenshots on this page for the unified labeling client now it's gone GA, but many people will continue to use the Azure Information Protection client for a while yet. They are very similar in appearance, with a couple of small differences in Office apps. You'll find updated screenshots in the user guide: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-user-guide

**Comment by cabailey** [comment]
@Breaker119  I've introduced a couple of screenshots from the unified labeling client, and also clarified from which client the screenshots are taken - with a link that explains the differences between the two clients. This seems to offer a reasonable compromise at this time, when the clients don't yet have parity. What do you think?

**Comment by Breaker119** [comment]
Excellent!
