### ISSUE TITLE
Testing steps

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#898]
Hello,
We have migrated from AIP to Office 365 labeling, but missing now "Show bar" to be displayed per default.
Is this something missing with Office 365 labeling policy?
Are there any PowerShell maybe available to fine-tune Office 365 labeling policy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df0547cf-7694-72e8-1c35-05502fc18233
* Version Independent ID: 3bdb8088-8d87-32aa-6252-f3f9c4944adc
* Content: [FAQs for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-labels-in-azure-information-protection-and-labels-in-office-365)
* Content Source: [Azure-RMSDocs/faqs.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/faqs.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire Congratulations on the migration!  The two clients don't yet have parity and a policy setting to show the Information Protection is one of those settings that's currently missing for the unified labeling client - listed in this table as "Manage the Information Protection bar in Office apps": https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#detailed-comparisons-for-the-clients

I quite understand why you want it displayed by default, and the good news is that it will be available in a later version of the client, configurable by PowerShell.  But it's not available today.

**Comment by lightupdifire** [comment]
@cabailey,
Thanks for feedback, do you have maybe any possible ETA?

**Comment by cabailey** [comment]
@lightupdifire  I have no control over when client releases go out, so I'm not at liberty to give ETAs. You could try asking the engineering team on their Yammer site (https://www.yammer.com/askipteam) but I also recommend you clarify whether you're asking about a preview release (for testing) or a GA release (for production use).

**Comment by lightupdifire** [comment]
Thank you!
