### ISSUE TITLE
Statement on built-in support for mobile devices appears wrong.

### ISSUE THREAD

**Issue by PaulDFoster** [MicrosoftDocs/Azure-RMSDocs#899]
It says:
Built-in support for mobile devices: No deployment changes are needed for Azure RMS to support mobile devices and Mac computers. To support these devices with AD RMS, you must install the mobile device extension, configure AD FS for federation, and create additional records for your public DNS service.

I think it should say:

Built-in support for mobile devices: No deployment changes are needed for Azure Information Protection to support mobile devices and Mac computers. To support these devices with AD RMS, you must install the mobile device extension, configure AD FS for federation, and create additional records for your public DNS service.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: def1834c-64d0-0852-4684-83674246ab7b
* Version Independent ID: 733e9732-a1a9-f920-6800-6a102c2bd99f
* Content: [Compare Azure Information Protection & AD RMS - AIP](https://docs.microsoft.com/en-gb/azure/information-protection/compare-on-premise#feedback)
* Content Source: [Azure-RMSDocs/compare-on-premise.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/compare-on-premise.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@PaulDFoster Hi Paul, thanks for your question.  When you say the current statement appears wrong, the only different I'm seeing in your suggested rewording is changing Azure RMS to Azure Information Protection - is that correct? If I remember correctly, it was worded this way to compare support for Rights Management protection capabilities.  Azure RMS as a component service for Azure Information Protection still exists, which is where names gets tricky.  If we say "Azure Information Protection" here, does that denote more than protection?  If it does, I'll have a go at rewording it.

**Comment by PaulDFoster** [comment]
@cabailey Yes the wording is in comparison of RMS to AIP. In the current text it says no deployment changes are needed for RMA. Then it says to support these devices with RMS you need to install extensions etc. The second sentence contradicts the first. OR both are very unclear and need reworded IMHO.

**Comment by cabailey** [comment]
@PaulDFoster  Not sure I understand you, now.  The first sentence says no deployment changes are needed for Azure RMS - the protection service in the cloud, which is used by Azure Information Protection.  In comparison, you do need deployment changes for AD RMS - the protection service on-premises.  This article helps to unravel some of the naming complexity: https://docs.microsoft.com/en-us/azure/information-protection/aka

**Comment by PaulDFoster** [comment]
Ok I missed the subtle *Azure* RMS (which I took to be old terminology, and expected AIP) against *AD* RMS.
