### ISSUE TITLE
Track and revoke your documents

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#906]
Hello,
Track and revoke your documents not supported if used Azure Information Protection unified labeling client?
Both articles don't have this option:
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-admin-guide
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/clientv2-user-guide

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240cbda7-fa0f-83a7-4ff5-75939c76ca29
* Version Independent ID: ceaf94ad-33e9-5346-2afa-2c59924a452c
* Content: [Azure Information Protection unified labeling client for Windows](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/aip-clientv2)
* Content Source: [Azure-RMSDocs/rms-client/aip-clientv2.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/aip-clientv2.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire  You deduced correctly :)  Sounds like you might not have found our comparison tables to more easily identify which features aren't supported by the unified labeling client: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-clients

In addition, the track and revoke feature is not planned for this client: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#features-not-planned-to-be-in-the-azure-information-protection-unified-labeling-client

**Comment by lightupdifire** [comment]
@cabailey 

Yes, maybe reading less or reading too much.. :)
I would advise update this document:
https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#clients-and-services-that-support-unified-labeling

With link to this document:
https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-clients

And maybe other way around.

Because what happened, is that we used AIP via Azure for few years, we asked long time ago MS Support, to have integration between Office 365 Labels and AIP, as that time it was written in one of MS docs, that it supposed to be so, so we could use only Office 365 and not Azure portal etc.

When "migration" article become available we thought (because tracking and rest limitation not mentioned in migration doc: https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#clients-and-services-that-support-unified-labeling) that all the same will be available, except features that set in migration document, limitation/compare section:
#label-settings-that-are-not-supported-in-the-admin-centers
#comparing-the-behavior-of-protection-settings-for-a-label

Quite mix between docs and if read by day rest 20 procedures, get a "nice cocktail" ;)

So my point here maybe is to let other people to be aware regards "offered migration" doc, to inform about limitation from this doc: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client#compare-the-clients

Of course we maybe just need wait and old features will come back to Unified Labeling client..

**Comment by cabailey** [comment]
@lightupdifire OK, now added that link to https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels#clients-that-currently-support-unified-labeling-include  It will take a while for feature parity, at which stage you will probably start to see new features in the unified labeling client only, so I think adding that link will earn its keep. 

Note that just because you've migrated your labels, you don't have to use the unified labeling client - it becomes a new choice.  You can continue to use the Azure Information Protection client if there are features you need but yes, you will need to use the Azure portal to manage them.

**Comment by lightupdifire** [comment]
Thanks for all info and help!
