### ISSUE TITLE
In comparing the clients, watermarks is not commented.

### ISSUE THREAD

**Issue by jinop** [MicrosoftDocs/Azure-RMSDocs#914]
In comparing the clients, Headers and footers do not support variables for dynamic values . How about watermarks? That's all I want to tell you, team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [The client for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/use-client)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@jinop Hi Jino - watermarks are not included in the list of limitations, which means that watermarks are supported the same in the unified labeling client as in the original client. Or were you asking about using variables in watermarks, which are not supported in either client?

**Comment by jinop** [comment]
@cabailey  – Hi! I was just asking if whether using variables is supported in watermarks other than headers or footers. Thanks Carol.
