### ISSUE TITLE
Examples for SharePoint URLs are inconsistent. 

### ISSUE THREAD

**Issue by gkneale** [MicrosoftDocs/Azure-RMSDocs#915]
Item 8 describing the repositories states "For a SharePoint library: http://sharepoint.contoso.com/Shared%20Documents/Folder". However the tip below uses the example "http://sp2013/Shared Documents". Is %20 required or optional?

**Comment by cabailey** [comment]
Hi @gkneale I don't see which page you're referring to - is it https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner? Yes, the %20 is optional if you're specifying the SharePoint URL in the Azure portal. If you specify the path with PowerShell (previous version) you need the %20 if you don't use quotes around the path.

**Comment by cabailey** [comment]
Hi @gkneale  I haven't heard back from you so will assume this issue is now resolved and will ask it to be closed. If your issue remains unresolved, please reopen and provide additional information. 
#sign-off

**Comment by cabailey** [comment]
#please-close
