### ISSUE TITLE
Complex architecture

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/Azure-RMSDocs#919]
My customer has a SP 2013 farm in their own data center, and another SP 2016 on VMs in Azure. How/where should we install the AIP scanner to scan both of these systems?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e9c09ab-9d9a-5329-be18-626ab19725d1
* Version Independent ID: e6110fa2-11ac-500b-79de-95ca948159a9
* Content: [Deploy the Azure Information Protection scanner - AIP](https://docs.microsoft.com/en-us/azure/information-protection/deploy-aip-scanner#optimizing-the-performance-of-the-scanner)
* Content Source: [Azure-RMSDocs/deploy-aip-scanner.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/deploy-aip-scanner.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
Answered with this Yammer post: https://www.yammer.com/askipteam/threads/195260618244096 

In line with this answer, we recommend "Have a high speed and reliable network connection between the scanner computer and the scanned data store", which might mean installing two instances of the scanner. However, you mentioned your customer's second datastore was on a VM in Azure and the scanner is designed for on-premises data stores. Although in theory it should work, I'm not sure that second datastore would be a supported configuration. I'll look into this.

**Comment by cabailey** [comment]
Hi Dean, apologies for the delay while the PM was on vacation.  But he's now confirmed there's not a problem with this configuration being supported "as long as the network between Azure and their on prem is fast and reliable".

**Comment by cabailey** [comment]
#please-close
