### ISSUE TITLE
Correct links to regedit

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/Azure-RMSDocs#922]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/Azure-RMSDocs.cs-cz/issues/17
The user reports a typo which also appears in the en-us page

@Jakub-Urban commented 5 hours ago
There is no HKEY_CURRENT-USER but HKEY_CURRENT_USER

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be1e1c46-7da6-6abd-cf7e-508932b7f217
* Version Independent ID: c5d25e69-4b80-a517-e0b0-79e79a5a9dc1
* Content: [Azure Information Protection client admin guide](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Jakub-Urban Thanks for flagging this typo - now fixed in the English version so you can expect to see this fix in your language version soon.
#please-close
