### ISSUE TITLE
MacOS Support?

### ISSUE THREAD

**Issue by cfoulon** [MicrosoftDocs/Azure-RMSDocs#925]
Any updates on its functionality for MacOS Office365 clients?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80433bf5-fdf0-92a2-6b0d-b559511d6ce6
* Version Independent ID: 99d5c616-c99a-dbcd-4ef9-67fcf77c5133
* Content: [Configuration for clients to use Office apps with Azure RMS from AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-office-apps)
* Content Source: [Azure-RMSDocs/configure-office-apps.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-office-apps.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@cfoulon  Hi, and thanks for your question. Yes, this page needed to be updated for Office 2019, which it is now.  I've also added Office 365 apps and a new section specifically to help users protect content for the first time if they have Office for Mac.

**Comment by cabailey** [comment]
#please-close
