### ISSUE TITLE
Support for user-defined permission

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/Azure-RMSDocs#930]
Based on the table in the article, user-defined permission is now supported with the Preview version of Unified Labeling client, but not supported (and won't work properly) in Office apps with built-in labeling. Can I interpret this to mean that user-defined permission will work in Office on Windows (provided that the preview unified labeling client is installed) but not in Office on iOS/Android (since AIP client can't be installed)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to Office 365 - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bernardlam That's correct.  And more specifically, Office for Mac, which supports built-in labeling.

**Comment by bernardlam** [comment]
In this case, I think we should provide guidance that says user should publish Sensitivity Labels with user-defined permissions only if all their users are using Office on Windows and they have preview client (i.e. no one is using Office on Mac/iOS/Android). At least we should call out this scenario so IT can evaluate the benefits against the downside. (e.g. what if users apply a label through mobile Office thinking the file is protected, but in fact it's not)

**Comment by cabailey** [comment]
The guidance we provide in the previous table is "Unless you are using the preview version of the unified labeling client, we do not recommend you publish a label with this configuration".  If they do publish a label with this configuration, we tell them what the outcome is for each scenario (the GA version of the unified labeling client, the preview version of the unified labeling client, and Office apps with built-in labeling). It's then up to admins to make the decision whether to publish a label with this configuration or not. For example, an admin could create a label policy for users who only use Windows for labeling and include this label configuration that wouldn't apply to Mac users.

**Comment by cabailey** [comment]
@bernardlam This issue seems to be addressed and we'll keep listening to feedback as admins charter their decision course during this tricky transition period.
#please-close
