### ISSUE TITLE
PowerPointShapeNameToRemove does not work

### ISSUE THREAD

**Issue by gesmyrli** [MicrosoftDocs/Azure-RMSDocs#932]
We use the latest version of AIP client 1.48.204 and Office 365 ProPlus latest version

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae0fec-f7a5-e963-b304-f55755cfd3db
* Version Independent ID: bfed1edd-3fee-0ea1-b478-ddcc76e2adc3
* Content: [Custom configurations - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-customizations.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@gesmyrli  Sorry to hear you're having a problem with this. Please open a support ticket in the Azure portal (see https://docs.microsoft.com/azure/information-protection/information-support#to-contact-microsoft-support) for this to be investigated. You helpfully include the client version, but when you open the support ticket, it would be also be helpful to clarify whether this used to work for you with a previous version of the client and only a problem after upgrading, or you're configuring it for the first time with the current GA client.
