### ISSUE TITLE
Testing steps

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#935]
Hello,
Seems if Unified Labeling client deployed by Intune and we want to roll-back action and deploy classic AIP client, it is not possible to deploy because error shows that newer/client is already installed.
Besides calling Uninstall via Intune and then calling Install again, is there any other way maybe to to deploy classic AIP client when device already have UL client deployed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c12b247-129e-a67c-e463-04d506b25c0c
* Version Independent ID: 4d80d86b-2461-d088-22e9-970d84e0e283
* Content: [Install the Azure Information Protection client for users](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-install)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-install.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-install.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire As you noted, in this scenario you will need to first uninstall the unified labeling client, and then you can install the classic client. As you say, this is because of the versioning, with the classic client being 1.x and the unified labeling client being 2.x.

**Comment by lightupdifire** [comment]
@cabailey there is no way that classic can overwrite UL? like using/updating some MSI properties?

**Comment by cabailey** [comment]
I know of no supported or safe way to do this. If this is something that's important to you, consider opening a new request on the UserVoice site for Azure Information Protection, and explain your business case: https://msip.uservoice.com

**Comment by lightupdifire** [comment]
Thanks, will do!
