### ISSUE TITLE
localization of header/footer/watermark

### ISSUE THREAD

**Issue by sebhe** [MicrosoftDocs/Azure-RMSDocs#940]
What about the header/footer/watermark. Can this be localized as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bf4357-5354-9750-bee2-3204f85b5743
* Version Independent ID: 82dd2f29-441d-0d9b-3bd4-7d056981017a
* Content: [Configure labels for different languages in Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-languages)
* Content Source: [Azure-RMSDocs/configure-policy-languages.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-languages.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@sebhe Unfortunately, no.  What is and isn't support for different languages for the Azure Information Protection client is documented here: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide#support-for-multiple-languages

**Comment by sebhe** [comment]
Thanks for your fast feedback. What a pity that this is not possible, but anyway thanks for your fast response! highly appreciated

**Comment by cabailey** [comment]
#please-close
