### ISSUE TITLE
AIP Label

### ISSUE THREAD

**Issue by Yoeeee** [MicrosoftDocs/Azure-RMSDocs#942]
[How to delete or rename a label using powershell?]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3441623-7282-17bc-582b-fb08efb80e48
* Version Independent ID: 61b9821f-f40e-0e55-e7b1-b466391ecb0a
* Content: [Delete or reorder an Azure Information Protection label - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-delete-reorder#feedback)
* Content Source: [Azure-RMSDocs/configure-policy-delete-reorder.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-delete-reorder.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Yoeeee There is no Azure Information Protection PowerShell support to delete or rename a label from the Azure portal. However, if your labels are using the unified labeling store, you might be able to do this with Office 365 Security & Compliance Center PowerShell (https://docs.microsoft.com/en-us/powershell/exchange/office-365-scc/office-365-scc-powershell?view=exchange-ps). If you need help with that module, leave feedback on that page for the Office team.

**Comment by cabailey** [comment]
@Yoeeee  Some good news for you: The Office team has just published documentation for Remove-Label (https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/remove-label?view=exchange-ps) and Set-Label (https://docs.microsoft.com/en-us/powershell/module/exchange/policy-and-compliance/set-label?view=exchange-ps) that you use with -DisplayName to rename a sensitivity label.

**Comment by cabailey** [comment]
@Yoeeee Now you have an answer for Azure Information Protection labels in the Azure portal, and for sensitivity labels, this issue is addressed so I'll ask for it to be closed.
#please-close
