### ISSUE TITLE
Usage Rights (Reply, Reply All)

### ISSUE THREAD

**Issue by Yoeeee** [MicrosoftDocs/Azure-RMSDocs#946]
I am confused by the usage rights for reply and reply all. Based on the description the receiver of the email doesn't have the rights to add anyone on the email? am I right? Please see the usage right/description below
But the behavior of the permissions in AIP Label configuration, if you toggle off the reply or reply all. It will only disable the functionality of the button for reply and reply all.

Scenario:
If you toggle on either reply or reply all in the configuration of AIP Label. It doesn't follows the description given to the usage rights. The receiver of the email can still add another recipient (to/cc) to the email and they can still have an access to the email.

Based on my understanding if you toggle on the reply and reply all on the permissions. You will be able to use the button for reply and reply all. But doesn't not have a restriction like what is written on the description.
Hope you can give me a clear explanation to the description of the usage rights. Thank you in advance.

**Usage Rights/Description**
Reply - Enables the Reply option in an email client, without allowing changes in the To or Cc lines
Reply All - Enables the Reply All option in an email client, but doesn’t allow the user to add recipients to the To or Cc lines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5089be5-ab21-9713-24cf-e88b3de6596f
* Version Independent ID: 00db5cf0-54f1-8a93-1ff9-75c3848e3869
* Content: [Configure usage rights for Azure Information Protection](https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights)
* Content Source: [Azure-RMSDocs/configure-usage-rights.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-usage-rights.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Yoeeee  To confirm your scenario: What total permissions (usage rights) are you granting the recipient when you test with Reply (or Reply All), and what email client is the recipient using on a different computer?

**Comment by Yoeeee** [comment]
btw we already resolved the issue. 
I used reviewer permission for our Confidential label. For the solution, fist we apply a label and then we used the "Do Not Forward" to make the label more secured to avoid the receiver of the email to add another user/email.

**Comment by cabailey** [comment]
Thanks for letting me know this is resolved.
#please-close
