### ISSUE TITLE
Office Windows client

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/Azure-RMSDocs#948]
This page is pointing to check for supported unified clients on:
https://support.office.com/en-us/article/apply-sensitivity-labels-to-your-documents-and-email-within-office-2f96e7cd-d5a4-403b-8bd7-4cc636bae0f9

There is a statement:
Windows - Word, Excel, PowerPoint, Outlook - Coming soon to the Office Insider program

This page is showing this information more than a year, and is still part of Office Insider program

Please update correct page with current information and status about availability of unified labeling for Office desktop apps on Windows

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b8e206-aa49-f558-09d4-506f5c725337
* Version Independent ID: 5169a618-9dea-3349-c365-0b16b57560c6
* Content: [Migrate Azure Information Protection labels to Office 365 - AIP](https://docs.microsoft.com/en-us/azure/information-protection/configure-policy-migrate-labels)
* Content Source: [Azure-RMSDocs/configure-policy-migrate-labels.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/configure-policy-migrate-labels.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@hkusulja  The link referenced is still an authoritative source of information for Office apps on Windows to support built-in sensitivity labels.  For feedback about the information on that page, please use the feedback mechanism provided at the bottom of the page, where it asks "Was this information helpful?"

However, as a secondary source of information, you might find it helpful to also check the Microsoft 365 Roadmap (see https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=sensitivity). 

#please-close
