### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/Azure-RMSDocs#954]
Hello,
Regards "This client, also known as just the unified labeling client, is replacing the Azure Information Protection client (classic)"
Is it really replacing classic client? Classic client will be stopped? Any known dates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 240cbda7-fa0f-83a7-4ff5-75939c76ca29
* Version Independent ID: ceaf94ad-33e9-5346-2afa-2c59924a452c
* Content: [Azure Information Protection unified labeling client for Windows](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/aip-clientv2)
* Content Source: [Azure-RMSDocs/rms-client/aip-clientv2.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/aip-clientv2.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@lightupdifire Your question seems to be answered now, so I'll ask for this issue to be closed.
#please-close
