### ISSUE TITLE
Not able to set label on PDF file stream

### ISSUE THREAD

**Issue by garima2510** [MicrosoftDocs/Azure-RMSDocs#966]
I am trying the above code to set a label on PDF file Stream that is coming from SharePoint. If the label is less secure, it works but for maximum secure label it is failing with the following error:

ServiceDiscoveryHelper::GetServiceDetails - Cannot compute domain: license domains, identity, and cloud endpoint base URL are all empty, correlationId:[3583e03c-9d67-4cf7-afd8-000063567326]

The same code works if pdf is passed through file path from local machine. Any help!

**Edit 31/07/2019**

I am able to make it work using admin account as identity while creating File Engine Settings. The complete code can be found here [code](https://mysharepointlearnings.wordpress.com/2019/07/26/using-mip-sdk-in-sharepoint/)

Check line 40.

My problem is, since I am using **app-only permissions**, the label on files are set using app identity registered in Azure AD. This works for office files but for PDF, even though the label is applied, AIP client is not able to open it and says, - You are not authorized. The label I am applying has view rights for everyone in the tenant. 

I would really appreciate some details on it. Thanks.

**Edit 02/08/2019**

I tried passing user id in Delegate Email part of Identity but the code fails with the following error:

> The service didn't accept the auth token. AuthChallenge:[Bearer resource="https://aadrm.com", realm="---", authorization="https://login.windows.net/tenantid/oauth2/authorize"], correlationId:[2d3c9fa2-cbe7-4350-9172-00006e9a41ad]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46b0a2b2-7502-f245-9d9b-4bf566633065
* Version Independent ID: f7f5635e-44ec-c1cc-ac35-2ecf57790248
* Content: [Quickstart - Set and get a sensitivity label on a file using the C# MIP SDK](https://docs.microsoft.com/en-us/information-protection/develop/quick-file-set-get-label-csharp)
* Content Source: [mip/develop/quick-file-set-get-label-csharp.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/mip/develop/quick-file-set-get-label-csharp.md)
* Service: **information-protection**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by garima2510** [comment]
Any updates please!

**Comment by nikagarwal** [comment]
@garima2510  I am seeing similar kind of error when I am trying to protect a .txt file using MIP c++ SDK.
`The service didn't accept the auth token. AuthChallenge:[Bearer resource="https://aadrm.com", realm="", authorization="https://login.windows.net/common/oauth2/authorize"]'`

Any idea what cause this and how to resolve this.

**Comment by garima2510** [comment]
@nikagarwal No I was not able to resolve it yet. Everything works perfectly if I do not provide admin id as delegate email but else it fails.

**Comment by cabailey** [comment]
#assign:msmbaldwin

**Comment by mlottner** [comment]
@msmbaldwin Can you take a look?
