### ISSUE TITLE
Support period

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/Azure-RMSDocs#974]
"Each general availability (GA) version of the Azure Information Protection client is supported for up to six months after the release of the subsequent GA version."
Despite this statement, 1.48.204.0 is listed as being supported until 2/15/2020, which is 7 months after the 7/15/2019 release of 1.53.10.0. Should the period mentioned be "at least six months", not "up to six months"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28d40811-9908-39df-a632-a31be13d9ad9
* Version Independent ID: b5c3157d-20d1-57d3-5332-41e385ebd7b9
* Content: [Azure Information Protection client - Version history & support policy](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history)
* Content Source: [Azure-RMSDocs/rms-client/client-version-release-history.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-version-release-history.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@dcbrown16  No, the support statement is accurate - the date for this specific release was out by a month so either a miscalculation or a typo. Now fixed.  Thanks for flagging!

**Comment by dcbrown16** [comment]
I see, thank you.
