### ISSUE TITLE
Microsoft Information Protection (MIP)

### ISSUE THREAD

**Issue by runemy** [MicrosoftDocs/Azure-RMSDocs#976]
Hi

It's not clear to me what Microsoft Information Protection (MIP) is. Is it the same as "Unified Labeling"? Is it a new version (next version) of AIP? Is it an umbrella of different products like AIP & ATP?

Please add MIP to: https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/terminology.md

With reference to:
* https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Difference-between-Azure-Information-Protection-and-Microsoft/m-p/270667
* http://pewinther.blogspot.com/2019/04/what-is-mip-microsoft-information.html

**Comment by cabailey** [comment]
Hi @runemy  We actually have an FAQ for this question: https://docs.microsoft.com/en-us/azure/information-protection/faqs#whats-the-difference-between-azure-information-protection-and-microsoft-information-protection 

Do you think a terminology entry is still needed?

**Comment by runemy** [comment]
Hi. Thanks for your answer. Yes, personally I think it can be relevant to link to this FAQ from this terminilogy page: https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/terminology.md

Do you know if ATP (advanced threat protection) is a part of this MIP Framework?

**Comment by cabailey** [comment]
@runemy OK, I'll look at adding an entry to the terminology page - good to know you use that resource!

Yes, Windows Defender ATP supports the Microsoft Information Protection framework: 
- https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Discover-and-protect-sensitive-data-through-Azure-Information/ba-p/297292
- https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/information-protection-in-windows-overview

**Comment by cabailey** [comment]
@runemy I've now updated the terminology page with an entry for "Microsoft Information Protection", and "unified label". Thanks for your feedback!
#please-close
