### ISSUE TITLE
Second "Service" may need to be excluded

### ISSUE THREAD

**Issue by XhellarchX** [MicrosoftDocs/Azure-RMSDocs#980]
Step [Disconnect from the service]
Typo ; Disconnect-AipServiceService

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9edb2c-4c7e-f9f5-a7fc-74c475dd083e
* Version Independent ID: 27d918c1-55e4-024b-35e6-2a9621b95cd7
* Content: [Use PowerShell with the Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-powershell#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-powershell.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-powershell.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@XhellarchX  Thanks for flagging this - you're quite right. I'll fix this today.

**Comment by cabailey** [comment]
Fixed now
#please-close
