### ISSUE TITLE
alignment with official blog article - major inconsistency

### ISSUE THREAD

**Issue by bakerm00** [MicrosoftDocs/Azure-RMSDocs#982]
https://techcommunity.microsoft.com/t5/Azure-Information-Protection/Auditing-sensitive-data-on-Windows-endpoints-using-the-Azure/bc-p/807985#M346

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae0fec-f7a5-e963-b304-f55755cfd3db
* Version Independent ID: bfed1edd-3fee-0ea1-b478-ddcc76e2adc3
* Content: [Custom configurations - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#disable-sending-discovered-sensitive-information-in-documents-to-azure-information-protection-analytics)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bakerm00  Thanks for your feedback.  Please explain the inconsistency you're seeing.

**Comment by bakerm00** [comment]
RunAuditInformationTypesDiscovery v RunAuditInformationTypeDiscovery

Language denotes difference between Opt in and Opt Out.    false v true
not all values are accounted for.

Premier support are also confused.

________________________________

**Comment by cabailey** [comment]
@bakerm00  Gotcha - there have been some confusions around this feature when it first came out, including the exact setting name and whether it's enabled by default or not.  We've been looking into this and made clarifications/updates in the docs, but those updates aren't yet reflected in the blog post. We've also updated the version history for release 1.48.204.0  when endpoint discovery was added to the client, to better explain how it works: https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-version-release-history#version-1482040

If Premier Support is confused, please ask them to contact me - they know how to do this.

**Comment by cabailey** [comment]
@@bakerm00  I see from your support ticket that you also got confirmation from them that the current documentation is correct, so closing this issue.
#please-close
