### ISSUE TITLE
Client configuration settings not made through portals.

### ISSUE THREAD

**Issue by bholzmmc** [MicrosoftDocs/Azure-RMSDocs#983]
In the section https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#disable-sending-discovered-sensitive-information-in-documents-to-azure-information-protection-analytics  it says, "Providing the client isn't configured to not sent audit information" - however there is no reference on how this can be checked.  Where is information on client configuration settings that aren't made through the AIP or SC&C portals settings or it's Advanced Client Settings ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ae0fec-f7a5-e963-b304-f55755cfd3db
* Version Independent ID: bfed1edd-3fee-0ea1-b478-ddcc76e2adc3
* Content: [Custom configurations - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-customizations#enable-azure-information-protection-analytics-to-discover-sensitive-information-in-documents)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-customizations.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-customizations.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@bholzmmc   This setting is done in the Azure portal, using the policy setting "Send audit data to Azure Information Protection log analytics".   This is a really long setting name, so rather than just add it to the existing text, I've clarified it with an additional paragraph.  Thanks for your feedback!

**Comment by cabailey** [comment]
#please-close
