### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by iaasazure** [MicrosoftDocs/Azure-RMSDocs#985]
This chrome screenshot in the doc is incorrect.
https://admin.na.aadrm.com/admin/admin.svc
IE still trusts the site but Chrome reports 'Not secure'
Edge Chromium also doesnt trust the site.
The server presented a certificate that wasn't publicly disclosed using the Certificate Transparency policy. This is required for some certificates to make sure they are trustworthy and to protect against attackers.
Qualsys SSL Labs reports the site as untrusted grade T
https://www.ssllabs.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f3f6498-91c2-77f6-d962-78f6546804fa
* Version Independent ID: 20550cb6-6a27-8d8c-2e61-5c0a322c3cf1
* Content: [Requirements for Azure Information Protection - AIP](https://docs.microsoft.com/en-us/azure/information-protection/requirements#feedback)
* Content Source: [Azure-RMSDocs/requirements.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/requirements.md)
* Service: **information-protection**
* Sub-service: **prereqs**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@iaasazure  Thanks for reporting this change.  Investigating.

**Comment by cabailey** [comment]
@iaasazure Because the URL  isn't designed to be customer-facing, I'm not sure when/if the certificate will be updated for the Certificate Transparency policy. So instead, I've replaced the browser check instructions with PowerShell commands that do the same job, but unfortunately, aren't as quick/easy as the original browser check.

**Comment by cabailey** [comment]
@iaasazure Had a chance to try this?  Since the documentation is now updated for this issue, I'll ask for this to be closed but you can reopen it if you have problems with the alternative now provided in the docs.
#please-close
