### ISSUE TITLE
.doc missing from File types supported for inspection

### ISSUE THREAD

**Issue by grex86** [MicrosoftDocs/Azure-RMSDocs#989]
in the Word line .doc is missing. Is it a typo or is this true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a8ab6d-63a2-dd69-7394-dd1d1577507c
* Version Independent ID: 57385923-cbf3-1cc7-a4b7-89d93e7a83ae
* Content: [File types supported - Azure Information Protection client](https://docs.microsoft.com/en-us/azure/information-protection/rms-client/client-admin-guide-file-types#supported-file-types-for-classification-and-protection)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-file-types.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/rms-client/client-admin-guide-file-types.md)
* Service: **information-protection**
* Sub-service: **v1client**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@grex86 It does seem unlikely that .doc is missing - checking.  Thanks for flagging this!

**Comment by cabailey** [comment]
@grex86 As suspected, .doc is supported but somehow got missed off the list (along with .dot) - not sure how we missed this before.  Both are now added.
#please-close
