### ISSUE TITLE
Migrate-client / user.cmd scripts

### ISSUE THREAD

**Issue by Lexy2** [MicrosoftDocs/Azure-RMSDocs#993]
Where can I download these scripts? The page doesn't seem to have a link for them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0d29ee-00b5-5a48-b259-d62e75c22d05
* Version Independent ID: 8c6632dc-5926-a431-7f7b-f3f2469170f6
* Content: [Migrate AD RMS-Azure Information Protection - Phase 3](https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase3)
* Content Source: [Azure-RMSDocs/migrate-from-ad-rms-phase3.md](https://github.com/Microsoft/Azure-RMSDocs/blob/master/Azure-RMSDocs/migrate-from-ad-rms-phase3.md)
* Service: **information-protection**
* Sub-service: **migration**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by cabailey** [comment]
@Lexy2 It's part of the preparation phase (https://docs.microsoft.com/en-us/azure/information-protection/migrate-from-ad-rms-phase1#step-2-prepare-for-client-migration) - see step 3 for the link and zipped file name.

**Comment by cabailey** [comment]
@Lexy2 Since this information is provided in the documentation, I'll ask for this issue to be closed
#sign-off
